### ISSUE TITLE
Equivalent of selector: for Windows / Linux menu items

### ISSUE THREAD

**Issue by paulcbetts** [atom/atom-shell#1001]
Is there an equivalent of `selector:` for menu items that can be used to implement natively-implemented menu items such as Undo or Cut? Or in other words, how can I make a "Edit => Cut" top level menu item that works on Windows / Linux?

**Comment by zcbenz** [comment]
On Linux and Windows there is no equivalent of `selector:` and you have to call editing related APIs directly. Chrome has provided [APIs](https://code.google.com/p/chromium/codesearch#chromium/src/content/public/browser/web_contents.h&q=webcontents&sq=package:chromium&type=cs&l=368) to execute editing commands on web pages, do you want them exposed in atom-shell?

**Comment by CharlieHess** [comment]
That would be lovely. :+1:
