### ISSUE TITLE
SquirrelAwareVersion=1 is forced on all apps

### ISSUE THREAD

**Issue by joshuawarner32** [atom/atom-shell#1008]
I'm building a custom app that I'm now trying to integrate with Squirrel.Windows.

For the moment, I'd like to be able to rely on Squirrel's default behavior for installing shortcuts, etc.  This is what SquirrelAwareVersion is supposed to control: apps without it, or with something other than "1" for a value, are supposed to fall back on the default behavior.

There are two problems with this:
* The value of SquirrelAwareVersion actually doesn't matter right now: https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Squirrel/SquirrelAwareExecutableDetector.cs#L81
* The rcedit tool doesn't seem to have the ability to remove keys from the version information block.

These together mean that, without a custom build, and without something fancier than rcedit.exe, everybody using atom-shell is forced to accept this behavior.

There are of course multiple bugs / features-that-could-be-added here, and thus many ways to attack the problem.

Solutions include:
* Adding the ability to remove version block entries to rcedit.exe
* Fix the Squirrel.Windows bug that leads to the actual value being ignored.  I can then put a completely bogus value there using rcedit.exe.

But I would propose this:
* Get rid of SquirrelAwareVersion=1 from atom.rc in this repository
* Add/modify a build step in Atom itself that runs rcedit.exe to add this key back

I can probably help with this, if you (atom-shell folk) agree this is a decent direction in which to proceed.

**Comment by paulcbetts** [comment]
I actually would rather that Atom Shell's built-in `auto-updater` were to help you out with implementing Squirrel.Windows callbacks and allow you to check for updates, but I realize that this is a more complicated change (it is the direction we want to go though moving forward)

**Comment by joshuawarner32** [comment]
@paulcbetts, I'm certainly open to taking that approach (in lieu of a more short-term solution), as long as the timeline doesn't snowball because of it.

What would be involved there?

**Comment by paulcbetts** [comment]
@joshuawarner32 So, there are a few parts, I'll copy-paste relevant code snippets from our app which, while not complete, should give you some ideas:

* Implement checkForUpdates and the events on Windows using Squirrel:

```coffee
checkForUpdates: (url) -> 
  updateDotExe = path.resolve path.dirname(process.execPath), '..', 'update.exe'
  return unless fs.existsSync(updateDotExe)

  proc = spawn updateDotExe, ['--update', url]
  proc.stdout.on 'data', (m) -> logger.info("Update: " + m)
  proc.stderr.on 'data', (m) -> logger.info("Update: " + m)
```

* Create an API for adding / removing shortcuts

```coffee
# Private: Forks to Squirrel in order to install or update our app shortcut on
# the Desktop and in the Start Menu on Windows
#
# finish - A callback to be invoked on completion
#
# Returns Nothing
installShortcuts = (finish) ->
  target = path.basename(process.execPath)
  updateDotExe = path.resolve path.dirname(process.execPath), '..', 'update.exe'
  spawn(updateDotExe, ['--createShortcut', target]).on('exit', finish)

# Private: Forks to Squirrel in order to remove our app shortcut on the Desktop
# and in the Start Menu on Windows. Called on app uninstall.
#
# finish - A callback to be invoked on completion
#
# Returns Nothing
uninstallShortcuts = (finish) ->
  target = path.basename(process.execPath)
  updateDotExe = path.resolve path.dirname(process.execPath), '..', 'update.exe'
  spawn(updateDotExe, ['--removeShortcut', target]).on('exit', finish)
```

* Handle Squirrel Events, as **early in app startup as possible** (in our app, this is literally the first method called in the application). We hard-code this, but you would want to instead allow the dev to customize these callbacks, as long as it terminates the app for you after the callback.

```coffee
# Private: When our app is installed, Squirrel (our app install/update framework)
# invokes our executable with specific parameters, usually of the form
# '--squirrel-$EVENT $VERSION' (i.e. '--squirrel-install 0.1.0'). This is our
# chance to do custom install / uninstall actions. Once these events are handled,
# we **must** exit immediately
#
# appStart - A callback to be invoked to start the application if there are no
#            Squirrel events to handle.
#
# Returns Nothing
handleSquirrelEvents = (appStart) ->
  options = process.argv[1..]
  unless options and options.length >= 1
    appStart()
    return

  m = options[0].match /--squirrel-([a-z]+)/
  unless m and m[1]
    appStart()
    return

  if m[1] is 'firstrun'
    appStart()
    return

  app.on 'ready', ->
    switch m[1]
      when 'install' then installShortcuts(app.quit)
      when 'updated' then installShortcuts(app.quit)
      when 'uninstall' then uninstallShortcuts(app.quit)
      when 'obsolete' then app.quit()
```

**Comment by joshuawarner32** [comment]
I have those handlers integrated and working in my custom app (thanks!).  Were you thinking those would get integrated into atom-shell itself?  If so, where?  There's not a whole lot of javascript code (AFAICT) that executes before the app's main.

**Comment by kevinsawicki** [comment]
> Were you thinking those would get integrated into atom-shell itself?

Yeah, there is a plan to add more windows squirrel helpers to the `auto-update` class, https://github.com/atom/atom-shell/issues/939

**Comment by joshuawarner32** [comment]
Ah, cool.  Sounds like this is mostly a dup of #939, then.
