### ISSUE TITLE
Handling uncaught exceptions on browser (node) side

### ISSUE THREAD

**Issue by joshuawarner32** [atom/atom-shell#1012]
I'd like to be able to set up my own `uncaughtException` handler in my atom-shell app, for two purposes:
* To log the error to our client log file
* (Potentially) include it in an error report we send to the server
* Present a slightly more user-friendly dialog that doesn't go into details that wouldn't help the user

To that end, I've tried two things, and in neither case is my custom error-handling code called.  In both cases, the atom-shell error dialog (with a stack trace) pops up.

Both of these are running at the very beginning of main.js, located in an appropriately placed "app.asar".  Here "boom" is undefined, and hence causes an exception:

Try 1:
```
process.on('uncaughtException', function() {
  console.log("caught from process");
});
boom();
```

Try 2:

```
var d = require('domain').create();
d.on(error, function(err) {
  console.log("caught from domain");
});
d.run(function() {
  boom();
});
```

Is there some way to do this I'm not thinking of?  Would this require modifications in atom-shell itself?

**Comment by paulcbetts** [comment]
We've had problems with this too
