### ISSUE TITLE
not able to install asar package

### ISSUE THREAD

**Issue by JW-Vinayak** [atom/atom-shell#1013]
Hi,

I want to convert my atom-shell app into asar archive. Used "npm install -g asar" command to install asar and it throws following error. Can you please give me some pointers as in what is going wrong?

		D:\>npm install -g asar
		-
		> native-mate@0.2.6 install C:\Users\mote_v\AppData\Roaming\npm\node_modules\asar\node_modules\chromium-pickle\node_modules\native-mate
		> echo

		ECHO is on.

		> chromium-pickle@0.1.4 install C:\Users\mote_v\AppData\Roaming\npm\node_modules\asar\node_modules\chromium-pickle
		> node-gyp rebuild

		C:\Users\mote_v\AppData\Roaming\npm\node_modules\asar\node_modules\chromium-pickle>node "D:\Softwares\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" r
		ebuild
		Warning: Missing input files:
		C:\Users\mote_v\AppData\Roaming\npm\node_modules\asar\node_modules\chromium-pickle\node_modules\native-mate\tests\compilation.cc
		Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
		C:\Users\mote_v\AppData\Roaming\npm\node_modules\asar\node_modules\chromium-pickle\node_modules\native-mate\vendor\base-minimal\base.vcxproj(18,3): error MSB4019: The imported project "C:\M
		icrosoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
		C:\Users\mote_v\AppData\Roaming\npm\node_modules\asar\node_modules\chromium-pickle\node_modules\native-mate\native_mate.vcxproj(18,3): error MSB4019: The imported project "C:\Microsoft.Cpp.
		Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
		gyp ERR! build error
		gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
		gyp ERR! stack     at ChildProcess.onExit (D:\Softwares\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
		gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
		gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
		gyp ERR! System Windows_NT 6.1.7601
		gyp ERR! command "node" "D:\\Softwares\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
		gyp ERR! cwd C:\Users\mote_v\AppData\Roaming\npm\node_modules\asar\node_modules\chromium-pickle
		gyp ERR! node -v v0.10.35
		gyp ERR! node-gyp -v v1.0.1
		gyp ERR! not ok

		npm ERR! chromium-pickle@0.1.4 install: `node-gyp rebuild`
		npm ERR! Exit status 1
		npm ERR!
		npm ERR! Failed at the chromium-pickle@0.1.4 install script.
		npm ERR! This is most likely a problem with the chromium-pickle package,
		npm ERR! not with npm itself.
		npm ERR! Tell the author that this fails on your system:
		npm ERR!     node-gyp rebuild
		npm ERR! You can get their info via:
		npm ERR!     npm owner ls chromium-pickle
		npm ERR! There is likely additional logging output above.
		npm ERR! System Windows_NT 6.1.7601
		npm ERR! command "D:\\Softwares\\nodejs\\\\node.exe" "D:\\Softwares\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "asar"
		npm ERR! cwd D:\
		npm ERR! node -v v0.10.35
		npm ERR! npm -v 1.4.28
		npm ERR! code ELIFECYCLE
		npm ERR! not ok code 0

**Comment by JW-Vinayak** [comment]
Sorry for posting this issue here instead of posting it in asar project. Do let me know if I have to close this issue here and post it there.

**Comment by zcbenz** [comment]
Yeah please reopen this issue in the asar repo.

And have you tried to install other native modules like `runas`? It seems like a problem of your building environment.
