### ISSUE TITLE
Add support for window transparency.

### ISSUE THREAD

**Issue by wildfiremedia** [atom/atom-shell#1015]
Can you share more info for this fix in 0.20.6?

I have an idea to start Atom-shell in transparency window, not Aero Glass instead of flashing a blank white screen before the page/content is render. This will less strain on our eyes vision.

**Comment by zcbenz** [comment]
You can find the documents at:
https://github.com/atom/atom-shell/blob/master/docs/api/frameless-window.md#transparent-window
