### ISSUE TITLE
Asar.js error with module

### ISSUE THREAD

**Issue by wildfiremedia** [atom/atom-shell#1021]
Tried to test with the latest atom-shell with this module and added a code ``` var jazz = require('jazz-midi'); ```
https://www.npmjs.com/package/jazz-midi

I get an error
```
c:\Users\joe\Desktop\atom-shell-win32-ia32\resources\atom\common\lib\asar.js:422 Uncaught Error: %1 is not a valid Win32 application.
c:\Users\joe\Desktop\atom-shell-win32-ia32\node_modules\jazz-midi\bin\win32\jazz.node
```

It seems there is a bug in asar.js or Jazz problem?

**Comment by zcbenz** [comment]
You have to follow the [tutorial](https://github.com/atom/atom-shell/blob/master/docs/tutorial/using-native-node-modules.md) to install native Node modules.
