### ISSUE TITLE
remote.getCurrentWindow() - clarify documentation

### ISSUE THREAD

**Issue by bpasero** [atom/atom-shell#1035]
The documentation reads: "Returns the BrowserWindow object which represents the current window.". As a user of this API I am not fully understanding the behavior of this method when I have multiple browser windows open at the same time: Does it return the browser-window which is currently active/focussed? Or does it return the browser-window which is associated with the render process. 

I would assume/hope the latter, but please clarify.

**Comment by zcbenz** [comment]
> Or does it return the browser-window which is associated with the render process.

Yeah it will return the window that the web page belongs to. I'll make it more clear in docs.

**Comment by bpasero** [comment]
Thanks, that is what I was expecting how it behaves :)
