### ISSUE TITLE
Access to localStorage from browser side

### ISSUE THREAD

**Issue by bpasero** [atom/atom-shell#1037]
This might be wishful thinking, but is there any way to expose localStorage to the browser side in Atom? My understanding is that Chrome switches from Renderer to Browser process anytime you access window.localStorage so my hope would be that localStorage can just be available on the browser side?

My motivation is storing and restoring window state: Ideally I can do this from the browser side where I also create the BrowserWindow. Since I want to use localStorage, I need access from the browser side but I am not sure how to get at it from there without DOM access.

**Comment by zcbenz** [comment]
You can simply write window state to a file if you want to access it in browser process. Accessing localStorage from browser side would be a wrong design under most cases.
