### ISSUE TITLE
Minimizing a window as soon as it is shown causes it to stop loading

### ISSUE THREAD

**Issue by CharlieHess** [atom/atom-shell#1040]
Create a `BrowserWindow` and perform this sequence of operations:
``` coffeescript
@window.loadUrl targetUrl
@window.show()
@window.minimize()
```
Calling `minimize` seems to cancel the load entirely. Calling `restore` on the window does not cause it to resume loading.

**Comment by zcbenz** [comment]
I can not reproduce this, can you share a simple app which shows this problem?

**Comment by bwin** [comment]
Also please provide your atom-shell version and os version.

**Comment by zcbenz** [comment]
I'm closing this unless there is more information.
