### ISSUE TITLE
Transparency doesn't work in resizable windows

### ISSUE THREAD

**Issue by darsain** [atom/atom-shell#1041]
From [docs](https://github.com/atom/atom-shell/blob/master/docs/api/frameless-window.md#transparent-window):

> Transparent window is not resizable, setting resizable to true may make transprent window stop working on some platforms.

This is a huge limitation. Is this set in stone (if so, what is the reason), or is there a possible fix incoming in a foreseeable future?

**Comment by zcbenz** [comment]
It is quite hard to fix because the way transparent window works is quite different to normal windows, but I think I will have a try in future.

**Comment by zcbenz** [comment]
I now don't think anyone would look into this, so I'm closing this now. We will still accept it if someone sends a pull request.

**Comment by wu-sv** [comment]
Has this issue still not been resolved yet?
