### ISSUE TITLE
Trouble unzipping the mac app with node

### ISSUE THREAD

**Issue by reggi** [atom/atom-shell#1042]
I've used a ton of different unzipping modules and nothing seems to work, I just keep getting this message. Here's full detail about the issue https://github.com/bower/decompress-zip/issues/43

Every time I try to unzip the atom shell app with node / programmatically I get this error.

![screen shot 2015-01-15 at 12 35 34 pm](https://cloud.githubusercontent.com/assets/296798/5762812/1ad4a60c-9cb3-11e4-9296-0e39bf145337.png)

I opened up mac `Console` and can see it logs the following when I try to run:

```
1/21/15 4:02:11.440 PM com.apple.xpc.launchd[1]: (com.github.atom-shell.255064[19701]) Could not find and/or execute program specified by service: 13: Permission denied: /Users/thomas/Desktop/wallpaper/wallpaper-app/build/Atom.app/Contents/MacOS/Atom
1/21/15 4:02:11.440 PM com.apple.xpc.launchd[1]: (com.github.atom-shell.255064[19701]) Service setup event to handle failure and will not launch until it fires.
1/21/15 4:02:11.440 PM Finder[339]: spawn_via_launchd() failed, errno=111 label=com.github.atom-shell.255064 path=/Users/thomas/Desktop/wallpaper/wallpaper-app/build/Atom.app/Contents/MacOS/Atom flags=1 : LaunchApplicationClient.cp #1136 LaunchApplicationViaLaunchDJobLabel() q=com.apple.root.default-qos
1/21/15 4:02:11.440 PM Finder[339]: spawn_via_launchd() failed, errno=111 label=com.github.atom-shell.255064 path=/Users/thomas/Desktop/wallpaper/wallpaper-app/build/Atom.app/Contents/MacOS/Atom flags=1
```

I'm pretty certain it's some kind of codesign issue yet again. Any idea why I can't unzip with node but can unzip with other terminal commands and archive utility just fine?

**Comment by zcbenz** [comment]
The zip archive contains some symbol links which most zip libraries can not handle, usually we just use the `zip` command to unzip, you can find an example at grunt-download-atom-shell:
https://github.com/atom/grunt-download-atom-shell/blob/master/tasks/download-atom-shell-task.coffee#L46
