### ISSUE TITLE
atom-shell app crashes in a save dialog

### ISSUE THREAD

**Issue by abe33** [atom/atom-shell#1045]
I'm working on an app built upon atom-shell 0.20.5 and, on the computer of a colleague, the app crash whenever he open the save dialog. 
It appears the crash is linked to Dropbox but I also have the dropbox app installed and I doesn't reproduce this. Our mount point for Dropbox is different, mine is in my home and his is in its Documents folder.

Here's the log of the crash: 
https://gist.github.com/abe33/5eb47ce6fcab93e0fed2

Here's the code that opens the save dialog: 

```coffee
  saveImage: (image) ->
    new Promise (resolve, reject) ->
      options =
        filters: [{ name: 'Images', extensions: [image.type] }]
        title: 'labels.save_image'.t()
        defaultPath: "#{process.env.HOME}/Downloads/#{parameterize image.name}.#{image.type}"

      dialog.showSaveDialog options, (chosenPath) ->
        if chosenPath?
          download = app.models.Download.new {image, path: chosenPath}
          resolve(download)
          download.start()
        else
          reject(new Error 'cancelled')
```

**Comment by zcbenz** [comment]
According to [a thread](https://forums.adobe.com/message/6938265#6938265) that has the same crash:

> That particular crash is a MacOS bug that affects multiple applications.
It usually crashes in the open and save dialogs.
>  
> Apple is aware of this OS bug, and working on a solution.

I think you can try upgrading to 10.10.1 if you haven't.

**Comment by zcbenz** [comment]
I'm closing this since I don't think we can do anything on this.
