### ISSUE TITLE
Log to mac Console app

### ISSUE THREAD

**Issue by reggi** [atom/atom-shell#1047]
Is it possible for me to log to the Console app? `console.log` doesn't work! Similar to #339 about debugging.

**Comment by zcbenz** [comment]
Checkout https://github.com/atom/node-nslog.

**Comment by reggi** [comment]
@zcbenz Thanks, do you know the log func, there's no doc?

**Comment by zcbenz** [comment]
It is a npm module `nslog`, you can find some usages in Atom editor.

**Comment by bwin** [comment]
see https://github.com/atom/node-nslog/blob/master/src/nslog.coffee

**Comment by reggi** [comment]
@bwin I used a converter and got to the same conclusion :)
Thanks!

**Comment by reggi** [comment]
@zcbenz Phantom.js has [this `onConsoleMessage`](http://phantomjs.org/api/webpage/handler/on-console-message.html) wonder what your thoughts are for getting something like that into Atom shell?

**Comment by reggi** [comment]
jsdom also has something like this https://github.com/tmpvar/jsdom#capturing-console-output
