### ISSUE TITLE
Screenshot can be out of sync with current layout

### ISSUE THREAD

**Issue by FWeinb** [atom/atom-shell#1049]
The screenshot returned by `capturePage` isn't in sync with the layout of the page. 

Currently atom uses `host->CopyFromBackingStore` to get the screenshot [here](https://github.com/atom/atom-shell/blob/master/atom/browser/native_window.cc#L341-L347). After some search I found this [issue](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/o2aUtFAIlyQ). 

It would be great if the screenshot could be synced with layout.

**Comment by zcbenz** [comment]
This requires hacking into Chromium's drawing code, and I don't even know if it is solvable, so I'm closing this since no one would work on it. We will still accept it if someone sends a pull request.

**Comment by Mr0grog** [comment]
FWIW, it seems like wrapping a call to `capturePage()` in `window.webContents.beginFrameSubscription()` guarantees that the backing store is up-to-date:

```js
window.webContents.beginFrameSubscription(function(buffer) {
  window.webContents.endFrameSubscription();
  window.capturePage.apply(win, args);
});
```

Obviously that's a pretty hacky workaround and actually having `capturePage` wait would be better, but for anybody experiencing this problem (I was pretty stymied by it for a few hours trying to use Nightmare.js to capture screenshots), it does seem to work.
