### ISSUE TITLE
IPC send() command doesn't work in webviews without nodeintegration

### ISSUE THREAD

**Issue by gstack** [atom/atom-shell#1053]
Added an IPC message handler in preload script, sending a message over IPC crashes without nodeintegration. Works when it's added but this is not desirable (since it's an external web contents)

**Comment by gstack** [comment]
Seems like IPC's state depends on the process variable existing

**Comment by paulcbetts** [comment]
We are successfully sending IPC messages from the `preload` script of WebView contexts as of 0.20.3, this might be a recent regression

**Comment by paulcbetts** [comment]
This *is* a recent regression, we can no longer send IPC messages, so we're completely blocked on upgrading :(

**Comment by zcbenz** [comment]
Hmm, when node integration is off, the global `process` object will be removed, and the `ipc` module relies on the global `process` object for message dispatching, which resulted in a crash.

**Comment by paulcbetts** [comment]
@zcbenz Sounds like `ipc` should capture `process` in a local when it's required in?

**Comment by zcbenz** [comment]
@paulcbetts The JavaScript code did it right, it was the C++ code that did it wrong when forwarding the messages.
