### ISSUE TITLE
Screen: allow to require module before App.ready()

### ISSUE THREAD

**Issue by bpasero** [atom/atom-shell#1061]
I think atom shell should really allow to require the screen module even if the App is not ready. Any method call within can check for App being ready, but module loading should be totally possible even before.

**Comment by mofucka** [comment]
Screen only runs in the browser process tho.. Linux requires it to be run in the renderer otherwise screen produces a crash AFAIK.

**Comment by zcbenz** [comment]
The `screen` module needs to subscribe to native screen events when it is initialized, which requires the app to be ready.

Of course we can return a proxy object and then routing the actual events to it when app is ready, but it adds lots of complexity to the simple module and I don't think it deserves the method.
