### ISSUE TITLE
Menu: assigning Ctrl+Plus ends up being Ctrl+Shift+Plus

### ISSUE THREAD

**Issue by bpasero** [atom/atom-shell#1062]
Is it not possible to have Ctrl - + as keybinding?

**Comment by zcbenz** [comment]
There is no single `+` key in keyboard events, it is always shifted `=`.

**Comment by bpasero** [comment]
Ok, so how would I be able to assign Ctrl++ to some action? In Chrome I can Ctrl++ to zoom in.

**Comment by zcbenz** [comment]
Are you using a keyboard that can input `+` without pressing `Shift`? Which platform are you using?

**Comment by bpasero** [comment]
Yeah, its a german keyboard layout :)

**Comment by zcbenz** [comment]
Can you try if `Ctrl+=` works for you?

**Comment by bpasero** [comment]
This does not enable Ctrl++ for me. Instead, I have to type Ctrl+Shift+0 on my keyboard.

**Comment by bpasero** [comment]
(its not so important, I just thought this was maybe a leftover from your work to support "+" and some trivial bug - if not, dont spend too much time on it)

**Comment by bpasero** [comment]
Hm I take it back, CmdOrCtrl+= seems to do it.
