### ISSUE TITLE
Run distribution failed silently

### ISSUE THREAD

**Issue by nantas** [atom/atom-shell#1063]
> atom-shell v0.20.7, Mac 10.10.1

I have an application built with polymer and node.js modules.

I can run my application with command-line `atom-shell bin/` correctly.

But as soon as I put the contents of my `bin` folder to `Atom.app/Content/Resources/app` then double click to launch the app. It will quit in a glimpse without showing anything. I checked console of Mac but it didn't show anything suspicious.

There are some native modules in my app like `lwip` and `pathwatcher`. I'm not sure if they are causing trouble. I test the distribution method with other simple app like `default_app` and basic webpage all work fine.

How can I catch the error when launching distribution of atom-shell?

**Comment by zcbenz** [comment]
Can you execute your program via command line?

```bash
$ ./Atom.app/Contents/MacOS/Atom
```

**Comment by nantas** [comment]
ok, so the command line outputs the error. Sorry I forgot about that.
