### ISSUE TITLE
Add Xcursor theme support

### ISSUE THREAD

**Issue by muchweb** [atom/atom-shell#1064]
Adding [Xcursor](http://www.x.org/releases/current/doc/man/man3/Xcursor.3.xhtml) theme support.

As a user, I want to be able to change the look (theme) of my pointer (e. g. by using [LXAppearance](http://wiki.lxde.org/en/LXAppearance)).

**Comment by zcbenz** [comment]
I suggest [reporting it to Chromium](https://code.google.com/p/chromium/issues/list) since the underlying graphic is drawn by Chromium and there is nothing we can do in atom-shell.

**Comment by muchweb** [comment]
@zcbenz, thank you for your suggestion. Unfortunately, their bug tracker requires using [unethical :eyes: 'googly account'](https://www.eff.org/tags/google). Please feel free to report this issue yourself if you would like to.
