### ISSUE TITLE
GTK theme support

### ISSUE THREAD

**Issue by muchweb** [atom/atom-shell#1065]
All default menus, scroll bars and other elements should use user's preferred GTK theme (not the light-gray custom 'chromium' look).

Possibly related to https://github.com/atom/atom/issues/5224.

**Comment by zcbenz** [comment]
The menus are already drawn according to current GTK+ theme.

For scrollbars and other elements I suggest [reporting it to Chromium](https://code.google.com/p/chromium/issues/list) since the underlying graphic is drawn by Chromium and there is nothing we can do in atom-shell.

**Comment by muchweb** [comment]
https://github.com/atom/atom-shell/issues/1064 is related.
