### ISSUE TITLE
Windows: "Paul Betts" folder appears in Start Menu

### ISSUE THREAD

**Issue by rly** [atom/atom-shell#1066]
I'm on Windows 7. I updated Atom from 0.175.0 to 0.176.0 yesterday. Today, I noticed a new folder in my Start Menu called "Paul Betts". The folder is empty. The creation time is just 13 seconds after the creation of the folder atom/app-0.176.0/resources and before the creation time of the rest of the files in atom/app-0.176.0.

This seems like a bug. In case it's relevant, I do remember closing Atom during the update process.

**Comment by bwin** [comment]
Nice try, Paul.

Kevin Sawicki <notifications@github.com> schrieb am Mi., 28. Jan. 2015
20:08:

**Comment by paulcbetts** [comment]
This seems like an Atom proper bug, can someone file it there?

**Comment by rly** [comment]
My bad. I filed this over there: https://github.com/atom/atom/issues/5296
