### ISSUE TITLE
Can not load files in asar archives in custom protocols

### ISSUE THREAD

**Issue by nantas** [atom/atom-shell#1069]
In our app, we reference all of assets with url with different protocols.
I'm currently working on build the distribution app and want to use asar to make a package of the whole app.

We load the start page like this:
```javascript
BrowserWindow.loadUrl('asar:' + __dirname + '/static/dashboard.html');
```
That part alone works, but as soon as I added a protocol.registerProtocol for 'asar' protocol the above page could not be load:
```javascript
    Protocol.registerProtocol('asar', function(request) {
        //do some work with request url
        return new Protocol.RequestFileJob(url);
    });
```

In the console it says: 
```plain
Failed to load resource: asar:/path/to/MyApp.app/Contents/Resources/app.asar/static/dashboard.html
```

The same code would work fine with normal `app` folder even though I use 'asar' protocols for all my asset reference urls.

I suspect that `Protocol.RequestFileJob(url)` does not work for inside asar package, but not sure how to dig deeper.

**Comment by nantas** [comment]
If I only use 'asar:' protocol for the starting page, and keep all other url reference with my custom protocol. I got the following error when load resources:
```plain
Imported resource from origin 'myprotocol://' has been blocked from loading by Cross-Origin Resource Sharing policy: Received an invalid response. Origin 'asar://' is therefore not allowed access.
```

**Comment by zcbenz** [comment]
Yeah `Protocol.RequestFileJob` can not read asar archives, as work around you can use `fs` module to read the file and the use `protocol.RequestStringJob` to return the content.

> If I only use 'asar:' protocol for the starting page, and keep all other url reference with my custom protocol. I got the following error when load resources:

Have you turned on CSP in your `html` file?

**Comment by nantas** [comment]
I added 
```html
<meta http-equiv="Content-Security-Policy" content="default-src fire: 'unsafe-inline'" >
```
In my starting html page.

But still got the same error:
```plain
Imported resource from origin 'myprotocol://' has been blocked from loading by Cross-Origin Resource Sharing policy: 
Received an invalid response. Origin 'asar://' is therefore not allowed access.
```

**Comment by nantas** [comment]
I find no way to solve the cross-protocol reference issue stated above, so I can only go on with changing all resource protocols to "asar" in my html files.

Now I'm trying to use `protocol.RequestStringJob` inside registerProtocol to handle resources in asar package like this:
```javascript
    Protocol.registerProtocol('asar', function(request) {
        //work out file path
        var fileContent = fs.readFileSync(filePath);
        return new Protocol.RequestStringJob({
            mimeType: Mime.lookup(file),
            data: fileContent
        });
    });
```

It works for html and css files, I can load them from asar correctly. But any image files are not displaying. It doesn't report any "Failed to load resource" error so my guess is that the request is proceeded but somehow the content cannot be displayed. Is it because the default setting `charset: 'UTF-8'` gets in the way of displaying images? @zcbenz

**Comment by zcbenz** [comment]
It is because `RequestStringJob` is not capable of processing binary data, #566 did propose a way to fix this but it is not implemented yet.

I'll fix the custom protocol not loading under `asar://`, it is affecting Atom too.

**Comment by nantas** [comment]
I tested atom-shell v0.21.1, without `asar:` protocol, it didn't complain about cross-origin policy anymore.
But my custom protocol still cannot load resource from asar package due to `protocol.RequestFileJob` does not work for files inside asar, and lack of `RequestBufferJob` implemented.

I guess the example in [Application Packaging Documentation](https://github.com/atom/atom-shell/blob/master/docs/tutorial/application-packaging.md):
```js
app.on('will-finish-launching', function() {
    var protocol = require('protocol');
    protocol.registerProtocol('atom', function(request) {
      var url = request.url.substr(7)
      return new protocol.RequestFileJob(path.normalize(__dirname + '/' + url));
    });
});
```
Will not work for asar package, can you confirm that?

**Comment by zcbenz** [comment]
Yeah I can confirm it, we still need a way to load asar resources in custom protocols.
