### ISSUE TITLE
Can't programmatically start/stop the timeline

### ISSUE THREAD

**Issue by nathansobo** [atom/atom-shell#1072]
I've tried the deprecated `console.timeline` and `console.timelineEnd()` as well as `console.time()` and `console.timeEnd()`.

**Comment by zcbenz** [comment]
Have you passed a name when calling?

![screen shot 2015-01-29 at 5 15 08 pm](https://cloud.githubusercontent.com/assets/639601/5969579/75ddca4c-a7da-11e4-8264-c70ec311a367.png)

**Comment by nathansobo** [comment]
I tried it but maybe I'll try again. Get back to you tomorrow.

**Comment by nathansobo** [comment]
@zcbenz It prints the time but doesn't start the actual timeline.

**Comment by zcbenz** [comment]
@nathansobo What do you mean by "start the actual timeline"? In Chrome `console.time` seems to only print the time too.

**Comment by nathansobo** [comment]
![screenshot_2015-02-06_14_49_33](https://cloud.githubusercontent.com/assets/1789/6088027/80b1e940-ae0f-11e4-84b6-2bfd6d22ab7c.png)

It used to be that calling `console.timeline()` was equivalent to clicking the "record" button in the timeline interface.

**Comment by zcbenz** [comment]
I think it might be a Chrome bug, `console.time` in Chrome browser doesn't do that too.

**Comment by nathansobo** [comment]
![chroooome](https://cloud.githubusercontent.com/assets/1789/6089754/302ded1e-ae25-11e4-805d-90be86fd7dce.jpeg)

**Comment by deepak1556** [comment]
should this be a bug ? looks like there are some solid reasons for not getting back that api https://code.google.com/p/chromium/issues/detail?id=412782 ;)

**Comment by nathansobo** [comment]
Could we add some other API for doing it... it doesn't need to be synchronous. My use case is that I want to start recording using a key binding rather than clicking record with my mouse. When doing performance work that saves a lot of time.

**Comment by zcbenz** [comment]
@nathansobo Chromium has removed lots of code related to `console.timeline`, it is nearly impossible to bring them back, so I'm closing this :( . I think the only solution is to execute JavaScript in the devtools to click the "record" button.

**Comment by nathansobo** [comment]
@zcbenz Any pointers to an API for running JS in the dev tools?

**Comment by zcbenz** [comment]
@nathansobo 

```javascript
require('remote').getCurrentWindow().devToolsWebContents.executeJavaScript('console.log("test");');
```

There is a bug (#1186) that you have to execute the code __after__ devtools is opened, otherwise `devToolsWebContents` would be `undefined`.

**Comment by nathansobo** [comment]
Thanks!
