### ISSUE TITLE
Console Crash

### ISSUE THREAD

**Issue by marcus433** [atom/atom-shell#1073]
When pushing 1000 items to localStorage atom-shell crashes

**Comment by zcbenz** [comment]
I tried to push items with following code but it works fine:

```js
for (var i = 0; i < 10000; ++i)
  localStorage[i] = i;
```

Which platform are you using?

**Comment by marcus433** [comment]
It appears it was actually due to an overload of console.log messages. atom-shell will crash if you do for (var i = 0; i < 10000; ++i)
  console.log(i);

**Comment by zcbenz** [comment]
I can not reproduce on Windows and OS X, which platform and what is version of atom-shell are you using?

**Comment by marcus433** [comment]
Sorry for the later reply. I ran into the error on Mac OS X Yosemite and the latest release version of atom-shell.

**Comment by zcbenz** [comment]
Can you paste the crash report here? You should be able to find it in `Console.app`.

**Comment by zcbenz** [comment]
I'm closing this unless there is more information.

**Comment by aperc** [comment]
In case this is still relevant, it crashes for me as well. The following code makes it crash. Funny enough, for me it crashes as soon as I do 1790 or more loops.

https://gist.github.com/aperc/a8649a406e54115abbf9

electron version is 0.28.3
OS X Yosemite 10.10.3

**Comment by aperc** [comment]
Additional info, only happens if run through the electron drag & drop GUI. Running the app through the console works fine.
