### ISSUE TITLE
Error building atom-shell from source

### ISSUE THREAD

**Issue by dcposch** [atom/atom-shell#1074]
Steps to reproduce:
* Fresh clone of atom-shell. When I did it, the commit was 2ed7d58ac443
* Follow the Linux build instructions here: https://github.com/atom/atom-shell/blob/master/docs/development/build-instructions-linux.md 
  (I'm using 64-bit Ubuntu 13.10)
* `./script/bootstrap.py` works, however
* `./script/build.py -c Debug` throws errors

Here's the compile output up to the first error. There were a bunch more similar errors.

    $ ./script/build.py -c Debug
    ninja: Entering directory `out/Debug'
    [8/994] CXX obj/vendor/breakpad/src/client/linux/handler/breakpad_client.minidump_descriptor.o
    FAILED: /usr/bin/clang++ -MMD -MF obj/vendor/breakpad/src/client/linux/handler/breakpad_client.minidump_descriptor.o.d -DCOMPONENT_BUILD -DGURL_DLL -DSKIA_DLL -DNDEBUG -DUSING_V8_SHARED -DWEBKIT_DLL -DSK_SUPPORT_LEGACY_GETTOPDEVICE -DSK_SUPPORT_LEGACY_BITMAP_CONFIG -DSK_SUPPORT_LEGACY_DEVICE_VIRTUAL_ISOPAQUE -DSK_SUPPORT_LEGACY_N32_NAME -DSK_SUPPORT_LEGACY_SETCONFIG -DSK_IGNORE_ETC1_SUPPORT -DSK_IGNORE_GPU_DITHER -DTOOLKIT_VIEWS -DUSE_AURA -DVIEWS_IMPLEMENTATION -DWEBVIEW_IMPLEMENTATION -DUSE_X11 -I../../vendor/breakpad/src -I../../vendor/breakpad/src/client -I../../vendor/breakpad/src/third_party/linux/include -I../../vendor -I../../vendor/breakpad -g -Wno-empty-body -std=c++11 -std=gnu++11 -fno-rtti -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/harfbuzz  -c ../../vendor/breakpad/src/client/linux/handler/minidump_descriptor.cc -o obj/vendor/breakpad/src/client/linux/handler/breakpad_client.minidump_descriptor.o
    In file included from ../../vendor/breakpad/src/client/linux/handler/minidump_descriptor.cc:32:
    In file included from ../../vendor/breakpad/src/client/linux/handler/minidump_descriptor.h:36:
    In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/string:39:
    In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/char_traits.h:38:
    In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/stl_algobase.h:64:
    In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/stl_pair.h:59:
    In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/move.h:57:
    /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/type_traits:268:39: error: use of undeclared identifier '__float128'
        struct __is_floating_point_helper<__float128>
                                          ^
    1 error generated.

**Comment by dcposch** [comment]
I think it's this issue: http://stackoverflow.com/questions/13525774/clang-and-float128-bug-error

I "fixed" it by changing one line in `out/Debug/build.ninja`

Before:

     command = $cxx -MMD -MF $out.d $defines $includes $cflags $cflags_cc $cflags_pch_cc -c $in -o $out

After:

   command = $cxx -MMD -MF $out.d $defines $includes -D__STRICT_ANSI__ $cflags $cflags_cc $cflags_pch_cc -c $in -o $out

After that it compiles without complaints.

**Comment by zcbenz** [comment]
@dcposch Thanks for the solution, can you move your fix from `brightray` to [common.gypi#L128](https://github.com/atom/atom-shell/blob/master/common.gypi#L128) and see if it works? This error seems to only happen in `breakpad`, in this way we can limit the fix in `breakpad` instead of the whole project.

**Comment by dcposch** [comment]
I tried it out, but it didn't work. The errors are happening outside of breakpad too. Example below:

    [6/237] CXX brightray/browser/brightray.inspectable_web_contents_delegate.o
    FAILED: /usr/bin/clang++ -MMD -MF brightray/browser/brightray.inspectable_web_contents_delegate.o.d -DCOMPONENT_BUILD -DGURL_DLL -DSKIA_DLL -DNDEBUG -DUSING_V8_SHARED -DWEBKIT_DLL -DSK_SUPPORT_LEGACY_GETTOPDEVICE -DSK_SUPPORT_LEGACY_BITMAP_CONFIG -DSK_SUPPORT_LEGACY_DEVICE_VIRTUAL_ISOPAQUE -DSK_SUPPORT_LEGACY_N32_NAME -DSK_SUPPORT_LEGACY_SETCONFIG -DSK_IGNORE_ETC1_SUPPORT -DSK_IGNORE_GPU_DITHER -DTOOLKIT_VIEWS -DUSE_AURA -DVIEWS_IMPLEMENTATION -DWEBVIEW_IMPLEMENTATION -DUSE_X11 -I../../../brightray -I../../../brightray/vendor/download/libchromiumcontent/src -I../../../brightray/vendor/download/libchromiumcontent/src/skia/config -I../../../brightray/vendor/download/libchromiumcontent/src/third_party/skia/include/core -I../../../brightray/vendor/download/libchromiumcontent/src/third_party/WebKit -I../../../brightray/vendor/download/libchromiumcontent/Release/gen -g -std=c++11 -std=gnu++11 -fno-rtti -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/harfbuzz -std=gnu++11 -fno-rtti -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/harfbuzz -Wno-deprecated-register -fno-rtti  -c ../../../brightray/browser/inspectable_web_contents_delegate.cc -o brightray/browser/brightray.inspectable_web_contents_delegate.o
    clang: warning: unknown warning option '-Wno-deprecated-register'; did you mean '-Wno-deprecated'?
    warning: unknown warning option '-Wno-deprecated-register'; did you mean '-Wno-deprecated'? [-Wunknown-warning-option]
    In file included from ../../../brightray/browser/inspectable_web_contents_delegate.cc:1:
    In file included from ../../../brightray/browser/inspectable_web_contents_delegate.h:4:
    In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/string:39:
    In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/char_traits.h:38:
    In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/stl_algobase.h:64:
    In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/stl_pair.h:59:
    In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/move.h:57:
    /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/type_traits:268:39: error: use of undeclared identifier '__float128'
        struct __is_floating_point_helper<__float128>
                                      ^

**Comment by dcposch** [comment]
Here's what I've tried so far. It gets past a bunch of other compile errors it ran into before.

https://github.com/atom/atom-shell/commit/8628646487530a21cb9b831805d2f36b7a07f52c

**Comment by dcposch** [comment]
OK, now it builds! 

Same changes in `atom-shell`. I additionally had to update `vendor/brightray`: https://github.com/brightray/brightray/pull/92

**Comment by zcbenz** [comment]
@dcposch I didn't realize it also happens outside breakpad, if so your original PR should be enough to fix this, sorry for the trouble, I'll merge brightray/brightray#91.

**Comment by zcbenz** [comment]
Fixed with https://github.com/brightray/brightray/pull/91.
