### ISSUE TITLE
WebRTC and getUserMedia crashes

### ISSUE THREAD

**Issue by nicola** [atom/atom-shell#1076]
1) I made a simple app that getUsermedia and put the stream into a video tag

```
<!DOCTYPE html>
<html>
  <head>
    <title>Hello World!</title>
  </head>
  <body>
    <video autoplay></video>
    <script type="text/javascript">
    navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia;
    var constraints = {audio: false, video: true};
    var video = document.querySelector('video');
    function successCallback(stream) {
      window.stream = stream; // stream available to console
      if (window.URL) {
        video.src = window.URL.createObjectURL(stream);
      } else {
        video.src = stream;
      }
    }
    function errorCallback(error){
      console.log('navigator.getUserMedia error: ', error);
    }
    navigator.getUserMedia(constraints, successCallback, errorCallback);
    </script>
  </body>
</html>
```

after a couple of minutes the app crashes by itself.

2) When setting up a WebRTC connection, from the initiator client, I receive

```
[71931:0131/233736:INFO:socket_host_udp.cc(334)] sendto() has failed twice returning a  transient error. Dropping the packet.
...
```

What is the state of atom-shell and webRTC?

**Comment by zcbenz** [comment]
Can you run the same code on Chrome 40 and see if it yields the same results? And what's the OS are you using?

**Comment by nicola** [comment]
Sorry, I am using OS X 10.10, Chrome 40 hasn't crashed yet. I can copy the logs as soon as it crashes again (the app)

**Comment by zcbenz** [comment]
You should be able to find the crash log in `Console.app`, can you paste it here?

**Comment by nicola** [comment]
That would not be enough

```
[1]    72020 abort       .
```

This is all the log: http://pastebin.com/sVMTEKTw

**Comment by zcbenz** [comment]
From the log the crash is not related to WebRTC or getUserMedia, it is your `BrowserWindow` object get garbage collected, which is actually a JavaScript error. You need to check your `main.js`.

> What is the state of atom-shell and webRTC?

It is the same with current stable release of Chrome.

**Comment by nicola** [comment]
What about part 2? Thanks on the hint on part 1

**Comment by zcbenz** [comment]
> What about part 2? Thanks on the hint on part 1

It is just a normal log, you should be able to find the same log in Chrome.

**Comment by nicola** [comment]
Actually no, in Chrome the WebRTC connection takes place (conversely from atom-shell)
