### ISSUE TITLE
Drag & Drop (Enhancement)

### ISSUE THREAD

**Issue by marcus433** [atom/atom-shell#1085]
Would it ever be considered to implement the Cocoa drag-drop API into atom-shell? This way file such as .zip could be dragged to desktop or even dragged while still downloading etc.

https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/DragandDrop/Tasks/DraggingFiles.html

**Comment by mark-hahn** [comment]
Can't you just put the drop functionality in chromium as you would in the
chrome browser?  There is standard html for that.  Someone correct me if
I'm wrong.

**Comment by marcus433** [comment]
You could, the issue is if you haven't yet downloaded the file. For example in an email app you drag an attachment out and it starts downloading on drag out. With the standard functionality you can't drag a file that hasn't finished downloading however in native cocoa you can and it will show a progress bar.

**Comment by zcbenz** [comment]
To implement this we have to patch Chromium and blink to provide an interface for this, which is actually quite complicated, I don't think we will ever do it.

I'm closing this as won't fix.
