### ISSUE TITLE
[OSX] How to pragmatically hide the app

### ISSUE THREAD

**Issue by vishnevskiy** [atom/atom-shell#1086]
similar to CMD+H? 

.hide() on BrowserWindow seems to be not the same behavior?

Specifically what I am trying todo is when the close button is pressed. Is it possible to just hide the BrowserWindow and clicking the dock will show it again?

**Comment by zcbenz** [comment]
You can use `Menu.sendActionToFirstResponder('hide:');` to achieve it, see also:
https://github.com/atom/atom-shell/blob/master/docs/api/menu.md#class-method-menusendactiontofirstresponderaction
