### ISSUE TITLE
webview don't embed override.coffee when reload page.

### ISSUE THREAD

**Issue by cyvirus** [atom/atom-shell#1087]
When reloading or navigating some links, override.js and other preload script file don't embedded again to webview page and causing some problem.
- If webpage try open new window will cause to crash webview (I guess due to window.open don't reimplemented) .
- I also can't use node features on webview.

I tested with atom-shell v0.21.1-linux-x64

**Comment by zcbenz** [comment]
Can you verify if you are using v0.21.1 with `process.versions['atom-shell']`? It sounds like you are using v0.20.0 and I can not reproduce this on Linux.

**Comment by cyvirus** [comment]
Sorry, I tested again with v0.21.1, it worked. Thanks!
