### ISSUE TITLE
Open browser-window from webpage with screen bounds

### ISSUE THREAD

**Issue by iamdriz** [atom/atom-shell#1088]
I want to open a second window from within my main window and display it on another screen (if one is available).

I have tried:

~~~
<script type="text/javascript">

	var remote = require('remote');
	
	var app = remote.require('app');
	
	var BrowserWindow = remote.require('browser-window');

	var screen = remote.require('screen');

	var displays = screen.getAllDisplays();

	var windowProjector;
	
	function showProjector() {
		
		if(windowProjector)
		{
			return false;
		}
		
		if(displays.length > 1)
		{
			windowProjector = new BrowserWindow({  
				"x": displays[1].bounds.x,
				"y": displays[1].bounds.y,
				"width": displays[1].workAreaSize.width,
				"height": displays[1].workAreaSize.height,
				"frame": false,
				"fullscreen": true,
				"web-preferences":{  
					"web-security":false
				},
			   "show": true
			});
			
			windowProjector.loadUrl('file://' + __dirname + '/windowProjector.html');
		}
		else
		{
			alert('You need two screens to run this game!');
			return false;
		}
		
	}

</script>

<button onclick="showProjector()">Start Game</button>
~~~

But I get the error that displays is undefined!

**How do you get the screen information when inside a webpage?** It seems that screen is different when inside a webpage to what it is when used on the server-side code.

**Comment by iamdriz** [comment]
I've even tried to use IPC to send the displays down from the main.js to the webpage:

var displays = screen.getAllDisplays();

`windowMain.webContents.send('screen', displays);`

**Comment by zcbenz** [comment]
`window.screen` is a reserved variable by DOM, use other variable names than `screen` can fix your problem.

**Comment by paulcbetts** [comment]
@zcbenz I'm gonna submit a pull to the docs, because I got trolled by this too. screen silently eats your misguided attempts to modify it, it's super non-obvious what happened
