### ISSUE TITLE
IPC for windows that don't exist yet

### ISSUE THREAD

**Issue by iamdriz** [atom/atom-shell#1090]
In my application I create a new BrowserWindow from within another window, so the variable that stores the instance of the window is on the client side and not the server side. The main.js also does not know about the window on app ready.

The new window is called `windowProjector` and in my main.js I handle communications like:

~~~
ipc.on('talk', function(event, arg) {
	windowProjector.webContents.send('talk', arg);
});
~~~

However this errors, because it doesn't know what windowProjector is as stated earlier.

How can I solve this? I thought about using IPC to send the newly created window up to the server main.js and then calling a function to START listening but this doesn't work either.

e.g.

On client side:
~~~
windowProjector = new BrowserWindow({
.. rest of code
});

ipc.send('projector', windowProjector);
~~~

On server side:
~~~
ipc.on('projector', function(event, arg) {
	windowProjector = arg;
	startListening();
});

function startListening() {
	// Handle chatter for the windowProjector sent up from windowMain
	ipc.on('talk', function(event, arg) {
		windowProjector.webContents.send('talk', arg);
	});
}
~~~

So how can I fix this issue? **I don't want to have to create the window at the server-side.**

**Comment by zcbenz** [comment]
You have to forward the message received from server side to the client side, and then forward it to the `windowProjector`.

You can not pass a window created on client side to server side.

**Comment by iamdriz** [comment]
Why have you closed this?

**Comment by iamdriz** [comment]
But windowProjector doesn't exist when the server code runs with the ipc forwarders listening. Hence the question.

**Comment by zcbenz** [comment]
The code in server side should forward the message to the window that created `windowProjector`, not to the `windowProjector` directly.

**Comment by bwin** [comment]
Because he has answered it.
> You have to forward the message received from server side to the client side, and then forward it to the windowProjector.

In your main.js you got a reference to your main-window. So send from main to mainWindow via ipc.
In your mainWindow you either got a reference to your windowProjector (then resend from here to there via ipc) or you don't (so queue the msg or discard it).

**Comment by bwin** [comment]
Ah, you beat me to it...

**Comment by iamdriz** [comment]
A reply doesn't necessarily mean the issue is resolved :p

I'll give that a try thanks.

**Comment by iamdriz** [comment]
In short are you saying that because the main window created the projector window I can send ipc messages straight to it from the main window without having to send them to the server first?

**Comment by zcbenz** [comment]
> In short are you saying that because the main window created the projector window I can send ipc messages straight to it from the main window without having to send them to the server first?

Yeah you can call `windowProjector.webContents.send('talk', arg);` in your main window.
