### ISSUE TITLE
Error when quitting app

### ISSUE THREAD

**Issue by iamdriz** [atom/atom-shell#1091]
When I click an exit button in my app I want to close all windows and quit the app.

I have the following code in my server side code:

~~~
windowMain.on('closed', function() {
	windowMain = null;
});

app.on('window-all-closed', function() {
	app.quit();
});
~~~

And on my client side code (I create the windowProjector client side):

~~~
windowProjector.on('closed', function() {
	windowProjector = null;
});

$(document).on('click', '.exit', function(e){
	e.preventDefault();
	remote.getCurrentWindow().close();
	if(windowProjector)
		windowProjector.close();
});
~~~

But I get the error:

![image](https://cloud.githubusercontent.com/assets/801252/6023647/cf5e92ea-abbd-11e4-9f06-a2fb0e3b290d.png)

I also get this error, if I just try and call app.quit instead of closing the windows.

What's the problem?

**Comment by zcbenz** [comment]
As stated in [the document](https://github.com/atom/atom-shell/blob/master/docs/api/remote.md#passing-callbacks-to-browser), you should avoid passing a callback to a remote object unless you know what you are doing.

In your case, you should make sure listeners install in `windowProjector` should be uninstalled before you close current window.

**Comment by iamdriz** [comment]
I'm not following. Exactly what's wrong with the code? I'm not passing any callbacks. I'm just closing the window and then when all windows are closed quit the app.

**Comment by zcbenz** [comment]
This is passing a callback:

```js
windowProjector.on('closed', function() {
    windowProjector = null;
});
```

**Comment by iamdriz** [comment]
Okies. So how do i close all the windows and quit the app then? Without doing that?

As the only other way I can think of doing this is to use ipc to tell the server code to call a quit function.

**Comment by zcbenz** [comment]
You can call `windowProjector.removeAllListeners` before you close current window.
