### ISSUE TITLE
Cannot load library chromiumcontent.dll on app load

### ISSUE THREAD

**Issue by iamdriz** [atom/atom-shell#1094]
Because the Windows version of atom-shell requires a bunch of dlls outside the main .exe file I have used the Enigma Virtual Box to combine all the files into one .exe file.

Based on this Wiki for node-webkit: https://github.com/nwjs/nw.js/wiki/How-to-package-and-distribute-your-apps#an-alternative-way-to-make-an-executable-file-in-windows

The app **works fine**... except every now and again I see this error, when I open the application:

![image](https://cloud.githubusercontent.com/assets/801252/6041799/aeac9046-ac77-11e4-967e-65ad5235b30c.png)

The app still works fine even if you see this error. But why am I seeing it? And how can I stop it.

**Comment by iamdriz** [comment]
Compressing the files under 'File Options' looks to fix this.

**Comment by bendulum** [comment]
I am getting "Cannot load library node.dll" when using the Enigma VB GUI. When using the Enigma CLI I'm getting a bunch of "Cannot find function ordinal 345..." errors.
I tried the enigmavirtualbox module from npm and the generate-evb module aswell.
Using the same strategy I was able to package a node-webkit app, but with electron I just can't get it to work.

**Comment by etiktin** [comment]
It is possible to pack Electron using EVB. The issue mentioned by @bendulum, is caused by double packing Electron's exe (details [here](https://github.com/etiktin/node-generate-evb/issues/1)).

**Comment by bendulum** [comment]
Yes, thank you for clearing this up. I was kind of lost :)
