### ISSUE TITLE
Pass objects from browser to renderer-side at window creation, as argument of "new BrowserWindow()" or ".loadUrl()", to avoid pollution of the global scope

### ISSUE THREAD

**Issue by cronvel** [atom/atom-shell#1095]
The *remote* module is really handy, however I don't like to pollute the global scope of the browser-side just to provide some objects to the renderer's remote module, using `remote.getGlobal(name)`.

It would be nice if we can pass some objects from browser-side to renderer-side, either at the `BrowserWindow` creation or when using `.loadUrl()`.

Implementation example, **browser-side**:
```js
var somethingIWantToShare = {
  myFunction: function() {
    // some code
  } ,
  ...
  // some properties and methods here
} ;

mainWindow.loadUrl( 'file://' + __dirname + '/html/main.html' , {
  rendererSideName: somethingIWantToShare ,
  anotherRendererSideName: ... // another object to share
} ) ;
```
**Renderer-side**:
```js
remote.rendererSideName.myFunction() ;
remote.anotherRendererSideName.myOtherFunction() ;
```

**Comment by zcbenz** [comment]
You can do it in this way:

browser side:
```js
mainWindow.rendererSideName = somethingIWantToShare;
```

renderer side:
```js
remote.getCurrentWindow().rendererSideName.myFunction();
```

**Comment by jprichardson** [comment]
@cronvel I wrote https://github.com/jprichardson/electron-window for this purpose. It uses the same method as `atom`. It also keeps track of global window refs so that you don't have to worry about it.

**Comment by cronvel** [comment]
@jprichardson Thanks a lot, I will look into it!

**Comment by Programming4life** [comment]
@zcbenz I tried that in v0.36.4 and it doesent work. I basically need to pass an object between two windows.

**Comment by meghadev** [comment]
This approach didn't work for me. Any possible reason?

**Comment by denu5** [comment]
@meghadev I think some things changed have since 2015 but I can tell you a solution that works for me in Electron 1.6

In the main process:

e.g. index.ts 
```
// typed to 'any', because we add a custom property later
 let window: any = new BrowserWindow({ 
        height: 500, 
        width: 700,
        frame: false,
        resizable: false
    });
.....

 window.custom = {
        'whatever': 'youwant'
    };
```
Then on the renderer side it's accessible like this:

e.g. index.html
```
<script>
var electron = require('electron');
var currentWindow = electron.remote.getCurrentWindow();
 
console.log(currentWindow.custom);
```

I'm not happy that it breaks the typing of the BrowserWindow and having said that, I'm pretty sure that this isn't best practice.

To use it in JS just remove :any

**Comment by IndieRobert** [comment]
can we get a 'opened' event to send data please.

**Comment by JeevanJain** [comment]
+1

**Comment by dingchaoyan1983** [comment]
+1 how to pass object reference to <webview> ?

**Comment by subbiah95** [comment]
@zcbenz , I saw your method it did work, but is there a way where i can pass from render process to main process, I tried the reverse as its, but it did not work

**Comment by HafizMuhammad-Farooq786** [comment]
> @meghadev I think some things changed have since 2015 but I can tell you a solution that works for me in Electron 1.6
> 
> In the main process:
> 
> e.g. index.ts
> 
> ```
> // typed to 'any', because we add a custom property later
>  let myWindow: any = new BrowserWindow({ 
>         height: 500, 
>         width: 700,
>         frame: false,
>         resizable: false
>     });
> .....
> 
>  myWindow.custom = {
>         'whatever': 'youwant'
>     };
> ```
> Then on the renderer side it's accessible like this:
> 
> e.g. index.html
> 
> ```
> <script>
> var electron = require('electron');
> var currentWindow = electron.remote.getCurrentWindow();
>  
> console.log(currentWindow.custom);
> ```
> I'm not happy that it breaks the typing of the BrowserWindow and having said that, I'm pretty sure that this isn't best practice.
> 
> To use it in JS just remove :any

Sir, I used your code. but I face an issue.

**Comment by trusktr** [comment]
Here's how to pass references from main to any process (window or webview, doesn't matter):

In Main:

```js
global.foo = { n: 123 }
```

Then in any Electron browsing context:

```js
import { remote } from 'electron'

console.log( remote.getGlobal( 'global' ).foo ) // { n: 123 }
```

You can implement an API this way to pass reference from window to window, through main.

NOTE! This ties up the renderer threads, which means executing a function from main inside a browsing context will lock/sync the main thread to the execution of the browser thread (it's been a while since I've researched, so I'm not sure if things have changed in that regard).

**Comment by trusktr** [comment]
After much tinkering, I've discovered that doing stuff like `remote.getGlobal('global').foo = 123` will not work as expected, because the call to `getGlobal('global')` returns some sort of proxy-like object, and multiple calls to `getGlobal('global')` can return differing proxy objects, so on subsequent calls the result of `remote.getGlobal('global').foo` will be `undefined`. This is always true, for example, when you set a value in one window, then try to read the value in a new `<webview>`.

To get around this problem, store values in lexical scope of the main process. For example, see https://discuss.atom.io/t/how-to-set-global-variable-of-main-process/24833/12?u=trusktr

**Comment by MarshallOfSound** [comment]
@trusktr That's not required, the issue here is that `foo` was undefined to begin with.

If you instead had

```js
// Main Process
global.foo = 1;
```

The setters / getters in each renderer would work.  Defining an undefined properties is not proxied through the `remote` module.  Redefining a defined property is proxied and works as expected

**Comment by trusktr** [comment]
@MarshallOfSound Not sure what you mean, as in my example above `foo` is defined.

But what I found is the following happens (when done in that sequence for example)

```js
// main process:
// open a BrowserWindow
```

```js
// in the BrowserWindow,
remote.getGlobal('global').someObj = {...}
```

```js
// later, in the same BrowserWindow, in a require'd file:
console.log(remote.getGlobal('global').someObj) // undefined (???)
```

```js
// at any time, in a <webview>:
console.log(remote.getGlobal('global').someObj) // always undefined (???)
```

The value does not stick around.

Now, if I apply a `getter/setter` trick in the main process,

```js
let _someObj

Object.defineProperty(global, 'someObj', {
  get() { return _someObj },
  set(value) { _someObj = value }
})
```

then the value sticks around for all of the above cases that were previously returning `undefined`:

```js
// later, in the same BrowserWindow, in a require'd file:
console.log(remote.getGlobal('global').someObj) // {...}
```

```js
// at any time, in a <webview>:
console.log(remote.getGlobal('global').someObj) // {...}
```

**Comment by trusktr** [comment]
@MarshallOfSound Perhaps a reciprocal `remote.setGlobal('someObj', {...})` method would help, which would abstract away all the gotchas.

**Comment by MarshallOfSound** [comment]
@trusktr The real thing here is IMO people shouldn't be using `remote`.  If you don't fundamentally understand how the backing IPC works it's full of raceconditions and footguns.  Plus its performance impact is noticeable as it is backed by synchronous IPC.

You're better off using custom async IPC

**Comment by trusktr** [comment]
> You're better off using custom async IPC

Do you mean, just (de)serializing stuff over ipcRenderer/webContents.send/etc?

From a DX perspective, its so easy to pass objects (instances of classes) around, with their prototypes and functions, instead of having to make IPC wiring. It'd be great if these parts had more polish.

**Comment by MarshallOfSound** [comment]
@trusktr That's the thing, `remote` doesn't magically send objects and classes and prototypes.  It serializes the entire thing (including a custom representation of the prototype) and sends it over syncronous IPC.  It's all faked, it's easy / helpful sure, but it's a huge race condition / performance hog if you use it for anything important in your application.  `remote` isn't a magical proxy of objects, it's just got really complicated serialization / deserialization that supports prototype chains.  It causes issue every major release and there are constant timing / racing issues.

As I said before, you're better off not using it, yes you sacrifice simplicity, but you gain back control, performance and predictability

**Comment by trusktr** [comment]
> It serializes the entire thing (including a custom representation of the prototype) and sends it over syncronous IPC.

Ooof, that sounds like a pain.

What about for example what native `window.open` does, where we can read/write actual references on a child window? Could it be possible to add a `getNativeWindow` method to `WebContents` that can let us do this? This could make things easy. Maybe the processes (parent and child windows f.e.) would need to be sync'd together when doing this (with relevant options, f.e. to turn off OOPIF for `<webview>`s), but in many cases this may not be a performance concern.

**Comment by CircleOnCircles** [comment]
```
// main process or renderer process 1
data = {"age": 12, "healthy": true}

let win = new BrowserWindow({
        webPreferences: {
          nodeIntegration: true
        }
      });

win.loadFile("public/print.html", {query: {"data": JSON.stringify(data)}});
```
```
// renderer process 2
const querystring = require('querystring');
let query = querystring.parse(global.location.search);
let data = JSON.parse(query['?data'])
```

ref. https://stackoverflow.com/a/59347064/3969942
