### ISSUE TITLE
GlobalShortcut Problem on Mac OS X

### ISSUE THREAD

**Issue by Trixt0r** [atom/atom-shell#1099]
I am registering a short cut as follows:

```
var globalShortcut = require('global-shortcut');
globalShortcut.register('Command+V', function(){
  myWindow.webContents.paste();
});
```
this results in the behaviour that my Atom-Shell app blocks this key combination in any other running application. I can not e.g. paste code in my Atom Editor while my Atom-Shell app is running.

Am I doing something wrong?
Is there any chance to fix this problem?

-- Trixt0r

**Comment by paulcbetts** [comment]
GlobalShortcuts are, as their name implies, "global". Are you trying to register a shortcut in just your application? If so, the way to do that is via creating a Menu Item for it using the Menu API

**Comment by zcbenz** [comment]
As @paulcbetts said this is an expected behavior, so I'm closing this.

**Comment by Trixt0r** [comment]
So, is it the accelerator property which I have to add in the menu items?

**Comment by zcbenz** [comment]
Yeah, you can find the documents at:
https://github.com/atom/atom-shell/blob/master/docs/api/menu.md#menu
