### ISSUE TITLE
Disable zygote on Linux

### ISSUE THREAD

**Issue by zcbenz** [atom/atom-shell#1101]
On Linux Chromium uses a zygote process to fork child processes, and it caused a bug that the environment variables in browser process are not inherited in renderer processes.

This is mostly for security purposes, but since we are not using Chromium's sandbox, we should find a way to disable zygote.

**Comment by deepak1556** [comment]
from here https://code.google.com/p/chromium/codesearch#chromium/src/content/browser/renderer_host/render_process_host_impl.cc&cl=GROK&l=364 looks like using just `--renderer-cmd-prefix` would disable zygote as this document states too https://code.google.com/p/chromium/wiki/LinuxZygote , or probably we can override it ?

**Comment by zcbenz** [comment]
`--renderer-cmd-prefix` will prepend the argument to renderer process's command line, it is mainly for debug purpose so I'm not sure if it can work in atom-shell.

But this is not high priority anyway, we already had a work around in Atom editor.

**Comment by sebastien-mignot** [comment]
@zcbenz Hi. Could you tell me what the workaround in Atom editor is please ? I have the same pb : some atom pluggins keep throwing an error (Broken Pipe inside zygote, caused by "running without the SUID sandbox in chromium"
