### ISSUE TITLE
WebView on Windows works not like on OS X.

### ISSUE THREAD

**Issue by Trixt0r** [atom/atom-shell#1102]
If I add a WebView in my app and define a preload script, every url change within the WebView invokes the preload script on OS X.
But on Windows (8.1) the preload script is only executed once and not on every url change.

From my point of view, the behavior on OS X is correct. Is this a bug or can the OS X behavior be also achieved on Windows? A quick and dirty solution would be to reload the hosting page every time the url changes, I guess.

I really need a solution for this problem, since I am setting up an API in the preload script for the page in the WebView. And this API has to be always present for the WebView page.

-- Trixt0r

**Comment by bwin** [comment]
What version of Atom-Shell are you using?

Heinrich Reich <notifications@github.com> schrieb am Fr., 6. Feb. 2015
11:54:

**Comment by bwin** [comment]
AFAIK there has recently been some activity about this. If you're not already on latest, try with 0.21x.

**Comment by Trixt0r** [comment]
Tested it with 0.21.1 and 0.21.2.

**Comment by bwin** [comment]
Ok, that's bad news. Best to wait for zcbenz to comment on this.

**Comment by zcbenz** [comment]
@Trixt0r I can not reproduce this on Windows 8.1, can you verify if you are using atom-shell v0.21.x by checking `process.versions['atom-shell']`? If you are then can you share a minimal app that can reproduce this problem?

**Comment by Trixt0r** [comment]
@zcbenz Thank you for the fast response, and sorry for my late one.
Downloaded the binaries again and it looks like the preload script is loading properly since 0.21.1.
