### ISSUE TITLE
Atom shell renders blank window, despite full DOM in developer tools.

### ISSUE THREAD

**Issue by lexholden** [atom/atom-shell#1103]
I'm not entirely sure if this is purely a bug in my application logic or a problem with atom-shell, but I thought I'd see if anyone is having the same issue.

My gut feels like it's an issue with concurrent logic executing at different speeds, since occasionally it works and renders fine, but more and more often I will still be able to interact with my app via developer tools, my context menus still trigger, I can see all of the divs etc in DOM (even complex angular directives fire, and I'm getting app data through IPC) but nothing below the top level -html- tag is visible. It's quite a large app loading lots of different json files on the browser side.

Tearing my hair out, it's hard to develop when I can only open my app 1 time in 20...

Any ideas?

**Comment by bwin** [comment]
Is your app on github?

**Comment by lexholden** [comment]
https://github.com/lexholden/cicero

Still early alpha development, some of the codebase is a tad prototyped/sloppy/hardcoded, but just made the repo public.

All the core frontend app logic is under /js/cicero.js atm. Thanks :)

**Comment by bwin** [comment]
I'll take a look at it in the evening (in about 6 hours)...

**Comment by zcbenz** [comment]
Can you make your app work with atom-shell v0.21.x? I tried to test your app but some native modules do not compile with latest atom-shell.

**Comment by lexholden** [comment]
@zcbenz Thanks for trying. Yep I'm using the latest version. Did you install bower and npm requirements first?

There may be some issues to do with hardcoding of some file paths for loaded content, just recloning myself now to run clean and see if that is an issue.

**Comment by lexholden** [comment]
Turns out I had some synchronous IPC calls that were choking it up, my bad. Thanks anyway.
