### ISSUE TITLE
[OSX] Transparent window draws icon in title bar area 

### ISSUE THREAD

**Issue by brumm** [atom/atom-shell#1104]
I was playing around with transparent windows, applying a padding to the body to push content inwards and leave a transparent area for css-emulated shadows, when I noticed that the window icon is still being drawn, just underneath the window content.

![screen shot 2015-02-06 at 15](https://cloud.githubusercontent.com/assets/170500/6081168/c9e433ea-ae17-11e4-9e82-f2493905cf8d.png)

Also, I noticed that contrary to the documentation, the transparent window is still resizable.

**Comment by zcbenz** [comment]
There must be a call of `BrowserWindow.setRepresentedFilename` in your code, removing that call would remove the icon.

> Also, I noticed that contrary to the documentation, the transparent window is still resizable.

Resizable transparent window doesn't work on all platforms.
