### ISSUE TITLE
did-fail-load does not fire on web contents

### ISSUE THREAD

**Issue by kevinsawicki** [atom/atom-shell#1105]
This prints out 'finished' but not 'failed'

```js
app.on('ready', function() {
  mainWindow = new BrowserWindow({width: 1024, height: 768, center: true});
  mainWindow.loadUrl('file:///this/file/does/not/exist.txt');
  mainWindow.webContents.on('did-fail-load', function() {
    console.log('failed');
  });
  mainWindow.webContents.on('did-finish-load', function() {
    console.log('finished');
  });
});
```

**Comment by maxkueng** [comment]
I've just encountered the same problem. I want to add some behavior to when the content fails to load but the event never fires. Also happens with `http://.. `URLs.

Can confirm in v0.20.4 and v0.21.2, so far.

**Comment by gabssnake** [comment]
Same use case as @maxkueng, I am seeing this behaviour on `electron-prebuilt 0.36.7` when requesting http://0.0.0.0/. No event gets fired and the BrowserWindow shows a "not found" page. Was this still present in this version or is it particular to the requested URL ?
