### ISSUE TITLE
ipc module data being passed in the calls

### ISSUE THREAD

**Issue by Sinewyk** [atom/atom-shell#1109]
I've just been playing around with atom-shell, trying to see the differences with node-webkit, and how I would make it work for a React app.

I'm also trying Immutable.js, and ... I just tried sending a Immutable.Map through the

```
window.webContents.send('map', Immutable.Map.set('data', 1));
```

and I correctly receive the object in the web page, but without any function attached to the object. Is that normal ? What can I expect from data passed from/to/through the ipc module, should I only work with primitive types like Object, Array, string and Numbers ? Nothing funky like passing functions through the module and stuff like that ?

I've been looking through the doc, and sorry if I missed something obvious like that. I'm not sure how the data being passed through the web page/browser context is handled :frowning:

**Comment by paulcbetts** [comment]
You can only generally send things via IPC that are JSON serializable

**Comment by Sinewyk** [comment]
So I can just forget classes, expecting their methods to be on it.

Roger that.

I'll just have my immutable store on the web page sides and treat the ipc as the ajax layer that I have to parse, or something along that.

Thanks =).

**Comment by paulcbetts** [comment]
@Sinewyk If you're trying to talk from renderer => browser, you can use the `remote` module, which does get you more of what you're looking for. In general, you want to put most of your code in the renderer process, it's much easier to debug.
