### ISSUE TITLE
Update io.js version

### ISSUE THREAD

**Issue by dlmanning** [atom/atom-shell#1113]
I realize io.js is a fast moving target, but a few things have become more stable since the 1.0.0-pre version currently included. In particular, the nan module has been updated a couple of times to improve the compatibility of native modules with io.js.

For example, building leveldown for leveldb fails against 1.0.0-pre, but works fine on 1.1.0.

**Comment by bwin** [comment]
Compiling native modules can be a b*tch on 0.21.x, so :+1:

David Manning <notifications@github.com> schrieb am Mo., 9. Feb. 2015 08:41:

**Comment by dlmanning** [comment]
Since posting this I've come to understand that the io.js / node version is tied to the version of v8 used in the packaged version of chrome. io.js 1.1.0 uses v8 4.1.0.14, which roughly matches v8 4.1.0.14 in Chrome 41, which is still in beta. Seeing as how the author is undoubtedly aware of all this and it's part of the normal release cycle, I'm closing my issue.
