### ISSUE TITLE
Videos not playing

### ISSUE THREAD

**Issue by iamdriz** [atom/atom-shell#1114]
In my app I have a video but it doesn't show the video as playing, but the ended even gets fired after 6 seconds (the video is 6 seconds). So the video is actually playing, it's just not showing it, all I see is the first frame of the video.

I've tested this with MP4.

**Comment by zcbenz** [comment]
Does your video play in Chrome browser? And can YouTube's videos play in atom-shell on your machine?

**Comment by iamdriz** [comment]
Yes the video plays fine in Chrome. Regarding YouTube, could you give me an example of how I would add a YouTube video to my app to test it? As usually you embed it as an iframe right?

**Comment by zcbenz** [comment]
You can just call `loadUrl` with `http://www.youtube.com` to open YouTube.

**Comment by iamdriz** [comment]
YouTube videos work fine. I should note that I add the video dynamically with:

~~~
var html = '\
			<div class="animation">\
				<div class="animation-outer">\
					<div class="animation-inner">\
						<video id="video" src="file://' + __dirname + '/videos/chest-gold.mp4"></video>\
					</div>\
				</div>\
				<div class="animation-top"></div>\
			</div>';
			
var appendedVideo = $(html).appendTo('.game');

var video = document.getElementById('video');
	video.playbackRate = 1;

$(appendedVideo).fadeIn('slow', function(){
	video.play();			
});
~~~

**Comment by zcbenz** [comment]
What's the version of your Chrome browser?

**Comment by iamdriz** [comment]
`40.0.2214.111` but I'm pretty sure I have been able to do this for some time...

**Comment by zcbenz** [comment]
It seems to be a bug of atom-shell, I don't know the reason though.

**Comment by iamdriz** [comment]
@zcbenz Ah bummer, is it because atom uses a different version of chromium? Or literally an issue inside atom that causes it to not play the video?

**Comment by zcbenz** [comment]
atom-shell uses 40.0.2214.94 which is slightly older, but it usually does not make any difference. I think it might be an issue inside atom-shell.

**Comment by mzgoddard** [comment]
@iamdriz Unless atom-shell is including an mpeg decoder, I don't believe it supports MP4. Clearly its doing some of the work maybe with the container format but I don't think it'll be able to decode the content in the file. Chromium doesn't include an mpeg decoder. Chrome does. http://www.chromium.org/audio-video

You should be able to show a video with one of the video formats Chromium does support like WebM.

**Comment by frankhale** [comment]
html5test.com is a cool site to see what features the browser uses. I just opened it in Atom-Shell 0.21.2 and here is a screenshot of the video features:

![html5test-atom-shell-0 21 2](https://cloud.githubusercontent.com/assets/190154/6155650/ed4f22ec-b202-11e4-8ed7-d024a53a253f.PNG)

**Comment by iamdriz** [comment]
Is it possible to get MP4 support into atom shell? It'd be really awesome if we could.

**Comment by frankhale** [comment]
This is similar to the following on Node-Webkit and since Atom-Shell and Node-Webkit are very similar it may work here as well (I have not tried it though).

https://github.com/nwjs/nw.js/wiki/Using-MP3-%26-MP4-%28H.264%29-using-the--video--%26--audio--tags.

**Comment by hachre** [comment]
I just wanna say that I'm using atom shell 0.20.3 still for my project and both on Windows and OS X it plays h264 encoded mp4s just fine.

**Comment by iamdriz** [comment]
Yes it's does. But not if the video tag is added to the DOM after...

**Comment by hachre** [comment]
After what? I add all my video tags via JS.

**Comment by hachre** [comment]
After what? I add all my video tags via JS.

```javascript
var video = document.createElement("video");
video.src = URL;
video.preload = "auto";
video.controls = true;
video.autoplay = false;
document.body.appendChild(video)
```

Works for me with the 0.20.3 version at least.

**Comment by iamdriz** [comment]
A

**Comment by iamdriz** [comment]
Yeah I do the exact same, but adding the tag via Js causes the video to stay at frame 1 (it does play as I get the ended event) but having it already on the page works fine.

**Comment by iamdriz** [comment]
This seems to have started working now and I haven't changed anything in the code or the version of atom-shell I am using... so I can only assume that this was because the computer I was testing it had a bad day or something along those lines. Tested on same computer and all works fine...

**Comment by odragora** [comment]
I had to say I have the same issue with MP4 video and Electron v0.36.8.
The most confusing thing is that the video is displaying when I run Electron app from the shell, and the video is not displaying when I pack the application and run it as .exe file.

**Comment by baconface** [comment]
Just to add clarity to the HTML5 Test results @frankhale posted, MP4 comes in several forms. The one mentioned showing unsupported is [MP4 ASP (Advanced Simple Profile)](https://en.wikipedia.org/wiki/MPEG-4_Part_2). But [MP4 AVC (Advanced Video Coding)](https://en.wikipedia.org/wiki/H.264/MPEG-4_AVC) is supported via H.264. Side by side support can be found [here](http://html5test.com/compare/feature/video-mpeg4/video-h264.html). MP4 ASP is not supported in Chrome.

**Comment by weiweian90** [comment]
I had the same problem with Electron v4.2.12. The video element cannot play mp4, but can play camera media stream
