### ISSUE TITLE
webview::getUrl wrong after loading file://

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom-shell#1116]
If I load a `file://` url into a webview it shows properly but then later `webview::getUrl` returns "about:blank".  This is a problem because my code doesn't always know what the url is supposed to be.

I created a tiny Atom package to demonstrate this.  It is at https://github.com/mark-hahn/blank-webview.

- Install blank-webview
- edit `lib/blank-webview-view.coffee` and fix the url `file:///c:/Users/Administrator/.atom/packages/blank-webview/www/sample.html` for your setup
- execute `blank-webview:toggle`
- a small page with a cloud will show
- after 2 seconds the console will show `webview.getUrl about:blank`

**Comment by mark-hahn** [comment]
windows 8.1 
atom 0.177.0 
atom-shell 0.21.0.

**Comment by mark-hahn** [comment]
Another symptom of the problem.

- load local  `file://` URL.
- use link to remote website on web
- use `webview::goBack`

You will see `about:blank`.  Apparently  `file://` URLs are always interpreted as `about:blank`.

**Comment by mark-hahn** [comment]
Bump.  The web-browser is mainly used to test local files as they are developed so this bug is pretty serious to those users.

**Comment by deepak1556** [comment]
@zcbenz the webview proto methods are redirected to webviewimpl https://github.com/atom/atom-shell/blob/master/atom/renderer/lib/web-view/web-view.coffee#L277 , does that invoke web_contents methods or is it somwthing else ? Also `getURL` method provided seems to be deprecated, should it be changed ? https://code.google.com/p/chromium/codesearch#chromium/src/content/public/browser/web_contents.h&q=GetURL&sq=package:chromium&l=173&dr=CSs

**Comment by zcbenz** [comment]
@deepak1556 We should probably use `GetVisibleURL` instead of `GetURL` in C++, thanks for finding it out!

**Comment by mark-hahn** [comment]
+1 on the thanks.

**Comment by ibdknox** [comment]
Just ran into this today. Any idea when we might see a fix in a release? :)

**Comment by zcbenz** [comment]
@ibdknox There is a pull request (#1209) to fix this, I need to check Chromium's code to see whether it is the correct fix.

**Comment by leesocrates** [comment]
I also have a problem with history.goback().
first I loadurl from a local file , the pathname is : "/D:/sword/msCode/resources/app/build/index.html"
then i login , after login success , go to schedule page , the pathname is : "/schedule", 
schedule page has a list ,then i click a item , enter a detail page , the pathname is : "/schedule/detail".
on the detail page , when i click a back button. i invoke history.goback().  i think it should go back to schedule page , the pathname should be "/schedule", but the truth is ,  the real pathname is "/D:/schedule". i don't know how to fix this problem , does anyone know how to fix it ?
