### ISSUE TITLE
Paste and Match Style cmd+shift+v

### ISSUE THREAD

**Issue by emorikawa** [atom/atom-shell#1120]
Is there a way to re-implement "Paste and Match Style" like Chrome has? It's super useful for clearing out the formatting from content you're pasting from other sources.

**Comment by hachre** [comment]
Paste it into a offscreen textarea, then read its value and transfer that to the actual place you wanted to paste into. (Is an idea)

**Comment by emorikawa** [comment]
I can't expect all of my users to do that.
ᐧ

**Comment by hachre** [comment]
That was a suggestion of how to strip all formatting off a paste via programming.

**Comment by zcbenz** [comment]
You can read text via [clipboard.readText](https://github.com/atom/atom-shell/blob/master/docs/api/clipboard.md) API and then insert the text, it would erase the formatting.

**Comment by Sukram21** [comment]
If someone still stumbles onto this issue - https://github.com/electron/electron/pull/1701 and https://github.com/electron/electron/issues/5866 solve it
