### ISSUE TITLE
Support for Afloat for app transparency

### ISSUE THREAD

**Issue by tgriesser** [atom/atom-shell#1124]
Hey all - great work on Atom

So there's this mac app called [aloat](http://afloat.en.softonic.com/mac) which allows for (among other things) setting app transparency - which is actually a pretty big [feature request](https://discuss.atom.io/t/background-transparency/1005) over on the forums. Typically it adds a context menu in the window panel of apps that support it.

![screen shot 2015-02-11 at 12 27 54 pm](https://cloud.githubusercontent.com/assets/154748/6152223/71143b0e-b1e9-11e4-976c-3241f873f52a.png)

Afloat currently works with Chrome, and some other chromium/node based apps I've seen, so I thought maybe it'd be possible for it to work with Atom?

Admittedly I don't know what all this would entail, whether it'd be a simple modification or whether it's not even possible - but the app is actually open source: https://github.com/millenomi/afloat so I just thought I'd add it as a suggestion.

**Comment by zcbenz** [comment]
We already have support for transparent window in atom-shell now.
