### ISSUE TITLE
Build fails due to files created with wrong names in bootstrap process, when branding atom-shell in Windows

### ISSUE THREAD

**Issue by jilltowle** [atom/atom-shell#1126]
I'm trying to rebrand atom-shell and am finding that, on Windows, some of the files created during the bootstrap process which should be named for the project have the wrong names.  It appears that the gyp_defines isn't being parsed correctly for the project and product names.  Because of this, the build is failing when it gets to this part.  

I'm using the following commands:

	cd atom-shell
	set GYP_DEFINES="project_name=myapp product_name=MyApp"
	python script\bootstrap.py -v
	python script\build.py -c Release -t myapp

This is creating the following files in out\Release\obj:

	myapp product_name=MyApp.myapp product_name=MyApp.exe.generated.manifest
	myapp product_name=MyApp.ninja
	myapp product_name=MyApp_dump_symbols.ninja
	myapp product_name=MyApp_lib.ninja

Without branding, on Windows, these are:

	atom.atom.exe.generated.manifest
	atom.ninja
	atom_dump_symbols.ninja
	atom_lib.ninja

Just for reference, we've also tried the rebranding on OS X, and I think those files were created with the expected names (although some of the files themselves are different, I'm assuming that's due to the platform.).

	myapp.ninja
	myapp_dump_symbols.ninja
	myapp_framework.ninja
	myapp_helper.ninja
	myapp_lib.ninja

What do we need to do for this to run correctly on Windows?
Thank you for your help.

**Comment by zcbenz** [comment]
This is weird, I just did a upgrade of gyp on master branch, can you try if it fixes this? I currently don't have access to a Windows machine.

**Comment by jilltowle** [comment]
Thanks for the quick response.  I pulled down your latest and tried it again with the same results.

**Comment by Wortex17** [comment]
this is still in effect with v0.22.1

**Comment by Wortex17** [comment]
also,setting product name and project name in reverse order
```
 set GYP_DEFINES="product_name=MyAppProduct project_name=myappproject"
```
results in usual "atom" named artifacts.
This strengthens the theory that the arguments are not split by whitespace.
defining the string values with escaped " does not help anything either

**Comment by Wortex17** [comment]
I've got it!
At least on windows, setting the GYP_DEFINES with quotes wrapping all parameters results in this error.

Trying
```
 set GYP_DEFINES=product_name=MyAppProduct project_name=myappproject
```
instead results in the correct artifacts

Can anyone confrim that these quotes are *not* needed on other OS's too?
If yes, i would remove them completely from the docs, otherwise add a paragraph directed to windows users

**Comment by paulcbetts** [comment]
@Wortex17 fwiw, grunt-build-atom-shell doesn't attempt to use GYP_DEFINES, but instead edits the Gyp file directly, which works successfully

**Comment by Wortex17** [comment]
@paulcbetts I was tempted to mention that, but that does not really resolve the issue at hand.
in my opinion even grunt-build-atom-shell would actually benefit from using GYP_DEFINES, as this would render the need to rig the gyp files (which may even fail in future versions) unnecessary. Are there any other reasons why you decided for rigging instead of configuring?

**Comment by zcbenz** [comment]
@Wortex17 That doesn't work on Linux, I guess it is related to how Windows cmd sets environment variables. I've fixed the docs on Windows, thanks for finding it out!

**Comment by lygstate** [comment]
set "GYP_DEFINES=product_name=MyAppProduct project_name=myappproject"
Is the right way to do the set

**Comment by zcbenz** [comment]
@lygstate Awesome! I'll update the docs.
