### ISSUE TITLE
webview: plugin question

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom-shell#1127]
The browser-window doc (https://github.com/atom/atom-shell/blob/master/docs/api/browser-window.md#class-method-browserwindowadddevtoolsextensionpath) says "currently only NPAPI plugins are supported".  The Chrome Browser is dropping NPAPI totally this year.  Does this affect chromium and more specifically the webview tag?

Another question:  How do I install plugins for webview?

Thanks in advance ,.,,

**Comment by zcbenz** [comment]
> The Chrome Browser is dropping NPAPI totally this year. Does this affect chromium and more specifically the webview tag?

I believe it will affect us, but I think we can wait until they actually did it.

> How do I install plugins for webview?

You can install the plugins into system's default location of NPAPI plugins, on Mac I believe it is `~/Library/Internet Plugins/`. Currently there is no way to add locations to search for plugins for `<webview>`.
