### ISSUE TITLE
Facebook returns errors after loading through atom-shell.

### ISSUE THREAD

**Issue by 5paceManSpiff** [atom/atom-shell#1131]
I get this console output after calling `loadUrl('http://facebook.com')` on my `BrowserWindow` object.  My profile page isn't able to display after logging in due to these reference errors.  Oddly enough these errors don't seem to occur if facebook is loaded in a `<webview>` tag.

```
Uncaught ReferenceError: __d is not defined
module.js:351 Uncaught Error: Cannot find module 'ServerJSDefine'
(index):14 Uncaught ReferenceError: requireLazy is not defined
(index):16 Uncaught ReferenceError: requireLazy is not defined
(index):18 Uncaught ReferenceError: requireLazy is not defined
module.js:351 Uncaught Error: Cannot find module 'BigPipe'
(index):27 Uncaught TypeError: Cannot read property 'beforePageletArrive' of undefined
module.js:351 Uncaught Error: Cannot find module 'TimeSlice'
(index):28 Uncaught TypeError: Cannot read property 'beforePageletArrive' of undefined
module.js:351 Uncaught Error: Cannot find module 'TimeSlice'
```

**Comment by mark-hahn** [comment]
I don't see this on my webview.  Did you check loading the same URL on a
chrome browser?  Try clearing cookies on both webview and the browser and
compare them.

**Comment by 5paceManSpiff** [comment]
I'm not getting any of the errors in my chrome browser across two linux systems, but both have the errors in atom-shell.

**Comment by 5paceManSpiff** [comment]
Reloading the page using `WebContents.reloadIgnoringCache()` produces the same results.

**Comment by mark-hahn** [comment]
Did you try clearing the cookies?

**Comment by 5paceManSpiff** [comment]
Sorry if this isn't the right place, but how do I go about doing that?

**Comment by bwin** [comment]
Just from the looks of it I would say it's probably/maybe because of `require` being defined by atom-shell and facebook expecting requirejs or something like that.

**Comment by mark-hahn** [comment]
First of all I'm not a core developer, just a user, so I'm not an expert.
I'm just saying what I would do.

To open the development console for your webview execute `.openDevTools()`
on the webview element in your code.  The window will pop up exactly like
the one in the chrome browser.  In both cases navigate to the facebook page
and then select `resources` and you will see the cookies.

**Comment by mark-hahn** [comment]
I could be wrong but I doubt atom-shell would define a global variable
called `require` inside the web page.

**Comment by 5paceManSpiff** [comment]
It seems to be an issue with the node integration.  If I add the `nodeintegration` attribute to a webview pointing towards facebook it will no longer load.

**Comment by 5paceManSpiff** [comment]
I'm going to try to rename the `require` function from the `preload` variable when creating the `BrowserWindow`?

**Comment by bwin** [comment]
> I could be wrong but I doubt atom-shell would define a global variable called `require` inside the web page.
In BrowserWindow you got `require` defined by the node-integration.

Ok, you already verified the cause. But why use a BrowserWindow instead of Webview for extternal 3rd-party content?

**Comment by 5paceManSpiff** [comment]
I'm making a stand alone facebook desktop app called "cagebook" which will replace most of the facebook feed data with Nicolas Cage quotes and pictures.  It's a lot easier to replace the standard facebook feed dom elements if I can interactively use the developer console.  I'm not quite sure how to attach a developer console to the webview browser plugin, so I'm trying to inject the changes through my atom-shell wrapper [jsb](https://github.com/5paceManSpiff/jsb), rather than in the document through a script tag.

**Comment by bwin** [comment]
:+1: for the idea.
You could use BrowserWindow with `"node-integration": false` in that case. (Of course not if you're actually using the node-integration for ipc or whatever.)

**Comment by 5paceManSpiff** [comment]
I could probably set it up without node integration, but I think it would be cool to have quote and image caching.  Right now I'm trying to see if I can rename the `require` function in a preload script.

**Comment by paulcbetts** [comment]
It's wildly insecure to load any non-local content in a window with node-integration..

**Comment by 5paceManSpiff** [comment]
Oops, there is totally a function to open the dev console on webview tags.  Sorry about that.

**Comment by 5paceManSpiff** [comment]
I'm aware that it's really insecure, I was just trying to get access to the dev console.  I overlooked the `<webview>.openDevTools()` function.

**Comment by 5paceManSpiff** [comment]
I'm going to close this issue seeing that my individual needs have been met, but I opened up an issue discussing atom-shell's handling of namespace conflicts at issue #1133.

**Comment by mark-hahn** [comment]
>  which will replace most of the facebook feed data with Nicolas Cage
quotes and pictures.

ROTFL

**Comment by boyphongsakorn** [comment]
how you do to fix that
i have a same error on linux (zorin os)

**Comment by bierzorutas** [comment]
here also same issue after so long...
