### ISSUE TITLE
Attaching the developers console to a <webview>

### ISSUE THREAD

**Issue by 5paceManSpiff** [atom/atom-shell#1132]
I've created a work in progress node library for remote javascript injection servers under the name [jsb](https://github.com/5paceManSpiff), or java script browser.  It would be super helpful if I could attach a developers console to a webview tag to interactively inject content.  I was wondering if anyone knows how I could go about implementing this.

**Comment by paulcbetts** [comment]
https://github.com/atom/atom-shell/blob/master/docs/api/web-view-tag.md#webviewopendevtools

**Comment by 5paceManSpiff** [comment]
Thanks man, sorry about that.
