### ISSUE TITLE
Node integration breaks some websites

### ISSUE THREAD

**Issue by 5paceManSpiff** [atom/atom-shell#1133]
In this case, facebook.  Checkout #1131.

The page is able to load in a webview tag without node integration, but after it is turned on there are namespace conflicts.

**Comment by 5paceManSpiff** [comment]
Should atom-shell be responsible for these kinds of namespace conflicts?

**Comment by paulcbetts** [comment]
So basically the idea is, you want to use a preload script but disable node integration - the preload script gets access to node.js and can do whatever it wants (including saving off node modules to local variables), then when the actual page loads, it has node integration disabled

**Comment by 5paceManSpiff** [comment]
Oh sweet, that's a really great way of dealing with it!

**Comment by maxogden** [comment]
ran into this issue today, here's how to do approximately what @paulcbetts described:

preload.js:

```js
delete global.require
delete global.module
delete global.__filename
delete global.__dirname
delete global.process
```

(you can also re-assign them however you please)

relevant source is here: https://github.com/atom/atom-shell/blob/4834eed5204502038cd3003bf7b34b957f95e4dd/atom/renderer/lib/init.coffee#L55
