### ISSUE TITLE
Feature request: API to openDevTools in own window

### ISSUE THREAD

**Issue by frankhale** [atom/atom-shell#1135]
I'm writing an app that has a very small window so when I open dev tools I am not able to toggle it to open in it's own window. It'd be really awesome to be able to pass a parameter to openDevTools to instruct it to open in it's own window.

**Comment by 5paceManSpiff** [comment]
I know [you can do this through the dev tools window already](http://stackoverflow.com/questions/23668827/how-to-open-the-chrome-developer-tools-in-a-new-window), so there must be some sort of api which could hook into it.

**Comment by 5paceManSpiff** [comment]
This line of code should call the click method implemented in the dev tools html view.  It's pretty hacky though.

```javascript
mainWindow.devToolsWebContents.executeJavaScript('document.getElementsByClassName("long-click-glyph")[0].click()')
```

**Comment by frankhale** [comment]
Thanks, I'll give that a shot!

**Comment by frankhale** [comment]
Unfortunately after I open the dev tools and attempt to get it's web contents using 'devToolsWebContents' it returns undefined so I cannot execute that one liner. I'll keep playing around to see if I can figure out what is going on.

**Comment by frankhale** [comment]
I'm just going to close this as I don't think it's really all that necessary. If others find it useful I suppose it can be reopened at a later time.

**Comment by frankhale** [comment]
Reference similar issue: https://github.com/atom/atom-shell/issues/1300

**Comment by wesleywesley** [comment]
@frankhale it returns undefined because you need to use a timeout or something, the devToolsWebContents is not immediately available. However, I'm then stuck on the next step, clicking the javascript element. It appears that element no longer exists in newest electron/chrome version. Anyone know the correct name of it now so I can adjust ?

**Comment by frankhale** [comment]
the openDevTools() function has options to allow you to detach the devtools when opening.

https://github.com/electron/electron/blob/master/docs/api/web-contents.md#webcontentsopendevtoolsoptions

**Comment by cinderblock** [comment]
In case you're here with the latest ERB that uses a different method to open the devtools:

```js
// ...
if (isDebug) {
  require('electron-debug')({ devToolsMode: 'detach' });
}
// ...
```
