### ISSUE TITLE
Protocol relative URLs are problematic

### ISSUE THREAD

**Issue by frankhale** [atom/atom-shell#1139]
I'm trying to use the cosmo boostrap theme and it is specifying at least one resource without specifying the protocol. This doesn't work in Atom-Shell 0.21.2.

Example:

```
@import url("//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700");
```

Atom-Shell wants to assume the file protocol

```
GET file://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700 net::ERR_FILE_NOT_FOUND
```

**Comment by frankhale** [comment]
this is probably because I've used the file protocol to load my index.html file. How can we get around this? I've noticed this for a while but was always willing to hand edit and add the protocol but I'd rather not keep doing that especially when I use things like bower to manage my dependencies.

**Comment by bwin** [comment]
AFAIK `//blah` means use the protocol of the parent. So Atom-Shell is right in assuming the file-protocol.
Sorry, but I don't know how to make this work.

**Comment by frankhale** [comment]
Yeah, I guess I'm going to have to hand edit the problematic files that are using parent relative URLs. Not a huge deal but a little annoying.

**Comment by bwin** [comment]
You could try using a Grunt/Gulp/whatever task for replacing protocol-relative urls. Beats doing it by hand.

**Comment by frankhale** [comment]
@bwin, I think you are right. This is probably the proper way to solve this. Thank you. I'll look into this.

**Comment by frankhale** [comment]
Related issue https://github.com/atom/electron/issues/1747

**Comment by frankhale** [comment]
Similar issue https://github.com/atom/electron/issues/1895
