### ISSUE TITLE
about cookie

### ISSUE THREAD

**Issue by liangz678** [atom/atom-shell#1142]
Can atom-shell support cookie？

**Comment by paulcbetts** [comment]
@liangz678 Cookies only make sense in the context of HTTP / HTTPS URLs - since Atom Shell loads file: URLs by default, cookies don't exist. What are you trying to do in particular?

**Comment by mark-hahn** [comment]
The only place you'll see cookies is in a `webview` tag which is like a
browser.  If you want a real browser embedded check out my `web-browser`
package.

**Comment by liangz678** [comment]
@paulcbetts  I use the bottle set up a web server, locally with ajax submit twice data, server record the session for the first time, the second time visit the session. But in the second time missed in the actual situation.
I made a mistake, two is not the same as the ajax. Is the first time in the web side, the second is in the bower side.

**Comment by 5paceManSpiff** [comment]
Would it be possible to persist cookies through javascript on the nodejs side?

**Comment by paulcbetts** [comment]
This sample to get Google Analytics working might help you guys, it fakes out `document.cookie`:

https://gist.github.com/paulcbetts/2d2de55d137a1cf9d1ac

**Comment by 5paceManSpiff** [comment]
Why would you need to fake out document.cookie?

**Comment by zcbenz** [comment]
@liangz678 Can you give a minimal example of what you want?

**Comment by zcbenz** [comment]
I'm closing this unless there is more information.
