### ISSUE TITLE
Feature request: API to permanently delete files

### ISSUE THREAD

**Issue by icewind** [atom/atom-shell#1144]
Hello. Can you please add a functionality for deleting files and not just moving them to trash? It is necessary when you are working with remote files and files mounted through sshfs.

**Comment by bwin** [comment]
I don't quite get it, why can't you delete files?

**Comment by icewind** [comment]
Do you mean delete file using not API method but fs.unlink?

**Comment by bwin** [comment]
yes

**Comment by icewind** [comment]
You right. I should be using fs module. Sorry to bother

**Comment by bwin** [comment]
No prob, happy to help.
