### ISSUE TITLE
remove frame of existing window

### ISSUE THREAD

**Issue by brumm** [atom/atom-shell#1145]
something akin to `browserWindow.setFrame(false)`, if possible.

**Comment by sprintr** [comment]
[Frameless window](https://github.com/atom/atom-shell/blob/master/docs/api/frameless-window.md)

**Comment by brumm** [comment]
yes. this removes the frame on creation. I'm looking to remove the frame on-the-fly, of an _existing_ window.

**Comment by sprintr** [comment]
Oh! don't think we can remove frame in the renderer process right now.

**Comment by bwin** [comment]
Work-around: just destroy your window and create a new (frameless) window and set the url and position like in your old window. If you're not playing media in the window this should do.

What's your use-case?

**Comment by zcbenz** [comment]
Enabling removing window frame on the fly will add too much complexity to the code, and it is not easy to implement. I don't think it deserves the efforts, even though it is useful in some rare cases.

**Comment by arcman77** [comment]
If this is for fullscreen mode -
What if you were to set the browser height higher than the available screen in the monitor in such a way that the frame would be covered by the osx menu bar?

**Comment by YeesterPlus** [comment]
emulate titlebar then you can remove it on the fly
