### ISSUE TITLE
Load html string directly from native BrowserWindow api

### ISSUE THREAD

**Issue by 5paceManSpiff** [atom/atom-shell#1146]
I'm trying to use the browser as a rendering engine for my own transfer protocols, and it would be really useful to have some way to render html strings directly as opposed to serving a local server with `window.loadUrl()`, or injecting something which changes the `document.documentElement.innerHTML` property on load.

**Comment by zcbenz** [comment]
You can encode your HTML to [data url](https://developer.mozilla.org/en-US/docs/Web/HTTP/data_URIs) and then use `loadUrl` to load it.

**Comment by cydrobolt** [comment]
I'm attempting to use this method, but it leaves external JS and CSS unloaded. Any ideas?

**Comment by barbalex** [comment]
@5paceManSpiff: How is it possible to inject something which changes the `document.documentElement.innerHTML`?

Could `webContents.executeJavaScript` be used?

**Comment by cydrobolt** [comment]
@barbalex we could change it using `$("html").html(str);`, but I don't think this loads the new scripts either.

**Comment by luanped** [comment]
Are there any updates with this? I would also be interested in loading html directly using html-loader in webpack, rather than calling loadUrl.

Thanks

**Comment by Autre31415** [comment]
@cydrobolt @luanped 

I attempted this same process and found the same issue. Discovered it's due to script paths being relative to the BrowserWindow file and not from the source of the html string.

I solved this by changing my paths to be relative to the root.

Another method entirely would be using fs.readfileSync to drop a temporary file in the location you source your script paths and then sourcing that file for BrowserWindow.

**Comment by JoeChapman** [comment]
+1 for an update. Any changes?

**Comment by edgeadjei** [comment]
Can we reopen this issue?
The proposed solution leaves external files unloaded as addressed by @cydrobolt 
I'm especially interested in this functionality because this would replace a lot of boilerplate for large multi-window SPAs.

**Use Case**
```js
const loadView = ({title,scriptUrl}) => {
  return (`
    <!DOCTYPE html>
    <html>
      <head>
        <title>${title}</title>
        <meta charset="UTF-8">
      </head>
      <body>
        <div id="view"></div>
        <script src="${scriptUrl}"></script>
      </body>
    </html>
  `)
}

var file = 'data:text/html;charset=UTF-8,' + encodeURIComponent(loadView({
  title: "Account",
  scriptUrl: "./account.view.js"
}));
window.loadURL(file);
```

**Comment by chesucr** [comment]
The same here. I would like to load with `window.loadURL()` HTML content directly as a string. This html data was the result of a parsed file.

**Comment by sfraise** [comment]
I've been using something like this which seems to work ok:
content.load('./views/modal-content/' + data + '.html', function() {
});

Just have to be careful if trying to require js files in the html files you're requiring, they only get required the first time you load it so make sure if you do require js files in them that everything is bound to an event and not just run on something like the document ready.

**Comment by danielsokolowski** [comment]
I am investigating Electron vs NW.js and it seems HW (properly) treats HTML as first citizen and JS as secondary while Electron does the opposite; google search lead me to this thread. 

Anyone who looked into NW, why did you choose Electron for your project?

**Comment by chesucr** [comment]
There is a small comparison [here](https://github.com/electron/electron/blob/master/docs/development/atom-shell-vs-node-webkit.md). But I think this thread is not the place to ask that :O

**Comment by vincelwt** [comment]
Using the `baseURLForDataURL` option fixed it for me! It is documented [here](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winloadurlurl-options)

```
window.loadURL('data:text/html;charset=UTF-8,' + encodeURIComponent(pageContent), {
	baseURLForDataURL: `file://${__dirname}/app/`
})
```

**Comment by mushishi78** [comment]
Using data URL means that you can't use query strings in the url.

**Comment by fabiospampinato** [comment]
data-urls can't reliably be used for this because they have a length limit, no?

**Comment by paul-sanchez** [comment]
In this cases, I save the compiled string into a file and load from file:

```
fs.writeFileSync(fileName, compiledString, {encoding: 'utf8'})
win.webContents.once('dom-ready', () => {
  fs.unlikeSync(fileName) /* cleaning */
})
win.loadUrl(fileName)
win.show()
```

**Comment by caoyongfeng0214** [comment]
> Can we reopen this issue?
> The proposed solution leaves external files unloaded as addressed by @cydrobolt
> I'm especially interested in this functionality because this would replace a lot of boilerplate for large multi-window SPAs.
> 
> **Use Case**
> 
> ```js
> const loadView = ({title,scriptUrl}) => {
>   return (`
>     <!DOCTYPE html>
>     <html>
>       <head>
>         <title>${title}</title>
>         <meta charset="UTF-8">
>       </head>
>       <body>
>         <div id="view"></div>
>         <script src="${scriptUrl}"></script>
>       </body>
>     </html>
>   `)
> }
> 
> var file = 'data:text/html;charset=UTF-8,' + encodeURIComponent(loadView({
>   title: "Account",
>   scriptUrl: "./account.view.js"
> }));
> window.loadURL(file);
> ```

nice !
but, the <script> not work.

**Comment by m4heshd** [comment]
It's really hard to believe that this still isn't a feature. Such a useful thing to have but only workaround at the moment is to just write the data to a file and load it.

**Comment by linonetwo** [comment]
> data-urls can't reliably be used for this because they have a length limit, no?

> ERR_INVALID_URL (-300) loading 'data:text/html;charset=utf-8,%0A%3C!doctype%20html%3E%0A%3C!--%20The%20following%20comment%20is%20called%20a%20MOTW%20comment%20and%20is%20necessary%20for%20the%20TiddlyIE%20Internet%20Explorer%20extension%20--%3E%0A%3C!--%20saved%20from%20url%3D(0021)https%3A%2F%2Ftiddlywiki.com%20--%3E%0D%0A%3Chtml%20lang%3D%22zh-Hans%22%3E%0A%3Chead%3E%0A%3Cmeta%20http-equiv%3D%22Content-Type%22%20content%3D%22text%2Fhtml%3Bcharset%3Dutf-8%22%20%2F%3E%0A%3C!--~~%20Raw%20markup%20for%20the%20top%20of%20the%20head%20section%20~~--%3E%0A%0A%3Cmeta%20http-equiv%3D%22X-UA-Compatible%22%20content%3D%22IE%3DEdge%22%2F%3E%0A%3Cmeta%20name%3D%22application-name%22%20content%3D%22TiddlyWiki%22%20%2F%3E%0A%3Cmeta%20name%3D%22generator%22%20content%3D%22TiddlyWiki%22%20%2F%3E%0A%3Cmeta%20name%3D%22tiddlywiki-version%22%20content%3D%225.3.0-prerelease-2023-05-22%22%20%2F%3E%0A%3Cmeta%20name%3D%22viewport%22%20content%3D%22width%3Ddevice-width%2C%20initial-scale%3D1.0%22%20%2F%3E%0A%3Cmeta%20name%3D%22apple-mobile-web-app-capable%22%20content%3D%22yes%22%20%2F%3E%0A%3Cmeta%20name%3D%22apple-mobile-web-app-status-bar-style%22%20content%3D%22black-translucent%22%20%2F%3E%0A%3Cmeta%20name%3D%22mobile-web-app-capable%22%20content%3D%22yes%22%2F%3E%0A%3Cmeta%20name%3D%22format-detection%22%20content%3D%22telephone%3Dno%22%20%2F%3E%0A%3Cmeta%20name%3D%22copyright%22%20content%3D%22TiddlyWiki%20created%20by%20Jeremy%20Ruston%2C%20(jeremy%20%5Bat%5D%20jermolene%20%5Bdot%5D%20com)%0A%0ACopyright%20(c)%202004-2007%2C%20Jeremy%20Ruston%0ACopyright%20(c)%202007-2023%2C%20UnaMesa%20Association%0AAll%20rights%20reserved.%0A%0ARedistribution%20and%20use%20in%20source%20and%20binary%20forms%2C%20with%20or%20without%0Amodification%2C%20are%20permitted%20provided%20that%20the%20following%20conditions%20are%20met%3A%0A%0A*%20Redistributions%20of%20source%20code%20must%20retain%20the%20above%20copyright%20notice%2C%20this%0A%20%20list%20of%20conditions%20and%20the%20following%20disclaimer.%0A%0A*%20Redistributions%20in%20binary%20form%20must%20reproduce%20the%'

Is the error, the content is truncated.

**Comment by linonetwo** [comment]
This is possible now in 2023! https://github.com/electron/electron/issues/38813#issuecomment-1597528421

**Comment by thanhle7** [comment]
Any update?

**Comment by thanhle7** [comment]
I made it work by using the option: baseURLForDataURL; script files loaded and run just fine.

**Comment by linonetwo** [comment]
@thanhle7 Already working in opensource Notion-like note app https://github.com/tiddly-gittly/TidGi-Desktop

**Comment by Susheer** [comment]
let htmlString = '<html><h1>Hello</h1></html>';
let encodedHtmlString = encodeURIComponent(htmlString);
let mainWindow = new BrowserWindow();

mainWindow.loadURL(`data:text/html;charset=utf-8,${encodedHtmlString}`);
