### ISSUE TITLE
Windows: addRecentDocument does not seem to have any effect

### ISSUE THREAD

**Issue by bpasero** [atom/atom-shell#1149]
I dont get this API to work on Windows:
- download atom-shell-v0.21.2 for windows
- edit atom-shell-v0.21.2\resources\default_app\main.js

```javascript
app.on('ready', function() {
   app.addRecentDocument('C:\\myfolder');
});
```

Run atom.exe and pin it to taskbar. Right click and the entry does not show up.

**Comment by bwin** [comment]
I can't get it to work either.

Instead of modifying the default app you can also run `require("remote").require("app").addRecentDocument('c:\\path\\to\\file');` from the console.

**Comment by paulcbetts** [comment]
Do you have a shortcut in the Start Menu? As I recall, this is one of those weird APIs that requires a Start Menu shortcut

**Comment by bpasero** [comment]
No, but the app is pinned to the task bar which should be the same.

**Comment by zcbenz** [comment]
On Windows it requires your application to be registered to work, see:
https://github.com/atom/atom-shell/blob/master/docs/tutorial/desktop-environment-integration.md#windows-notes
