### ISSUE TITLE
Looking for help to understand issues installing native modules

### ISSUE THREAD

**Issue by aackerman** [atom/atom-shell#1152]
I'll try to be as detailed as I can, please bear with me.

Local `node` version `0.12.0` installed fresh from homebrew on OSX Yosemite.
Attempting to build `bignum` for `atom-shell` `0.21.2`

I've tried several different ways to install native modules and I'm past my understanding of C++ and `node-gyp`, unable to effectively understand the problems I'm experiencing or if the problems are related to the `bignum` library itself.

A normal install of `bignum` with `npm i bignum` will work fine.

```
export npm_config_disturl=https://atom.io/download/atom-shell
export npm_config_target=0.21.2
export npm_config_arch=ia32
HOME=~/.atom-shell-gyp npm install bignum
```
When I run the above statements, I run into several compilation errors related to `nan` and `v8`, such as the following. 

```
  CXX(target) Release/obj.target/bignum/bignum.o
In file included from ../bignum.cc:8:
../node_modules/nan/nan.h:67:21: error: no type named 'ExternalAsciiStringResource' in 'v8::String'; did you
      mean 'ExternalStringResource'?
typedef v8::String::ExternalAsciiStringResource
        ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
                    ExternalStringResource
```

I'm at a loss to understand the problems at hand. I do understand that `v8` changes have happened causing several `node` libraries to upgrade their versions of `nan` and `bignum` has [updated](https://github.com/justmoon/node-bignum/commit/81480fba462b3110b3193f1624354e6bdbf624a1) to, I assume to the latest version of `nan`, very recently. 

I also saw [this issue](https://github.com/rvagg/nan/issues/226#issuecomment-71140076) related to `nan` not working with `atom-shell` but the issue appears to be been resolved within the last week. And the issue appears to have been resolved before the `bignum` library updated its `nan` dependency.

After reading about that issues I also attempted to install with `apm`.

```
$ npm install -g atom-package-manager
$ cd ./node_modules/bignum
$ env ATOM_NODE_VERSION=0.21.2 apm install .
```
I ran the above statements and ran into the following errors.

```
dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /usr/local/lib/node_modules/atom-package-manager/node_modules/keytar/build/Release/keytar.node
  Expected in: dynamic lookup

dyld: Symbol not found: _node_module_register
  Referenced from: /usr/local/lib/node_modules/atom-package-manager/node_modules/keytar/build/Release/keytar.node
  Expected in: dynamic lookup

/usr/local/bin/apm: line 40: 53208 Trace/BPT trap: 5       "$binDir/$nodeBin" --harmony_collections "$binDir/../lib/cli.js" "$@"
```

I've also attempted to rebuild the module with `node-gyp`.

```
$ cd ./node_modules/bignum
$ HOME=~/.atom-shell-gyp node-gyp rebuild --target=0.21.2 --arch=ia32 --dist-url=https://atom.io/download/atom-shell
```

This resulted in the same errors as above attempting to install with `npm`.

Any help would be greatly appreciated, I feel like I've exhausted everything I could do by myself.

**Comment by kevinsawicki** [comment]
The `dyld: lazy symbol binding failed: Symbol not found: _node_module_register` is because you are building apm with node 0.12, you won't see this error if you build it instead using node 0.10

What version of `bignum` are you trying to install? Looks like `0.9.2` came out yesterday, was it that version that was failing?

**Comment by aackerman** [comment]
Yes, `0.9.2` is the version I'm attempting to install. Are there any downsides to using `apm` with node `0.10`? I wouldn't really have any problems with downgrading.

**Comment by kevinsawicki** [comment]
`apm` ships with node 0.10 so there aren't any downsides, you can use something like https://github.com/wfarr/nodenv if you want to manage multiple node installs at once.

**Comment by aackerman** [comment]
I've attempted the following on node `0.10.33` with no success.

```
$ npm install -g atom-package-manager
$ cd ./node_modules/bignum
$ env ATOM_NODE_VERSION=0.21.2 apm install .
```

It fixed the initial `Symbol not found` problem I had using `apm` with node `0.12.0` but resulted in output similar to `npm install bignum` after setting exports.

**Comment by paulcbetts** [comment]
@aackerman If you haven't gotten that far, you should just use https://github.com/atom/atom-shell-starter tbh, it solves all of these dumb problems around module rebuilding - doing it by hand is a huge PITA.

**Comment by aackerman** [comment]
@paulcbetts I'll look into it, it's not clear at the outset how to use native modules with that project, but I'll have more time to figure it out tomorrow.

**Comment by paulcbetts** [comment]
@aackerman You just add them via `npm install --save`, no extra work necessary

**Comment by zcbenz** [comment]
The version of `nan` used by `bignum` doesn't have support for atom-shell yet.
