### ISSUE TITLE
Are all the DLLs etc. which come with the Windows version required?

### ISSUE THREAD

**Issue by shrewdlogarithm** [atom/atom-shell#1153]
Coming from node-webkit, I'm guessing the D3D, xinput, ffmpeg and lifEGL ones are optional if you're not using video/WEBGL/GPU-acceleration and pads (xinput?)??

I'm guessing the version and licence files are required only for licensing rather than functionality (e.g. don't have to be present for test builds)???

chromiumcontent and pak files are 'nw.pak' equivalents and required I guess?

I'm guessing the msvc and vccor ones are also necessary?

Also - and a bit tangentially - is there a default appname you can use so that just running atom.exe will start your app without faffing about with a cmd/bat file (if not - that would be a great idea perhaps?)

TiA!

**Comment by shrewdlogarithm** [comment]
I'd sort-of add to that - are all the contents of locales required too?

I have an application where shipping the fewest files possible is desirable but atom-shell offers benefits, particularly in memory usage, over node-webkit (which is much easier to package at this point?)

**Comment by shrewdlogarithm** [comment]
By way of trying to guess at an answer (a definitive one would be useful tho!) - I've removed the contents of "locales" and the following files with no obvious ill-effects

WebGL/GPU acceleration related?
d3dcompiler_46.dll
libEGL.dll
libGLESv2.dll

This file is for keyboard/controller mappings!?  Not sure why it's in here??
xinput1_3.dll

This one's for HTML5 video which I don't use so...
ffmpegsumo.dll

There are for licensing I guess?
LICENSE
version

I'm assuming the rest are required as something odd happened when they were removed.

Also - it seems you can replace the content of "default_app" with your app and just run atom.exe - at least on Windows - that seems a decent solution to avoiding the faff around of bat/bash scripts??

**Comment by paulcbetts** [comment]
You definitely don't need to have the scripts, I think they're just for development

**Comment by shrewdlogarithm** [comment]
Whilst scripts to do you mean - the code in resources I'd assumed was required, is it just source-code for debugging or???

**Comment by paulcbetts** [comment]
>  faff around of bat/bash scripts??

^^^

**Comment by shrewdlogarithm** [comment]
Unless you install your app in "default_app" (I tried this and it works but I don't know if default_app.asar would??) you have to run the atom executable with a parameter which is the app's name (directory or asar?)

End-users don't type commands - they click icons - so that means providing a cmd/bat/sh file which runs the app for them (which is - if we're honest - a bit of a faff about!)

Ideally there's either a default or a config file which tells it what to run (node-webkit (mis)users a package.json) or something of that ilk?

**Comment by zcbenz** [comment]
Only `LICENSE` and `version` are safe to remove, all other files may be needed by some features.

> Unless you install your app in "default_app" (I tried this and it works but I don't know if default_app.asar would??) you have to run the atom executable with a parameter which is the app's name (directory or asar?)

See https://github.com/atom/atom-shell/blob/master/docs/tutorial/application-distribution.md.
