### ISSUE TITLE
Running atom-shell with no windows active (just a tray icon)

### ISSUE THREAD

**Issue by shrewdlogarithm** [atom/atom-shell#1154]
You can certainly start an atom-shell app with just a tray icon (which launches windows on-demand) but when you close the last window, the app ends automatically?

I could catch the 'close all windows' event and 'do something' to stop that I'm sure - but I'm not sure what (opening a window seems rash as the app certainly starts without one being active!?)

Background: trying to make a low-footprint cross-platform app which opens a mix of web and locally- sourced content on-demand - already using node-webkit but it consumes/leaks large amounts of memory opening/closing windows over time which atom-shell doesn't seem to do (awesome!)

I don't really see why you NEED a window open to keep the application alive - would be nice if it didn't have to be so (tho I could open a placeholder Window if need-be)

**Comment by zcbenz** [comment]
The default behavior of atom-shell is to quit when all the windows are closed, so if you create a window and then close it, this behavior will be triggered to quit the app. To override this you can simply catch the `window-all-closed` event and do nothing in it.
