### ISSUE TITLE
Window Position

### ISSUE THREAD

**Issue by kirubasankars** [atom/atom-shell#1159]
I wanted to place my window near to tray. How do I do that?

new BrowserWindow({width: 800, height: 600});

**Comment by sprintr** [comment]
I think you can use x, y positions in the options. or use `BrowserWindow.setPosition(x, y)` API.

**Comment by shrewdlogarithm** [comment]
I think he's asking how to know where the tray IS (it's not always bottom-right) - I suspect the answer to that is "you can't" - certainly it will be a bespoke thing for Windows (normally bottom-right), Linux (normally top) and OSX (always top?)

Even if you assume it is always in the same place (based on the OS) you then need to know how wide/high the screen is for "for right or bottom-right position)

I can't find any way to detect screen size in "main.js" but you can within a browserwindow so you'll need to create a window (set to not show), open it - it's code can then move it to where it should be and then show it (via remote.getCurrentScreen()....) and voila...

**Comment by bwin** [comment]
@shrewdlogarithm Please describe your problem with using `screen` from browser-side?

I have no problem with 0.21.2 on win32.
```js
var app = require('app');
app.on('ready', function() {
  var atomScreen = require('screen');
  console.log(atomScreen.getAllDisplays());
});
```

**Comment by shrewdlogarithm** [comment]
I don't have a problem - I said I didn't know how to do it

Also - why do people call main.js "browser side" when it's actually "node side" surely?

"browser side" is inside browserwindow surely?

**Comment by bwin** [comment]
That's the renderer-side...
Yeah, those names can definitely get confusing (althogh they do make sense). If we had better distinguishable (new) names and a majority of people we're using those it would be good.
But currently I'll stick to the official names (from the docs), this way it is defined what you meant and not open to interpretation what the "browser" is.

Sorry for going off-topic on this...

**Comment by zcbenz** [comment]
There is no reliable way to get position of Tray icon on all platforms, so I don't think we will have support for this.
