### ISSUE TITLE
Add AppVeyor badge to front page

### ISSUE THREAD

**Issue by lllama** [atom/atom-shell#1163]
Currently only shows the TravisCI badge, which I'm assuming is *nix only

**Comment by zcbenz** [comment]
We are currently not using AppVeyor because its building is too slow (over 30min) to be useful.

**Comment by lllama** [comment]
Supposedly AppVeyor have a faster build environment available now: http://www.appveyor.com/blog/2015/06/23/new-oss-build-environment-and-xamarin-support

Is this worth revisiting?

**Comment by zcbenz** [comment]
@lllama I just tried with their new environment, the bootstrap script still took > 10m to run (and failed), so the whole building can easily go over 30m. 

https://ci.appveyor.com/project/zcbenz/electron/build/2
