### ISSUE TITLE
webview plugins

### ISSUE THREAD

**Issue by skandasoft** [atom/atom-shell#1164]
does the webview plugin work for all embeded object.. I am on windows 7 and atom is 0.181
```
<webview plugins="true" nodeintegration="true" tabindex="-1" disablewebsecurity="true" src="1.html"></webview>
```

in the 1.html I have the following embed objects..

```
<embed width="420" height="315" src="bookmark.swf">
<embed width="420" height="315" src="http://www.youtube.com/v/XGSy3_Czz8k">
<object width="420" height="315" data="http://www.youtube.com/v/XGSy3_Czz8k">
<embed src="info.pdf" width="500" height="375">
```

None of these plugins seem to work(swf/youtube/pdf)..what is missing.

**Comment by mark-hahn** [comment]
Check the console output of the webview for errors.

**Comment by paulcbetts** [comment]
@skandasoft Yes they work, you need to have the NPAPI version of Flash installed though

**Comment by skandasoft** [comment]
what does that mean since NPAPI is going away. In regular chrome browser I am able open all these without any of these plugin(NPAPI). I am assuming that webview should be able to do the same...am I missing some thing here..

**Comment by zcbenz** [comment]
> what does that mean since NPAPI is going away. In regular chrome browser I am able open all these without any of these plugin(NPAPI). I am assuming that webview should be able to do the same...am I missing some thing here..

Chrome uses pepper API for flash, which is not supported in atom-shell yet (#912). You have to use NPAPI version of flash in atom-shell.
