### ISSUE TITLE
Question: How to spawn and control multiple threads

### ISSUE THREAD

**Issue by steelbrain** [atom/atom-shell#1165]
I have tried web workers, they work great, but their's no NodeJS stuff like `require()` etc in their context.
So is there way to spawn multiple threads and control them?
I want to use them to compile js using uglifyjs and modules like that without blocking the main app.

**Comment by paulcbetts** [comment]
Give `child_process.fork` a try

**Comment by steelbrain** [comment]
I cant believe I did this >_<
I am using pcntl_fork already on my other projects, It's a great way to manage child processes.
Thank You for reminding me @paulcbetts
