### ISSUE TITLE
asar deters me from using atom-shell

### ISSUE THREAD

**Issue by shrewdlogarithm** [atom/atom-shell#1166]
As a developer working on Windows asar is a pain-in-the-ass to get working (I raised an issue in that repo - dependencies on Python and ancient Net Frameworks) and it seems a bit of an unfinished thing to be trusting???

Coming from node-webkit, packaging an atom-shell app is a bit of a mess - I raised another issue here about which files are absolutely required because users are getting more wary of what they install (as they should be) and applications which ship with a tonne of files are a major turn-off - not to mention being a PiTA the maintain/update!?

Just my 10p - it would be nice to have a bit more detail on which files are required/optional and perhaps an alternative to asar which doesn't involve sending all the source files (a zip which is extracted at run-time - ala node-webkit - for example)

Note: I'm not interested in 'hiding' or 'obfuscating' source because that's a waste of time - I'd just like a neater way of distributing apps!

Any plans in that area?

**Comment by paulcbetts** [comment]
You don't have to use ASAR if you don't want to, it's entirely optional for your applications. ASAR's main benefit is load-time performance in large applications, not obfuscation, but again, it's entirely optional

**Comment by shrewdlogarithm** [comment]
I realise it's not mandatory - but it is the only option other than "just include all the source files"?

It might just be my view of distribution, but shipping either portable or installer-based apps which have a tonne of files is just a way of making your life harder when updates and other issues arise.

In my ideal world you have a small group of 'platform specific' files, a single file for your app and maybe some data files - KISS and all that?

**Comment by YuriSolovyov** [comment]
node-webkit .zip extracting at load-time is not great too. discussion was here: https://github.com/atom/atom-shell/issues/251

**Comment by paulcbetts** [comment]
> In my ideal world you have a small group of 'platform specific' files, a single file for your app and maybe some data files - KISS and all that?

This *is* ASAR. I

**Comment by shrewdlogarithm** [comment]
The concept behind sending the source in an archive is great but when you choose to go a completely new route like that, you have to expect people like me to go "erm - is this ready for production use?" and asar may not quite be there was my point here?

Certainly there seems to be some work needed to make asar work better on Windows and - indeed - offer a few more features so we can create asar archives without having a pile of files on a disk (a pile of files in GitHub is the obvious example)

I'm not actually worried about sending raw source directories and files - other than how ugly and unprofessional it looks (and that it makes more work for doing updates - having to manage 100s of files instead of 1)

I never really liked the node-webkit approach of unzipping everything into temp but the only platform it's ever given me a headache on is OSX (node-webkit is not a particular stable thing on OSX at the best of times!) because of the way OSX apps are structured it's a BIT of a pain-in-the-ass.

**Comment by shrewdlogarithm** [comment]
Closing this as I think it's run-out it's usefulness - for now I'm going to test my app with atom-shell using source-code - tho I'm planning to make some sort of middleware asar packager at some point 

I don't want native code in the client and I don't want to have to make an asar specifically (I just push and release code on Github) so a middleware to find a release and bundle it as an asar would be ideal.
