### ISSUE TITLE
API for javascript execution status

### ISSUE THREAD

**Issue by maxogden** [atom/atom-shell#1168]
node tracks async operations and keeps the process open while they are running, and exposes [unref](http://nodejs.org/api/timers.html#timers_unref) as a way to disable this behavior.

I'm curious if Chromium tracks async events and supports similar functionality for JS execution in pages. It would be cool if you could do e.g. `browserWindow.on('did-javascript-finish'` to get notified when JS finishes executing in a page.

I am not sure if this is possible, but I thought it would be worth asking :)

**Comment by Wortex17** [comment]
Hmm what you are actually asking for would be asking to the stack and the message queue / event loop.
I doubt this is possible atm, but would actually be very interesting.

> to get notified when JS finishes executing in a page.

I doubt this is really useful. Actually, as long as any event listeners are there and the message queue isn't empty, this is never the case. You would get this 'event' very rarely, if at all, and only for pages that are DESIGNED for that.

**Comment by zcbenz** [comment]
It is hard to define when JS finished executing. In web page, under most cases when the document is loaded the JS has already finished executing, most code just starts to run when the `onload` event happens. So this would be quite meaningless in the case of web page.
