### ISSUE TITLE
IPC not available when navigating to the next page

### ISSUE THREAD

**Issue by skandasoft** [atom/atom-shell#1169]
when navigating to the next page using link in the current page, 'ipc' is not available any more in the next page / it doesn't listen to the message from the container anymore..do I have rerun the preload once more to get the ipc to listen for the messages..

**Comment by zcbenz** [comment]
Can you give a minimal demo that shows this problem?

**Comment by skandasoft** [comment]
It is the same issue as https://github.com/atom/atom-shell/issues/921 
when clicking on a link of a page it loads the next  without the preload.js nor does it have access to the require

**Comment by paulcbetts** [comment]
We hit this issue too - here's how to repro:

1. Create a WebView with both a preload script and point to an HTTP(S) page
1. In the preload script, define some global variables (i.e. `window.myAwesomeMethod = function() { require('fs').writeFileSync("/tmp/myfile.txt", "hello"); }`)
1. Start the app, click on some links in page
1. Try to use `myAwesomeMethod`, it is undefined.

**Comment by zcbenz** [comment]
@paulcbetts Were you using v0.21.2? I tried to reproduce with following code but it works fine:

Open devtools and run:

```javascript
var w = new WebView;
w.addEventListener('console-message', function(e) {
  console.log(e.message);
});
w.src = 'https://github.com'
w.setAttribute('preload', 'file:/tmp/test.js');
document.body.appendChild(w);
```

The content of `/tmp/test.js` is:

```javascript
window.test = 'test'
console.log('preload');
```

Click the links in the page and you can see `preload` is printed every time and `window.test` is set to `test`.

**Comment by paulcbetts** [comment]
@zcbenz I wonder if I'm being hit by that Chrome "optimization" again with script contexts. The last page where we were relying on the preload context being there, is a super-empty dummy page:

```
<html>
<script>winssb.didSignIn()</script>
</html>
```

**Comment by zcbenz** [comment]
@paulcbetts I tried to navigate to that page but it works fine, was it possible that you were running an old version of atom-shell? We had the problem before v0.21.1.

**Comment by paulcbetts** [comment]
@zcbenz I can look into it again

**Comment by zcbenz** [comment]
@paulcbetts I think we can wait to see if @skandasoft can provide more information.

**Comment by skandasoft** [comment]
I am on the latest version of atom.so not sure what version of atom shell. I am still facing the issue. the first time you load the webview with the src attribute it open the web page. And when you open the developer tool and type require, it is available. when you click on the link of the page, it navigates to the next one and in the developer tool require is not available.

**Comment by zcbenz** [comment]
@skandasoft You can get the version of atom-shell with `process.versions['atom-shell']`.

**Comment by skandasoft** [comment]
"0.21.0"

**Comment by zcbenz** [comment]
@skandasoft You need to update to at least v0.21.2.

**Comment by jimmcslim** [comment]
Here's a repro showing that process.versions stops working (also `require()`) when the browser goes back in history (via backspace key) https://github.com/jimmcslim/atomtest

**Comment by pfffr** [comment]
Confirmed. btw: you should better not dupe 'app.js' anyway.

**Comment by skandasoft** [comment]
how would you update the version for atom-shell.. I am on windows 7..and it updates automatically atom editor

**Comment by jimmcslim** [comment]
@pfffr What do you mean by that? Is app.js a reserved filename? In my example, I'm just using it as a script to be loaded by index.html in the Rendered process which also happens to perform a `require`.

@skandasoft My example uses the `grunt-download-atom-shell` grunt task to download atom-shell, `Gruntfile.js` specifies the version to use (0.21.3 in this case). I think you would only update atom-shell as part of an update to your whole application, which you would be updating via Squirrel perhaps.

**Comment by pfffr** [comment]
@jimmcslim There is *app.coffee*, so you use default *require ('app')* in your atom-shell application. That literally could cause problems.

**Comment by bwin** [comment]
@skandasoft Just wait for an update to atom.
@jimmcslim skandasoft is using the atom editor, not his own app.
I think you mean rep**~~r~~**o, short for repository, right? Maybe I'm wrong...
@pfffr `require('app')` is ok. This only looks in node_modules (that's what he wanted). To require your own files you would use `require('./app')`.
I think the file-structure in the example is just a little bit mixed up. Just from lookiing at path+filename you won't know if it's browser- or renderer-code.

**Comment by zcbenz** [comment]
@skandasoft Sorry I thought you were writing your own Atom Shell app, I'll bump the version of Atom Shell in Atom editor.

**Comment by jimmcslim** [comment]
@bwin Sorry, I mean repro as in reproduction of the issue... maybe not this issue but definitely #921! My example atom-shell project in the linked repository demonstrates an issue with require() no longer being available when you load a page in atom-shell, then backspace to return to the previous page (which has a dependency on require()).

**Comment by pfffr** [comment]
@bwin Of course. But: he uses the normal *require('app')* and his own *require('app.js')*. That probably can cause future typo problems. ;)

**Comment by skandasoft** [comment]
when would the bumped atom-shell be available in atom editor
