### ISSUE TITLE
is there a way to execute javascript on developer tool console and get result back

### ISSUE THREAD

**Issue by skandasoft** [atom/atom-shell#1171]
is there a way to execute javascript on developer tool console and get result back. I see that the chrome-debugging-protocol client has to be used for a such a thing..

**Comment by zcbenz** [comment]
You can use the [`devToolsWebContents` attribute of `BrowserWindow`](https://github.com/atom/atom-shell/blob/master/docs/api/browser-window.md#browserwindowdevtoolswebcontents) to execute JavaScript in devtools. It is not possible to get the result though.

**Comment by frankhale** [comment]
This comment isn't related to the original issue but when I attempted to use devToolsWebContents on my browser window it returned undefined. Is this a bug in 0.21.2?

**Comment by zcbenz** [comment]
@frankhale The devtools must be opened when accessing the `devToolsWebContents`.

**Comment by frankhale** [comment]
Ah, okay I will give it another try.

**Comment by frankhale** [comment]
Yeah yeah, I did that. This code fails for me, I'll open an issue:

```
  var browser = remote.getCurrentWindow();
  browser.openDevTools();
  console.log(browser.devToolsWebContents); // devToolsWebContents is undefined
```
