### ISSUE TITLE
atom-shell not available on CentOS?

### ISSUE THREAD

**Issue by gliurn** [atom/atom-shell#1172]
Hi, i tried to run atom-shell on CentOS 6.6 but i got this error:
./atom: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by ./atom)
./atom: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./atom)
./atom: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./atom)
./atom: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /root/atom-shell/libchromiumcontent.so)
./atom: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /root/atom-shell/libchromiumcontent.so)
./atom: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /root/atom-shell/libgcrypt.so.11)
./atom: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /root/atom-shell/libgcrypt.so.11)

the problem seems to come from libstdc++.so.6 any ideas to solve this?

**Comment by gliurn** [comment]
After some research it seems there is no solutions exept upgrade to CentOS 7 (which works btw) because atom-shell have been compil under Ubuntu. if you want to go deeper, here is an interresting link about the same issue with Chrome http://chrome.richardlloyd.org.uk/

**Comment by blackSea4477** [comment]
Just Copy 
- libstdc++.so.6  
- ld-linux-x86-64.so.0
- libc.so.6
- libgtk-x11-2.0.so.0 
under the path .....src/node_modules/electron/dist . You can get this from Centos 7 . 
Then Download https://jlison.github.io/bin/centos6/soichih/mirror/gcc-4.7.2.tar.gz and extarct it to some folder and update LD_LIBRARY_PATH 

glibpath=/opt/glib/  (path where you have extracted glib )

export LD_LIBRARY_PATH=$glibpath/glib-2.49.4-kgesagxmtbemim2denf65on4iixy3miy/lib:$LD_LIBRARY_PATH

export LD_LIBRARY_PATH=$glibpath/libffi-3.2.1-wk2luzhfdpbievnqqtu24pi774esyqye/lib64:$LD_LIBRARY_PATH

export LD_LIBRARY_PATH=$glibpath/pcre-8.39-itdbuzevbtzqeqrvna47wstwczud67wx/lib:$LD_LIBRARY_PATH

export LD_LIBRARY_PATH=$glibpath/gettext-0.19.8.1-aoweyaoufujdlobl7dphb2gdrhuhikil/lib:$LD_LIBRARY_PATH


I am able t o run electron on my centos 6.5 and nothing breaks !

**Comment by blackSea4477** [comment]
Just Copy 
- libstdc++.so.6  
- ld-linux-x86-64.so.0
- libc.so.6
- libgtk-x11-2.0.so.0 
under the path .....src/node_modules/electron/dist . You can get this from Centos 7 . 
Then Download https://jlison.github.io/bin/centos6/soichih/mirror/gcc-4.7.2.tar.gz and extarct it to some folder and update LD_LIBRARY_PATH 

glibpath=/opt/glib/  (path where you have extracted glib )

export LD_LIBRARY_PATH=$glibpath/glib-2.49.4-kgesagxmtbemim2denf65on4iixy3miy/lib:$LD_LIBRARY_PATH

export LD_LIBRARY_PATH=$glibpath/libffi-3.2.1-wk2luzhfdpbievnqqtu24pi774esyqye/lib64:$LD_LIBRARY_PATH

export LD_LIBRARY_PATH=$glibpath/pcre-8.39-itdbuzevbtzqeqrvna47wstwczud67wx/lib:$LD_LIBRARY_PATH

export LD_LIBRARY_PATH=$glibpath/gettext-0.19.8.1-aoweyaoufujdlobl7dphb2gdrhuhikil/lib:$LD_LIBRARY_PATH


I am able t o run electron on my centos 6.5 and nothing breaks !

**Comment by BotellaA** [comment]
I am under RHEL6.8 and I have the same issue. I tried the above solution but I only found ld-linux-x86-64.so.2 and not ld-linux-x86-64.so.0. Does this matter?

Executing electron with this solution give me this error:
```libc.so.6: symbol _dl_starting_up, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference```

Do you have an idea to fix this?
Thank for your help

**Comment by Zubairlatif** [comment]
> I am under RHEL6.8 and I have the same issue. I tried the above solution but I only found ld-linux-x86-64.so.2 and not ld-linux-x86-64.so.0. Does this matter?

Executing electron with this solution give me this error:
libc.so.6: symbol _dl_starting_up, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference

Do you have an idea to fix this?
Thank for your help

@BotellaA Did you find any solution about your problem? because I'm also facing this problem.
