### ISSUE TITLE
Defining a 'default' app

### ISSUE THREAD

**Issue by Wortex17** [atom/atom-shell#1178]
Sorry if this is somewehre in the docs, but i didn't find anything related to it:
When executing atom without a command line argument (or clicking on it through explorer/finder),
by default atom-shell shows an information page to load an app.

Now, for packaging and releasing this really doesn't look very nice, as it should actually start the application and just pass the argument to it.
Is there a way to define a "default" app that is loaded if none is given - afterwards or in the build process?

How are you guys handling the release packaging? (I try to keep away from installers which would generate bash files or shortcuts as startpoint)

**Comment by bwin** [comment]
You can put a folder named `app` or an asar-archive `app.asar` under `resources`. The `default_app` will load one of them automatically. Have a look at the `default_app`.

**Comment by Wortex17** [comment]
Ah, now i see!
Wow, looks really clean, coming from nwjs ;)
Thanks!
