### ISSUE TITLE
Does <webview> support "Remote debugging protocol"?

### ISSUE THREAD

**Issue by popopome** [atom/atom-shell#1179]
I want to develop built-in *javascript debugger* with `<webview>`.
`<webview>` has apis to open devtool according to docs. 
But I couldn't find any way to connect remote debugging port such as [Remote debugging protocol](https://developer.chrome.com/devtools/docs/debugger-protocol)

Any hints or docs? 
Thanks.

**Comment by mark-hahn** [comment]
I don't know the answer to your question but you should know that remote
debugging currently doesn't work with ioJS.

**Comment by zcbenz** [comment]
I think the answer is Yes.

```bash
$ atom-shell --remote-debugging-port=9222
$ curl http://127.0.0.1:9222/json
```

But you have to communicate with the raw protocol, there is no things like `chrome.debugger` in atom-shell.

**Comment by popopome** [comment]
What I want to do is connecting to `<webview>` process neither **browser process** or **renderer side**. In my understanding `<webview>` has its own process and it means the debugging port should be different with browser or renderer side. 

I didn't try your suggestion yet but it looks like only for browser side.

Thanks.

**Comment by zcbenz** [comment]
@popopome It works for all web pages including the webview.

**Comment by popopome** [comment]
Sounds great!
I'll try it!
Thanks.
