### ISSUE TITLE
If we can customize dialog CSS style?

### ISSUE THREAD

**Issue by caracare521** [atom/atom-shell#1180]
just tried dialog module, very useful.
But wondering if we can customize its CSS style? 
Currently it's just a default chrome style, white background, black font.

**Comment by frankhale** [comment]
Dialogs are native so I assume it's not possible to style with CSS. What about using one of the various modal dialog jQuery plugins or something similar?

**Comment by zcbenz** [comment]
They are native dialogs so there is no way to customize them with CSS.

**Comment by caracare521** [comment]
Alright, thanks
