### ISSUE TITLE
The fire time of browser Window "did-finish-load" event changed?  

### ISSUE THREAD

**Issue by caracare521** [atom/atom-shell#1181]
So I got a problem in my project after updated atom-shell from v20.6 to v21.2.

Here is some sample code:

First I have a base window controller file on the browser side.
this.browserWindow.webContents.on ('did-finish-load', (function(_this) {
        return function() {
          console.log("this window's setting's params should be: ", _this.settings.params);
          return _this.browserWindow.webContents.send('command', _this.settings.params);
        };

After a browser window's 'did-finish-load' event captured, will fire a "command" with params to its webContents.

Then this just "did-finish-load" browser window itself on render side will catch this 'command' and its
params, then do some following steps according to this params.

ipc.on('command', function(params) {
    console.log("received params are: ", params);
}

This was Okay while using v0.20.6. But now browser window won't be able to catch this "command".
Looks like, "did-finish-load" event is fired earlier than before now.

Any idea? @zcbenz

**Comment by zcbenz** [comment]
I can not reproduce this, can you provide a minimal example?

**Comment by caracare521** [comment]
@zcbenz , after I wrote a small example, I find that atom-shell v21.2 works correctly.
But this does occur on my project. So after some investigation, with some guess and luck,
I am able to find out why. 

We are using $stateProvider(ui.router) to do web page swapping on render side.
And I use a temp default state, then it will transfer to a certain state according to user input.
This state changing is fairly quick. So it was running okay using v20.6.
Here is how it looks like:

$stateProvider
  .state 'index',
    url: '/'
  views:
      'main':
        templateUrl: "../shiftTemplate.html"
        controller: ['$state', '$q', '$location', ($state, $q, $location) ->
          $state.transitionTo 'chat'
        ]
 .state 'secondState',
    url: '/secondState'
  controller:[
    ##do something, for example catching command
   ]

But after updated to v21.2, somehow atom-shell's running speed is increased a little bit.
Maybe it's caused by Chrome's update or nodejs's update, or you optimized some code in atom-shell. Due to this speed increasing, the command will be sent to this web page on render side
while it's still in default state (called index here). This will lead to a command lost in the project.
That's how problem #1181 occurs. 

Now I remove this default state, It works fine now.

If later I really need default state, I will try to pass useful params to its next state.

@zcbenz, now you can close this issue, as it's just a timing issue.
Just keep in mind, maybe later this would come back to atom-shell in another form.

**Comment by zcbenz** [comment]
Glad to know it has been solved, thanks for sharing your findings.
