### ISSUE TITLE
Rebuilding sqlite3 failed.

### ISSUE THREAD

**Issue by mese79** [atom/atom-shell#1182]
Hi
I'm using atom-shell 0.21.2 and i'm trying to rebuild sqlite3 for my app but with no success.
i tried all three ways in [here](https://github.com/atom/atom-shell/blob/master/docs/tutorial/using-native-node-modules.md), but none of them works.
```
$ export ATOM_NODE_VERSION=0.21.0
$ apm install .
```
so output is:
> gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.10.35 | linux | x64
gyp http GET https://atom.io/download/atom-shell/v0.21.0/node-v0.21.0.tar.gz
gyp http 200 https://atom.io/download/atom-shell/v0.21.0/node-v0.21.0.tar.gz
gyp http GET https://atom.io/download/atom-shell/v0.21.0/SHASUMS256.txt
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: getaddrinfo ENOTFOUND
gyp ERR! stack     at errnoException (dns.js:37:11)
gyp ERR! stack     at Object.onanswer [as oncomplete] (dns.js:124:16)
gyp ERR! System Linux 3.14.27-desktop-1.mga4
gyp ERR! command "/usr/lib/node_modules/atom-package-manager/bin/node" "/usr/lib/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=0.21.0" "--dist-url=https://atom.io/download/atom-shell" "--arch=x64" "--ensure"
gyp ERR! cwd /home/mehdi/.atom
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 

```
$ HOME=~/.atom-shell-gyp node-gyp rebuild --target=0.21.0 --dist-url=https://atom.io/download/atom-shell
```
and the output is:
> gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.11.14 | linux | x64
child_process: customFds option is deprecated, use stdio instead.
gyp info spawn python
gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/mehdi/temp/test/atom-shell-v0.21.2-linux-x64/resources/app/gyp-node_modules/sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/mehdi/.atom-shell-gyp/.node-gyp/0.21.0/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/mehdi/.atom-shell-gyp/.node-gyp/0.21.0',
gyp info spawn args   '-Dmodule_root_dir=/home/mehdi/temp/test/atom-shell-v0.21.2-linux-x64/resources/app/gyp-node_modules/sqlite3',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
**gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp**
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1059:12)
gyp ERR! System Linux 3.14.27-desktop-1.mga4
gyp ERR! command "node" "/usr/bin/node-gyp" "rebuild" "--target=0.21.0" "--dist-url=https://atom.io/download/atom-shell"
gyp ERR! cwd /home/mehdi/temp/test/atom-shell-v0.21.2-linux-x64/resources/app/gyp-node_modules/sqlite3
gyp ERR! node -v v0.11.14
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 

```
$ export npm_config_disturl=https://atom.io/download/atom-shell
$ export npm_config_target=0.21.0
$ export npm_config_arch=x64
$ HOME=~/.atom-shell-gyp npm install sqlite3
```
it gives me:
> sqlite3@3.0.5 install /home/mehdi/temp/test/atom-shell-v0.21.2-linux-x64/resources/app/node_modules/sqlite3
node-pre-gyp install --fallback-to-build
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: Unsupported target version: 0.21.0
node-pre-gyp ERR! stack     at get_runtime_abi (/home/mehdi/temp/test/atom-shell-v0.21.2-linux-x64/resources/app/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/versioning.js:132:23)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/home/mehdi/temp/test/atom-shell-v0.21.2-linux-x64/resources/app/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/versioning.js:241:21)
node-pre-gyp ERR! stack     at install (/home/mehdi/temp/test/atom-shell-v0.21.2-linux-x64/resources/app/node_modules/sqlite3/node_modules/node-pre-gyp/lib/install.js:134:35)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/home/mehdi/temp/test/atom-shell-v0.21.2-linux-x64/resources/app/node_modules/sqlite3/node_modules/node-pre-gyp/lib/node-pre-gyp.js:49:37)
node-pre-gyp ERR! stack     at run (/home/mehdi/temp/test/atom-shell-v0.21.2-linux-x64/resources/app/node_modules/sqlite3/node_modules/node-pre-gyp/bin/node-pre-gyp:77:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/home/mehdi/temp/test/atom-shell-v0.21.2-linux-x64/resources/app/node_modules/sqlite3/node_modules/node-pre-gyp/bin/node-pre-gyp:130:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:460:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:478:10)
node-pre-gyp ERR! stack     at Module.load (module.js:355:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:310:12)
node-pre-gyp ERR! System Linux 3.14.27-desktop-1.mga4
node-pre-gyp ERR! command "node" "/home/mehdi/temp/test/atom-shell-v0.21.2-linux-x64/resources/app/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/mehdi/temp/test/atom-shell-v0.21.2-linux-x64/resources/app/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.11.14
node-pre-gyp ERR! node-pre-gyp -v v0.6.2
node-pre-gyp ERR! not ok 
**Unsupported target version: 0.21.0**
npm ERR! Linux 3.14.27-desktop-1.mga4
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sqlite3"
npm ERR! node v0.11.14
npm ERR! npm  v2.0.0
npm ERR! code ELIFECYCLE
npm ERR! sqlite3@3.0.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.0.5 install script.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

I also tried to change target into 0.21.2 but results was the same.
I guess i'm lost in **atom-shell version** vs **atom-node version** vs **installed node version**!
here is some info:
```
$ apm -v
apm  0.141.0
npm  2.5.1
node 0.10.35
python 2.7.6
git 1.8.5.6

$ node -v
v0.11.14

$ node-gyp -v
v1.0.2
```

And finally i tried to run my app to see sqlite related error:
>A JavaScript error occured in the browser process
Uncaught Exception:
**Error: Cannot find module '/home/mehdi/temp/test/atom-shell-v0.21.2-linux-x64/resources/app/node_modules/sqlite3/lib/binding/node-v41-linux-x64/node_sqlite3.node'**
    at Function.Module._resolveFilename (module.js:351:15)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/home/mehdi/temp/test/atom-shell-v0.21.2-linux-x64/resources/app/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:475:26)
    at Object.Module._extensions..js (module.js:493:10)
    at Module.load (module.js:370:32)
    at Function.Module._load (module.js:325:12)
    at Module.require (module.js:380:17)

```node_modules/sqlite3/lib/binding/node-v41-linux-x64/node_sqlite3.node``` ?!!
So please tell what to do?

**Comment by mese79** [comment]
This process.versions in sample app:
![versions](https://cloud.githubusercontent.com/assets/1878378/6418897/e5338d78-becd-11e4-967c-893138df0e1d.png)

**Comment by zcbenz** [comment]
From your first result:

```
gyp ERR! stack Error: getaddrinfo ENOTFOUND
```

It was apparently networking problem.

From your third result:

```
node-pre-gyp install --fallback-to-build
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: Unsupported target version: 0.21.0
```

Somehow it switched to use `node-pre-gyp` instead of `node-gyp`, which doesn't support atom-shell yet.

I suggest reporting this to node-sqlite3 since people there may have better knowledge of this. I'm closing this since it is not a problem of atom-shell.

**Comment by mese79** [comment]
Could you tell me about versions at least? i mean ```--target``` or ```npm_config_target``` should be what for ```atom-shell 0.21.2``` ?
Have you notice the screenshot of ```0.21.2```? isn't version of **modules** and **node** weird?
This is the 0.19.0 shot:
![0 19 0](https://cloud.githubusercontent.com/assets/1878378/6437095/be44f302-c0ce-11e4-827c-f28978667805.png)

**Comment by bwin** [comment]
Atom-Shell >= 0.12 uses io.js instead of node, so the versions are ok.
sqlite3 uses node-pre-gyp to build, so currently no atom-shell support.
You can build sqlite3 for atom-shell <=0.20.x with https://github.com/bwin/aspm.

**Comment by olimsaidov** [comment]
For anyone having same issue: http://verysimple.com/2015/05/30/using-node_sqlite3-with-electron/

**Comment by milesoldenburg** [comment]
Thanks, @olimsaidov. Those linked steps worked for me, pasting here for posterity.

```
cd node_modules/sqlite3
npm run prepublish
node-gyp configure --module_name=node_sqlite3 --module_path=../lib/binding/node-v43-darwin-x64
node-gyp rebuild --target=0.27.1 --arch=x64 --target_platform=darwin --dist-url=https://atom.io/download/atom-shell --module_name=node_sqlite3 --module_path=../lib/binding/node-v43-darwin-x64
```
Modify for your version of electron and node. I tested with 0.29.1 and v44.

**Comment by fritx** [comment]
@milesoldenburg where to see the v44? thanks

**Comment by milesoldenburg** [comment]
@fritx It depends on the version you of electron and node you are running. So in my case I just swapped 0.27.1 in the snippet with 0.29.1 and v43 with v44.

**Comment by fritx** [comment]
ok thanks i will try it @milesoldenburg and also snippet from @olimsaidov

**Comment by fritx** [comment]
unfortunately i'm on Windows, any guys know how to deal with it? :cry: 
![qq 20150828105638](https://cloud.githubusercontent.com/assets/6647633/9538091/4256e002-4d73-11e5-9114-e3832c98a4e8.jpg)
![qq 20150828105642](https://cloud.githubusercontent.com/assets/6647633/9538092/425d9168-4d73-11e5-99c6-bf7098a07e23.jpg)

**Comment by zcbenz** [comment]
For people building sqlite3 for v0.31.0, checkout https://github.com/mapbox/node-sqlite3/issues/498.

**Comment by fritx** [comment]
@zcbenz thanks finally it worked.. I used the fork:

```plain
"dependencies": {
  "sqlite3": "git://github.com/kkoopa/node-sqlite3.git#nan2",
}
```
