### ISSUE TITLE
browser.devToolsWebContents returns undefined when DEV tools are opened

### ISSUE THREAD

**Issue by frankhale** [atom/atom-shell#1186]
I'd like to get the dev tools web contents but it returns undefined. 

Here is a snippet to reproduce the problem. I'm using Atom-Shell 0.21.2 on Windows 8.1 x64.

```javascript
var browser = remote.getCurrentWindow();
browser.openDevTools();
console.log(browser.devToolsWebContents); // it's undefined, boo!
```

**Comment by zcbenz** [comment]
If you access `devToolsWebContents` in browser process then things would work.

This is related to the handling of object's members in `remote` module, I'll figure out a way to fix this case.

**Comment by frankhale** [comment]
I'm running this in code that runs in the browser window as opposed to the main.js which opens the browser window. I'm assuming by run this in the browser process you mean my main.js?

**Comment by zcbenz** [comment]
> I'm assuming by run this in the browser process you mean my main.js?

Yes.

**Comment by frankhale** [comment]
Cool, thanks! I'll give this a shot.
