### ISSUE TITLE
Record io.js version used in each release

### ISSUE THREAD

**Issue by TimothyGu** [atom/atom-shell#1188]
It would be extremely helpful if the io.js version bundled in each release is recorded. This would help tracking down ABI issues for binary modules.

**Comment by frankhale** [comment]
You can get the io.js version using process.version

Atom-Shell 0.21.2 reports v1.0.0-pre

**Comment by TimothyGu** [comment]
@frankhale I know *that*, but currently you can't get this information ahead of time.

**Comment by zcbenz** [comment]
It is recored in https://atom.io/download/atom-shell/index.json.

**Comment by TimothyGu** [comment]
ah ok thanks
