### ISSUE TITLE
how to use <webview>.insertCSS ?

### ISSUE THREAD

**Issue by dygg** [atom/atom-shell#1190]
when i try to use the <webview>.insertCSS api, nothing happened.

i use it like : 

`..insertCSS("body{background:#000}")`

or

`..insertCSS(__dirname + "/css/webview.css")`

it's  wrong?

**Comment by zcbenz** [comment]
It inserts CSS string, e.g. your first code.

If it doesn't work then it is very likely your rule has been overridden by the page's rules, you can use devtools to check that.

**Comment by piyushagade** [comment]
Use it this way:
<webview>.insertCSS(fs.readFileSync(path.join(__dirname, 'yourCSSFile.css'), 'utf8'));
