### ISSUE TITLE
Howto foreground instance and to prohibit dupes?

### ISSUE THREAD

**Issue by pfffr** [atom/atom-shell#1193]
Anyone got an idea on how to prevent starting an atom-shell app twice, better foregrounding the original instance on multiple launch in win32, f.e. "atom.exe my_app/"? I just a need an idea. :8ball:

**Comment by zcbenz** [comment]
@pfffr See https://github.com/atom/atom-shell/issues/648.

**Comment by pfffr** [comment]
Found that, too. Does not work for me on current git branch + Win7 64bit.

**Comment by pfffr** [comment]
This is hilarious CoffeeScript shizzle. Could anyone provide a sample application.coffee, just containing  Application Class with working socket just showing up an index.html window?

**Comment by olegam** [comment]
Seems to work fine. I put this into a single function that I call right after creating the app window: https://gist.github.com/olegam/10b87e3e54a859506a8d
Works on both Mac and Windows.
