### ISSUE TITLE
auto-updater should warn or err whenever the app is not signed

### ISSUE THREAD

**Issue by joaomoreno** [atom/atom-shell#1196]
I experimented with the `auto-updater` module and found it hard to deal with since it gave me no feedback at all. I eventually signed my application and, of course, I started getting something.

It would be nice to get a warning when calling any of the two methods (`setFeedUrl` and `checkForUpdates`) whenever the application is not signed, instead of no feedback at all.

**Comment by jspahrsummers** [comment]
Squirrel.Mac already [catches this case](https://github.com/Squirrel/Squirrel.Mac/blob/b1f4ecf615ad3b9f4b92929eb7ed6427993ecd09/Squirrel/SQRLUpdater.m#L158-L166).
