### ISSUE TITLE
<webview>.reload() does not preload specified script

### ISSUE THREAD

**Issue by jofan** [atom/atom-shell#1197]
When having the following:

<webview src="http://localhost:8080" preload="./test.js"></webview>

In test.js:

document.addEventListener("DOMContentLoaded", function(event) {
  console.log("DOM fully loaded and parsed");
});

Then the event listener or any other code in test.js will not be called when doing <webview>.reload().

I've tried to also reload window.location using ipc and it's the same result.

Is there a way to refresh the webview content will maintaining injected event listeners?

**Comment by zcbenz** [comment]
It is a bug that `preload` script doesn't load after reloading, it looks similar to #1169.

**Comment by zcbenz** [comment]
@jofan What's the version of atom-shell were you using?

**Comment by tagisen** [comment]
@zcbenz We are using atom-shell version 0.20.6

**Comment by zcbenz** [comment]
@tagisen You should use the latest 0.21.2, which has fixed this.

**Comment by tagisen** [comment]
@zcbenz We did update atom-shell and we can see that bug is partly fixed. We don't the error mentioned above anymore, but when we run <webview>.reload() we get a empty <webview> with no content whatsoever and the preload script is not included.

**Comment by zcbenz** [comment]
@tagisen It sounds like a bug to me, does it happen for every website, or just some of your pages?

**Comment by tagisen** [comment]
@zcbenz it seems its just our content. We are loading HTML content into the webview. The aim is to load a html project available on your local files. But it seems that it works fine if I run reload and there is a website loaded via URL into the `<webview>`.

**Comment by zcbenz** [comment]
@tagisen Is it possible for you to narrow down which part of the HTML content may cause the problem? Otherwise there is no way for me to look into it.
