### ISSUE TITLE
Releases page - different downloads

### ISSUE THREAD

**Issue by xfq** [atom/atom-shell#1201]
In the releases page (https://github.com/atom/atom-shell/releases), there are two zip files for each platform in a release, one with `symbols` in the file name and one without. I'm not sure what are the differences between the two, perhaps the "symbol" versions contain extra debugging information? Whatever it means, I think it should be mentioned in `README.md`.

Maybe a link to `docs/tutorial/using-selenium-and-webdriver.md` or a short description for `chromedriver` downloads is also needed (in `README.md`).

**Comment by zcbenz** [comment]
The ones with `-symbols` in their filenames are purely debugging symbols, which are usefully to generate a meaningful stack trace from uploaded crash reports.

I agree we should mention it in README.
