### ISSUE TITLE
BrowserWindow lacks move and resize events?

### ISSUE THREAD

**Issue by shrewdlogarithm** [atom/atom-shell#1207]
Certainly I can't seem to find them - and they seem essential for an app to save the size/position of a Window for a user??

DOM Window has a resize event but that's not really ideal and there's no way to track a window moving otherwise?

p.s. I took a peek at the source with a view to adding them myself but I lack the skills, sadly, so over to someone a bit more savvy with the C++?

**Comment by zcbenz** [comment]
Move and resize events are not supported yet. If you want to save window's position, the usual way is to save it when window is closed, not when it is moved or resized.

**Comment by shrewdlogarithm** [comment]
I realise I can do that - historically it's been better to track move/resize tho, because the way maximize/minimize works on some OSes can lead to the size/position of the window being reported wrongly at close time

In theory, you just first check a Window is hidden and if so, show it.  You then then check if ti's maximised or minimized and if so restore it and THEN you can measure it before closing it - and the way that works on some OSes can lead to wrong results being saved in my experience.

I'll try it and report back if I find any issues tho
