### ISSUE TITLE
Add an option to expose `global.gc()`.

### ISSUE THREAD

**Issue by bolinfest** [atom/atom-shell#1213]
Node accepts the `--expose-gc` flag to make `global.gc()` available. I am trying to write some tests using `WeakMap` to see if I have memory leaks, so having access to `global.gc()` would be really useful.

Is there any way to enable this today and/or how hard would it be to add?

**Comment by deepak1556** [comment]
v8 related flags can be enabled by https://github.com/atom/atom-shell/blob/master/spec/static/main.js#L9 but it actually didnt expose gc() . is it because v8 was already initialised by gin in libchromium, @zcbenz thoughts ?

**Comment by zcbenz** [comment]
@deepak1556  That code is in the specs window.

@bolinfest You can use the line referenced by @deepak1556 to expose `gc`.

**Comment by bradisbell** [comment]
Could someone please elaborate on how to actually expose global.gc() in Electron?  The link above doesn't seem to reference anything useful anymore.

**Comment by danburzo** [comment]
@bradisbell you need to run Electron with `--js-flags="--expose-gc"` to enable the `global.gc()` method.

**Comment by cbroad** [comment]
This is only about 5 years late, but for posterity the following can be done without any command line args.  Obviously the "--expose-gc" command line argument is implied in the first command.
`
	require("v8").setFlagsFromString('--expose_gc');
	global.gc = require("vm").runInNewContext('gc');
`
