### ISSUE TITLE
white screen when.setKiosk is call

### ISSUE THREAD

**Issue by gliurn** [atom/atom-shell#1226]
hi, when i run my app, i trie to show it only when he 's completely load. so i set show to false when i create the browserWindow and i use remote.getCurrentWindow().setKiosk(true); when i catch event 'did-finish-load in the render side . but for 1s i got a white screen. Do yu know how to fix this?

Thanks

**Comment by zcbenz** [comment]
We have some problems with kiosk mode, I'm merging this to #1054.

**Comment by gliurn** [comment]
i ve the same error with setFullScreen, i use an X Window to show my atom-shell app so i don t really need kiosk mode but this white screen really annoy me. a way to avoid it?

**Comment by zcbenz** [comment]
On Linux kiosk mode is the same with fullscreen mode. I don't know a way to avoid it.

**Comment by gliurn** [comment]
ok, thanks for this information, i didn t know that but this code give the same thing too:

in main.js:
app.on('ready', function() {
  // Create the browser window.
  var atomScreen = require('screen');
  var size = atomScreen.getPrimaryDisplay().workAreaSize;
  mainWindow = new BrowserWindow({ width: size.width, height: size.height,frame: false, show: false });
mainWindow.loadUrl('file://' + __dirname + '/index.html');		 												
});      

and in index.html:
 onload = function() {
            var loadstop = function() {
		remote.getCurrentWindow().show();
            };
            webview.addEventListener("did-stop-loading", loadstop);     			
        };

even this code give me the white screen
