### ISSUE TITLE
Keep Chromium's v8 & io.js' v8 in sync?

### ISSUE THREAD

**Issue by mzgol** [atom/atom-shell#1227]
Currently Atom runs on io.js but includes v8 3.30 from Chromium 40. Since io.js now follows v8 versions included in latest stable Chrome, how about making those versions match to prevent unpleasant surprises? That would mean including v8 4.1 for now (as it's included in latest io.js & Chrome 41) and updating io.js & Chrome at the same time each 6 weeks.

**Comment by paulcbetts** [comment]
This is already the plan afaik, they're just out of sync until Chrome 41 lands in Atom Shell (which is very soon)

**Comment by zcbenz** [comment]
Once the [upgrade to Chrome41](https://github.com/brightray/libchromiumcontent/pull/94) is done we will be synced with latest io.js.
