### ISSUE TITLE
webContents.send nullifies repeating instance of an object

### ISSUE THREAD

**Issue by teleclimber** [atom/atom-shell#1229]
If I have this Browser-side:

```
var test_obj = [];
var a = { "yee":"haw!" };
test_obj.push(a);
test_obj.push(a);
myWindow.webContents.send( 'test-data', test_obj );
```

..and I place this in the Renderer:

```
ipc.on( 'test-data', function(data) {
	console.log( 'test data, received:', data );
});
```

I would expect something like:

```
[ { "yee":"haw!" }, { "yee":"haw!" } ]
```

Instead I get:

```
[ { "yee":"haw!" }, null ]
```

Note that `JSON.stringify` works as expected so it seems natural that `webContents.send` would behave the same.

Thanks.

**Comment by zcbenz** [comment]
This behavior is intended to prevent parsing recursive objects.

**Comment by teleclimber** [comment]
This behavior -- silently altering message data -- is pretty bad.

I understand that we don't want to parse recursive objects. But this isn't a recursive object. At least it's not an object that is problematic to parse. If it were cyclical then I would completely understand, but it's not.

In any case, if Atom-Shell can't deal with the message data as it is, why would it **silently** alter it?? It seems that throwing an error would be far more appropriate than silently changing my data structure.
