### ISSUE TITLE
determining sender window of IPC messages in browser

### ISSUE THREAD

**Issue by maxogden** [atom/atom-shell#1231]
I'm wondering if it's possible to know which window sent an IPC message.

For example, say I create 2 `browser-window` instances, and they both call `ipc.send('foo', 'bar')`.

In the browser, is there any way to know which window triggered the `ipc.on('foo', cb)` events that get triggered?

Maybe you should be able to do `webContents.on` in addition to `webContents.send` to be able to get messages from a specific window

**Comment by paulcbetts** [comment]
Why not just do this yourself by sending extra information in the send message?

**Comment by maxogden** [comment]
@paulcbetts thats what I'm doing now (https://github.com/maxogden/find-data/blob/master/client.js#L7-L10, https://github.com/maxogden/find-data/blob/master/client.js#L26-L32) but I figured this functionality might be something core-worthy

**Comment by zcbenz** [comment]
The `event.sender` references to the WebContents that sent the message.

**Comment by trusktr** [comment]
> Why not just do this yourself by sending extra information in the send message?

Because we're lazy. It could be solved in the API once and for all.
