### ISSUE TITLE
segmentation fault when creating new window inside close event of other window

### ISSUE THREAD

**Issue by maxogden** [atom/atom-shell#1233]
I experienced this when hacking on https://github.com/maxogden/find-data/ just now but made a small test case for it:

https://gist.github.com/maxogden/b22a3ba5f7b425bc7c2e

```
~/Desktop 🐈  atom-shell test.js
[39501:0310/163228:WARNING:dns_config_service_posix.cc(151)] dns_config has unhandled options!
[39503:0310/163228:INFO:renderer_main.cc(211)] Renderer process started
loaded
closing and creating new window...
/usr/local/bin/atom-shell: line 2: 39501 Segmentation fault: 11  "/Users/maxogden/src/js/atom-shell/dist/Atom.app/Contents/MacOS/Atom" "$@"
```

I probably shouldn't be creating windows inside close (since its kind of like an infinite loop), and moving `loadPage()` from inside the `close` event into the `did-finish-load` event indeed fixes the segfault, but I thought I should report the segfault anyway

**Comment by zcbenz** [comment]
This crash happens because your BrowserWindow object is garbage collected, and the crash is tracked at #1112.
