### ISSUE TITLE
disable "unexpectedly quit" reopen dialog?

### ISSUE THREAD

**Issue by maxogden** [atom/atom-shell#1234]
during dev if I crash atom-shell, and run it again, it gives me this:

![screen shot 2015-03-10 at 4 39 14 pm](https://cloud.githubusercontent.com/assets/39759/6587645/30a6e4b6-c744-11e4-900e-3aa786051096.png)

this seems like a hardcoded Atom editor feature. is there any way to disable it?

**Comment by zcbenz** [comment]
This is a feature of OS X, you can turn it off for your app:
http://stackoverflow.com/questions/20226802/disable-the-last-time-you-opened-it-unexpectedly-quit-while-reopening-window

**Comment by maxogden** [comment]
@zcbenz thanks for the tip. Following the advice in that thread didn't work for me until I also deleted `~/Library/Saved Application State/com.github.atom-shell.savedState`, now it launches without the dialog after crashes :)
