### ISSUE TITLE
check internet connection

### ISSUE THREAD

**Issue by gliurn** [atom/atom-shell#1236]
hi, i would like to refresh my webview when i lose (or as long as i didn t have) internet connection, how could i check it on my webview?

Thanks for your help

**Comment by bwin** [comment]
http://caniuse.com/#feat=online-status

**Comment by gliurn** [comment]
that's not an help, and as said in your link navigator.online report always true now, so it s useless

**Comment by mcdermed** [comment]
```Early versions of Chrome and Safari always reported "true" for navigator.onLine```

We're using Chrome 40 currently which isn't an early version of chrome.

**Comment by gliurn** [comment]
ok, i tried this simple code:

if (navigator.onLine) {
						  alert('online');
						} 
					else {
						  alert('offline');
						}

but it show me "online" even if i m offline

**Comment by paulcbetts** [comment]
`navigator.onLine` will tell you if at least one of your network interfaces is up, which does not perfectly correlate to "I have an Internet connection and it works". `navigator.onLine` is a hint that it's worth checking as to whether the Internet works.

**Comment by zcbenz** [comment]
Atom Shell uses Chromium's code for `navigator.onLine`, so it is recommended to report it to Chromium  if it doesn't work for you:
https://code.google.com/p/chromium/issues/list

**Comment by cerfuck** [comment]
I faced with same problem and find solution like this:
```
window.webContents.on('did-fail-load', (event: Event, errorCode: number, errorDescription: string, validatedURL: string, isMainFrame: boolean) => {
      if (errorDescription === 'ERR_INTERNET_DISCONNECTED') {
        // your code
      }
});
```

**Comment by zakawat** [comment]
@vadim-ch where should I put this code ...?

It didn't worked for me in `main.js` nor in `renders.js`

**Comment by xudafeng** [comment]
@elkwood @zcbenz @zsubzwary 

navigator.onLine keeps returning true, leading to inaccurate solutions

https://github.com/electron/electron/issues/11290#issuecomment-670828109
