### ISSUE TITLE
OSX Crash when creating a Tray icon

### ISSUE THREAD

**Issue by shrewdlogarithm** [atom/atom-shell#1237]
Using the latest (0.21.3) Darwin release, I'm getting an app crash if I try to create a Tray icon

````
var Tray = require("tray")
global.tray = new Tray(path.join(__dirname, "images/gtray.png"));
````

Is the offending code - png exists - NOT using asar - suspect this is a pathing issue tho???

Crash looks like this (no idea how to cut/paste/save that on OSX) - and yes, that's a Hackintosh cos I don't own a Mac - but remove those 2 lines and it works OK (as does the default_app)

https://dl.dropboxusercontent.com/u/1164739/osxcrash.png

Error is a generic 'Error (1000) creating CGSWindow' - NSException NSInternalInconsistencyException etc.

If I can provide more details and someone more OSX savvy can tell me how to get the whole report/dump - that would be awesome - and perhaps how to path to Tray

Demo project here

https://github.com/shrewdlogarithm/atom-shell-crash-demo

**Comment by bwin** [comment]
Just a thought: Try it without setting it to a global object. `tray = new Tray( ...`

**Comment by shrewdlogarithm** [comment]
Doesn't fix it here - I removed the path.join(__dirname bit and got a
different error entirely (not a crash, a JS error) but I cannot seem to
fathom what directory it wants (and I think the crash happens when it
actually DOES find the file!) ??

**Comment by bwin** [comment]
From reading your answer I'm not sure if you knew what i meant:
~~global.~~tray = new Tray(path.join(__dirname, "images/gtray.png"));
If you've tried that, please ignore this comment.

**Comment by bwin** [comment]
This doesn't have to do with anything, just wanted to let you know: In your `atom-shell-crash-demo` in main.js on line 17 you have `... true: false});`

**Comment by shrewdlogarithm** [comment]
Fixed the silly true: false thing - still unsure how to proceed with the Tray tho, I'm pretty sure the crash is because I have the RIGHT path to the icon (and without it, no Tray?)

**Comment by deepak1556** [comment]
thats cause of NSApplication event loop wasnt setup, initialise either on `will-finish-launching` or `ready` . @zcbenz should this be a bug ?

```
app.on('will-finish-launching', function() {
	global.tray = new Tray(path.join(__dirname, "images/gtray.png"));
})
```

**Comment by zcbenz** [comment]
@deepak1556 We should throw error when users try to create `Tray` before `ready` event, like `BrowserWindow`.
