### ISSUE TITLE
Webview persists data across sessions

### ISSUE THREAD

**Issue by marcus433** [atom/atom-shell#1244]
The atom-shell webview element is storing cookie data. Shouldn't all cookie data be removed as soon as the webview is destroyed? Example: opening google login in a webview, when opening the webview again in a later session it still shows the suer as logged in. Would it be possible to add an option for this, if it isn't an error?

**Comment by mark-hahn** [comment]
What you want are session cookies but I don't think any browser allows you
to override what the website sends.

**Comment by mark-hahn** [comment]
A better answer for your request:  Inject some javascript that runs when
the webview opens.  Put code in to erase all cookies.  Google "clearing all
cookies with javascript".

**Comment by marcus433** [comment]
I attempted that however HTTP cookies can't be overwritten. I'm looking for something more like "incognito" for the web view element



—

**Comment by zcbenz** [comment]
We currently don't have any session related APIs, it is currently tracked at #959.
