### ISSUE TITLE
Error Opening App when using socksv5 module

### ISSUE THREAD

**Issue by mattcollier** [atom/atom-shell#1247]
I need to access the socks proxy provided by tor in my app.  I have working io.js code utilizing the socksv5 module:  https://github.com/mscdex/socksv5

Atom-shell v0.21.3

here is a most basic app demonstrating the issue: https://github.com/mattcollier/atomsocks

The error is : 
Error opening app
The app provided is not a valid atom-shell app, please read the docs on how to write one:
https://github.com/atom/atom-shell/tree/master/docs

I'm open to alternative modules that provide socks proxied DNS request as well.

**Comment by bwin** [comment]
What OS are you on? Also, please run your app from the comand line and paste the output here.
(Best to wrap it in 3 backticks \`\`\` to prevent it from being interpreted as markdown by github.)

**Comment by mattcollier** [comment]
Debian Linux 64 bit

```matt@matt-Lenovo-G560-Jessie:~$ atom-shell nox_test
[13255:0314/193511:ERROR:browser_main_loop.cc(164)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
Gtk-Message: Failed to load module "canberra-gtk-module"
Error opening app
The app provided is not a valid atom-shell app, please read the docs on how to write one:
https://github.com/atom/atom-shell/tree/master/docs
```

**Comment by bwin** [comment]
Ok, so the actual error is `Failed to load module "canberra-gtk-module"`.

Could you try installing libcanberra-gtk3-module with `apt-get install libcanberra-gtk3-module`?
If this doesn't fix it, I'll try your sample app.

**Comment by mattcollier** [comment]
Actually, I always get that canberra-gtk-module error.  If you run the app you'll see that if you run it with the require('socksv5'), it doesn't work, but if you comment that line, it runs properly.

**Comment by bwin** [comment]
The actual error is:
```
A JavaScript error occured in the browser process
Uncaught Exception:
Error: Cannot find module 'ipv6'
    at Function.Module._resolveFilename (module.js:351:15)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/home/winkler/Arbeitsfläche/as0.21.3/resources/default_app/node_modules/socksv5/lib/utils.js:2:12)
    at Module._compile (module.js:475:26)
    at Object.Module._extensions..js (module.js:493:10)
    at Module.load (module.js:370:32)
    at Function.Module._load (module.js:325:12)
    at Module.require (module.js:380:17)
```

Solution: Install `ipv6` with `npm i -S ipv6`.
I'm not sure why it's missing...

**Comment by mattcollier** [comment]
Thanks!  Can you tell me how you got the more detailed error message?

**Comment by bwin** [comment]
The "Error opening app. The app provided blah yada yada" msg comes from the default_app. I just replaced it (resources/default_app) with your app.

**Comment by mscdex** [comment]
FWIW `ipv6` is bundled with `socksv5`. It's been awhile but I believe the reasoning is that the `ipv6` repo contained fixes not published to npm (in quite some time).

**Comment by bwin** [comment]
@mscdex Hi, was just going to open an issue over at your repo...

**Comment by mattcollier** [comment]
Well, I guess I ran afoul when I specified the git repository for socksv5 in my own dependencies.
@bwin, I don't follow what you said about how you received the error message.  Can you give a more detailed explanation?  I really appreciate your prompt assistance!

**Comment by bwin** [comment]
If you don't pass any parameters to `atom` you see it the default_app in action on the "Welcome to Atom-Shell" window.
Atom-shell always runs the app in `resources/default_app`. The "default" default_app does
- load the app in `resources/app` or `resources/app.asar` if there is one of these
- load the app specified as a command line arg unless there are no cli args
- if no app is found, then show "itself"
- it also catches errors and displays a nonsense "not a valid atom-shell app" msg instead.
(Maybe it does more or the order is slightly off, haven't looked at it in a while. It's tiny, have a look at it if you're interested.)

What I did was replacing the contents of `PATH/TO/ATOM-SHELL/resources/default_app` with your app, so errors are thrown (and not catched by the original default_app). Then you have to run atom-shell from the command line (`./atom`) to see the log output.

**Comment by zcbenz** [comment]
The `default_app` would complain about invalid app when there is a module not found error, we should probably fix that.

I'm closing this since it has been solved.

**Comment by bwin** [comment]
@mscdex Just out of curiosity: how did this get to your attention (so fast)?

**Comment by mscdex** [comment]
@bwin Someone on IRC brought it to my attention the other day.

**Comment by bwin** [comment]
Thanks for the quick responses.
