### ISSUE TITLE
disable chromium WARNING messages?

### ISSUE THREAD

**Issue by maxogden** [atom/atom-shell#1251]
I get warning messages like this on STDERR:

```
[1320:0316/152451:WARNING:dns_config_service_posix.cc(151)] dns_config has unhandled options!
```

Is there any way to turn this off? The only thing I could find is the `--disable-logging` flag here http://peter.sh/experiments/chromium-command-line-switches/ but I think thats for the Chromium.app browser and not libchromium/content

**Comment by bwin** [comment]
I'm interested in this, too. Although in my use-case these msgs aren't user-facing, they add noise when debugging my app.
(Just to be clear, I also just want a flag or something to turn them off, not to turn them off completely.)
