### ISSUE TITLE
how to terminate app if intercepting will-quit

### ISSUE THREAD

**Issue by maxogden** [atom/atom-shell#1252]
I have a use case where I open and close multiple windows, and don't want the entire app to terminate when all windows are closed (this is the default behavior).

I am following [this section](https://github.com/atom/atom-shell/blob/master/docs/api/app.md#event-will-quit) of the docs and calling `preventDefault` on the `will-quit` event, which successfully keeps my app from automatically quitting when there are no open windows.

However, I can't figure out how to actually quit the app now. Calling `app.quit()` and `app.terminate()` both cause the `will-quit` event to fire, which does nothing.

Is there a way to bypass the `will-quit` event and make the app terminate, or some other way to prevent the 'terminate app if no windows are open' default?

**Comment by bwin** [comment]
How about a var `allowQuit= false` and in your `will-quit`-handler only call `preventDefault()` if `!allowQuit`. And when you finally want to quit, set `allowQuit = true`.
In my head this makes sense, but I'll have to try it out. (I can only test on linux/windows BTW.)

**Comment by maxogden** [comment]
@bwin oh man, that totally works! so simple, I am an idiot for not thinking of that :P

**Comment by bwin** [comment]
At least on windows this would work. Not calling `app.quit()` on `window-all-closed` would also work.
~~I think you're running into OSX-related problems here. I think I remember an issue that stated something like "can't quit app on osx" or something, but I can't seem to find it.~~
Ok, this already works for you. Even better.

> so simple, I am an idiot for not thinking of that :P

I feel like that half of the time... :smiley:
