### ISSUE TITLE
Element's title is cropped, in Linux

### ISSUE THREAD

**Issue by joaomoreno** [atom/atom-shell#1263]
Notice how the tooltip of the `hello` element is rendered a bit off the viewport.

![screen shot 2015-03-19 at 15 42 06](https://cloud.githubusercontent.com/assets/22350/6732860/b837dac8-ce4e-11e4-8d4e-cd8659667d7c.png)

When the window is maximised this doesn't happen. It looks like the screen's bounding box is being used to layout the tooltip; instead of the web view's bounding box.

```html
<!DOCTYPE html>
<html>
  <body>
    <div
      style="position: fixed; bottom: 10px; left: 0; border: 2px solid black;"
      title="world">hello</div>
  </body>
</html>
```

**Comment by zcbenz** [comment]
We currently have some issues displaying native tooltips, I'm merging this to #877.
