### ISSUE TITLE
ship application with plugins included

### ISSUE THREAD

**Issue by DogsForArms** [atom/atom-shell#1264]
Hello friends!  
I am trying to have my application ship with NPAPI flash for mac osx as well as windows.  Is it possible to do this in atom-shell?  I have done a little bit of searching and seen that "Add 'extra-plugin-dirs' option." looks promising but I am not entirely sure how to use it.  I have tried the following to no avail with both extraPluginsDirsValue1 and extraPluginsdirsValue2

in my main.js something like this:
...
var mainWindow = null
app.on('ready', function() {

  var extraPluginsDirsValue1 = 'file://' + __dirname + '/plugins/FlashPlugin.plugin'
  var extraPluginsDirsValue2 = 'file://' + __dirname + '/plugins/'

  //for mac it is a .plugin i think
  mainWindow = new BrowserWindow({...., 'web-preferences': { 
      'plugins': true, 
      'extra-plugins-dirs': [extraPluginsDirsValue1]
    }
  })
...

})

I have assumed that extra-plugins-dirs value is an array because of what I have read in the commit history here
https://github.com/atom/atom-shell/commit/1fbebb0da76d22be72ebf944bef135d6360f723b

Thank you very much for your time.

**Comment by zcbenz** [comment]
You need to use real file path without `file://`.

**Comment by DogsForArms** [comment]
Thank you very much.

**Comment by paulcbetts** [comment]
This works, though be aware that to legally ship Flash with your app you need to sign some Flash Redist paperwork
