### ISSUE TITLE
Implementing non-US Keyboard support

### ISSUE THREAD

**Issue by ythej** [atom/atom-shell#1266]
Hi,

I am little new to Atom. I am trying to find what is the root cause for improper working of Atom with non-US keyboard layouts. By doing some research came to know that Atom uses webKit. And also I came to know that by using <a href="https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key">KeyboardEvent API</a> there will no issue's working with non-US Keyboard layouts. But I know that webkit doesn't support.

Could anyone please help me with where the problem is taking place exactly in the code ? And also is it recommended to fix this by patching chromium or its better to fix by creating a package for Atom which contains keybinding files for every keyboard layout and the required keybinding is loaded from there ?

Thank you.

**Comment by zcbenz** [comment]
You can find related discussions in [Atom's repo](https://github.com/atom/atom).

**Comment by ythej** [comment]
@zcbenz , Actually one of the solutions to fix this is mentioned as patching chromium. I thought it is right place to discuss about it than atom.

**Comment by zcbenz** [comment]
@ythej I remember there is a Chromium bug on non-US keyboard support, you can have a search at https://code.google.com/p/chromium/issues/list. But fixing it on Chromium's side seems very unpractical to me.

**Comment by ythej** [comment]
@zcbenz , okay, Thank you :)
