### ISSUE TITLE
OS X Notification with atom-shell

### ISSUE THREAD

**Issue by noraesae** [atom/atom-shell#1269]
Hi,

I'm trying to show OS X notification with atom-shell.

```js
new Notification('hello');
```

The code above works fine when I run the Atom app with double-clicking the app icon from Finder and drag the working directory into the app. The problem is that when I run atom-shell with `atom-shell .` from terminal, notification doesn't work.

Anyway to make it work?

Thanks in advance.

**Comment by zcbenz** [comment]
Are you using `tmux` or `screen` under terminal?

**Comment by noraesae** [comment]
Exactly. Using `tmux`. Does it affect the behaviour?

**Comment by zcbenz** [comment]
It is known to make some UI related APIs not working, see also:
https://github.com/atom/atom-shell/issues/916#issuecomment-68567844

**Comment by noraesae** [comment]
Oh, now I see. Thank you for the quick answer :+1:

**Comment by noraesae** [comment]
Thanks to your advice, I searched a bit about `tmux` and user namespace issue, and I added the following line in `.tmux.conf` and it worked perfectly.

```
set-option -g default-command "reattach-to-user-namespace -l zsh"
```

Thank you!
