### ISSUE TITLE
Support for Yosemite dark menu bar icons in Tray

### ISSUE THREAD

**Issue by maxogden** [atom/atom-shell#1271]
e.g. here's the call to check for it https://github.com/shpakovski/Popup/blob/62e265afdbb378c6fa818174d493c0688fc2ac17/Popup/StatusItemView.m#L34

basically you want black and white versions of your menu bar icon, and you want the app to load the correct one based on the users setting

for example here's an atom-shell app with a black icon running on the dark menu bar, next to an icon with a 'light' icon:

![screen shot 2015-03-20 at 11 42 54 am](https://cloud.githubusercontent.com/assets/39759/6758576/54c5df64-cef6-11e4-8107-c4ef9aff44ba.png)

and here it is running on the normal light menu bar:

![screen shot 2015-03-20 at 11 42 46 am](https://cloud.githubusercontent.com/assets/39759/6758577/57d2eeb8-cef6-11e4-8340-2abc2a5c6851.png)

**Comment by zcbenz** [comment]
You can achieve it by marking the image as template image:
https://github.com/atom/atom-shell/blob/master/docs/api/native-image.md#template-image
