### ISSUE TITLE
crash-reporter phones home (54.249.141.255)

### ISSUE THREAD

**Issue by jmatsushita** [atom/atom-shell#1278]
That's really not polite.

https://github.com/atom/atom-shell/blame/master/docs/api/crash-reporter.md#L20

**Comment by bwin** [comment]
It's just a default value and it's mentioned in the docs. I think it's fine that way. (Also the whole crash-reporter is optional.)

**Comment by paulcbetts** [comment]
@jmatsushita Native crashes (which is what this reports) are not the same as JS crashes, and generally don't have the privacy concerns you're worried about, either from a developer perspective or from the user's perspective. Here's more info:

https://msdn.microsoft.com/en-us/library/windows/desktop/ms680369%28v=vs.85%29.aspx

**Comment by zcbenz** [comment]
It is optional and explicitly documented, and as @paulcbetts said it leaks nothing about your privacy, so I think it is totally fine.

**Comment by jmatsushita** [comment]
Thanks for taking the time to explain. Just to make sure I understand, when a developer does nothing (i.e. does not require a crash-reporter to start), then nothing will be sent out? However, if they require a crash-reporter, and start it, then they would have to "forget" to override the default value for the crash reports to be sent to ```http://54.249.141.255:1127/post```.

Is that right?

**Comment by zcbenz** [comment]
Right.
