### ISSUE TITLE
Does the product_name have any relevance on Win?

### ISSUE THREAD

**Issue by Wortex17** [atom/atom-shell#1280]
When building atom-shell with custom GYP_DEFINES it is possible to define a project and a product name.
The resulting executable carries the project name (all build and ouput file related to it do too) - at leats on windows.
TBH i only skimmed through the atom.gyp, but my first impression is that the product_name is only ever used under linux/osx environments.

Can you elaborate on what these two definitions actually stand for?

**Comment by zcbenz** [comment]
`project_name` is like the executable file's name of your app, and `product_name` will be used as your app's name. It is totally fine to use the same name for both, but sometimes people would prefer a short lower-cased name for `project_name`.

As an example, in Atom editor, `project_name` is `atom` and `product_name` is `Atom`.

**Comment by Wortex17** [comment]
I see, thanks ^^
