### ISSUE TITLE
Use GYP_DEFINES to set all branding information

### ISSUE THREAD

**Issue by Wortex17** [atom/atom-shell#1281]
Currently, when rebuilding (& rebranding), using GYP_DEFINES only really affects the outcoming executables name (and maybe something else that I do not know about on non-win platforms, see #1280 ).

I can only speak for windows here, but the resulting executable still has default branding information incorporated in its resource data.

See this screenshot of the exe's properties (sorry, german Windows, but i guess you know the fields).
![Properties](https://cloud.githubusercontent.com/assets/170627/6769155/ee62a2d4-d08f-11e4-990e-a87d57b6fbbc.PNG)

Thism windows resource data is defined [in this file](https://github.com/atom/atom-shell/blob/master/atom/browser/resources/win/atom.rc).

Would it be posible to generate this file through the bootstrap script, so it can incorporate custom settings?
I'm thinking of 
* using already existing GYP_DEFINES product_name and project_name
* additional GYP_DEFINES like corporate/copyright information etc.

Otherwise this would, of course, need rigging either previously to the build (editing the rc file) or after the build (using rcedit)

**Comment by paulcbetts** [comment]
Both Atom and Slack use rcedit to rig this after-the-fact, as well as the EXE's icon

**Comment by zcbenz** [comment]
It sounds like a good idea, we should replace all hard-coded `atom` strings with `product_name` and `project_name`.

I'm merging this to #686.
