### ISSUE TITLE
"auto-update" dosen't work properly on both Windows and Mac.

### ISSUE THREAD

**Issue by w88975** [atom/atom-shell#1283]
my auto-update code。

```javascript

var Remote = require('remote');
var app = Remote.require('app');
var autoUpdater = Remote.require('auto-updater');

Polymer({
    version: '',

    created: function () {
        this.version = app.getVersion();
        this.result = '';
        autoUpdater.setFeedUrl('https://atom.io/api/updates?version=0.16');

        console.log('created');
        autoUpdater.on('checking-for-update', function() {
            console.log("checking-for-update");
        });

        autoUpdater.on('update-available', function() {
            console.log("update-available");
        });

        autoUpdater.on('update-not-available', function() {
            console.log("update-not-available");
        });

        autoUpdater.on('update-downloaded', function() {
            console.log(" update-downloaded");
        });

        autoUpdater.checkForUpdates();
    },
});

```

on Mac OSX  the terminal output this log:

```console

Could not get code signature for running application, application updates are disabled: Error Domain=NSOSStatusErrorDomain Code=-67062 "The operation couldn’t be completed. (OSStatus error -67062.)" 

```

on windows:

do not output anything.

**Comment by w88975** [comment]
@zcbenz

**Comment by zcbenz** [comment]
On Mac your application has to be signed otherwise [Squirrel](https://github.com/Squirrel/Squirrel.Mac) would not continue.

The Windows auto-updater is tracked at https://github.com/atom/atom-shell/issues/939.

**Comment by michaeljcalkins** [comment]
@zcbenz Can you recommend an example or tutorial on this?  I'm just getting started with it all.

**Comment by Janneman84** [comment]
I just got an empty error in the error event, no message, just 'Error'. Turns out you need to do setFeedURL() before setting the event listeners, or else it won't work... Above example does this right.

It would be useful if the documentation was more clear about this.

**Comment by anisnair** [comment]
I am able to access my endpoint from the browser.
But I think the autoupdater is not able to do the same.

It throws the below exception.
`"err":{"message":"Command failed: 4294967295\nSystem.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)`

I though this would be because my endpoint is set to `localhost`.
But tried uploading the endpoint to a live server. And still no luck

It returns the same exception.

**Comment by adrianscripcariu** [comment]
hello anishnair02 I have the same error Did you find a soultion?

**Comment by anishnair02** [comment]
No adrianscripcariu. Please let me know when you fix this. And if I do, I will update you.

**Comment by adrianscripcariu** [comment]
Hello anishnair02. It seems to be an url error from the server... if you have the server look at the  incoming requests and watch the url that is comming from electron... that was my problem, but now I have another one, the server return the json but in app I have this error 
System.Exception: Invalid release entry: {"url":"localhost:3000/releases/wind/1.0.4/MyApp.zip";}

**Comment by MarshallOfSound** [comment]
@adrianscripcariu You appear to have a stray semicolon in that JSON output

**Comment by adrianscripcariu** [comment]
![error](https://cloud.githubusercontent.com/assets/21836226/19270537/3443b032-8fc9-11e6-9b7b-11e6bf5701ea.png)

**Comment by adrianscripcariu** [comment]
This is how it looks like in electron

**Comment by MarshallOfSound** [comment]
You appear to be missing a lot of the required schema

https://github.com/Squirrel/Squirrel.Mac#update-json-format

**Comment by adrianscripcariu** [comment]
Can you please help me uith a prebuild squierrel server :D

**Comment by adrianscripcariu** [comment]
I've tried this guide https://medium.com/@svilen/auto-updating-apps-for-windows-and-osx-using-electron-the-complete-guide-4aa7a50b904c#.x6s289n1h

**Comment by adrianscripcariu** [comment]
and the server code
'use strict';
const fs = require('fs');
const express = require('express');
const path = require('path');
const app = express();

app.use(require('morgan')('dev'));

app.use('/updates/releases', express.static(path.join(__dirname, 'releases')));

app.get('/updates/latest', (req, res) => {
  const latest = getLatestRelease();
  const clientVersion = req.query.v;

  if (clientVersion === latest) {
    res.status(204).end();
  } else {
    res.json({
      url: `${getBaseUrl()}/releases/darwin/${latest}/MyApp.zip`
    });
  }
});

let getLatestRelease = () => {
  const dir = `${__dirname}/releases/darwin`;

  const versionsDesc = fs.readdirSync(dir).filter((file) => {
    const filePath = path.join(dir, file);
    return fs.statSync(filePath).isDirectory();
  }).reverse();

  return versionsDesc[0];
}

let getBaseUrl = () => {
  if (process.env.NODE_ENV === 'development') {
    return 'http://localhost:3000';
  } else {
    return 'http://download.mydomain.com'
  }
}

app.listen(process.env.PORT, () => {
  console.log(`Express server listening on port ${process.env.PORT}`);
});

**Comment by MarshallOfSound** [comment]
@adrianscripcariu Personally I use https://github.com/GitbookIO/nuts

**Comment by adrianscripcariu** [comment]
Hello, I downloaded and installed npm install, but I don;t really understand what i have to do next :(

**Comment by zeke** [comment]
@adrianscripcariu check out the docs at https://nuts.gitbook.com/deploy.html

**Comment by anishnair02** [comment]
Hello adrianscripcariu,

I could get the windows electron app auto-updated.

Here's what I did.

1. Set the feedURL to something like this: `http://localhost/downloads/yourapp-updates/`
This is the link to an empty directory on my localhost.
The app version is set to 1.0.0

2. Create the installer using `npm run dist`
This creates the `dist directory->win` in the project folder which contains the following
- `RELEASES`
- `YourApp-1.0.0-full.nupkg`
- `YourApp Setup 1.0.0(Application file)`
You need the `YourApp Setup 1.1.0` file to install it the first time.

3. Now we have the app installed in the windows machine. You may also want to check the app version in `Control Panel -> Programs and Features`. And it should show `1.0.0`

4. Now in the code(Project folder).
Make the necessary changes(to test it, I just changed the background color of a div)
Set the version to a higher number from the previous version. So I set it to `1.1.0`
Run `npm run dist`
It should now have the following files in the `dist directory->win`
- `RELEASES`
- `YourApp-1.1.0-full.nupkg`
- `YourApp Setup 1.1.0(Application file)`
Note the `nupkg` and the `application` file name is different now(it's 1.1.0, earlier it was 1.0.0)

5. Copy these three files and paste to the updates directory(http://localhost/downloads/yourapp-updates/)

6. Re-run the installed app(you can use the desktop shortcut created using `electron-squirrel-startup`)

7. The app will auto-update on its own(you should see the changes you made - div color changed)

**Comment by paulcbetts** [comment]
> 1.) Set the feedURL to something like this: http://localhost/downloads/yourapp-updates/

Pro-Tip, anywhere in Squirrel.Windows that you can put a HTTP URL, you can _also_ put just a regular path to a folder. This makes testing updates much much easier, because you can just set your dist folder as the update URL

**Comment by anishnair02** [comment]
Hi,

Yes I am aware about the fact, that regular paths do work for Windows Electron app.
And yes for testing this can be useful.

But after I make the app live to users, I will have to set the path to a directory, which is accessible to everyone. And that's when servers come into picture.
So I will have a path like this maybe: http://updates.mydomain.com/latest/

**Comment by vojtatranta** [comment]
@anishnair02 I wrote an article about Electron Auto Update on Windows along with example repo:  https://blog.avocode.com/blog/get-that-damn-windows-auto-update-working-on-electron
