### ISSUE TITLE
accept-first-mouse does not work on -webkit-app-region: drag

### ISSUE THREAD

**Issue by tommoor** [atom/atom-shell#1286]
If an element has the "-webkit-app-region: drag" css style (such as a title area) then even with "accept-first-mouse" in the window options the first click (and hold) to drag the window does not work. 

Repro steps:
- Create a frameless window with a webkit-app-region: drag
- Focus another window
- Click and hold on the draggable area and try and move the window

**Comment by bwin** [comment]
Cannot reproduce. Please provide the necessary details like Atom-Shell version, operating system version and architecture.

**Comment by tommoor** [comment]
@bwin  Atom Shell 0.22.2 on Mac OSX 10.10.1.

I've tried with and without accept-first-mouse, always-on-top and resizeable.

**Comment by bwin** [comment]
Sorry can't help you there, I don't have a Mac here... (Just wait a little while and someone else will look into it.)

**Comment by zcbenz** [comment]
I can confirm it on Mac, it seems to be caused by `ControlRegionView` not implementing `acceptFirstMouse`.

**Comment by tommoor** [comment]
Impressed gang, a fix in under 24 hours!
