### ISSUE TITLE
I signed my application,but auto-updater output 'did not pass validation'

### ISSUE THREAD

**Issue by w88975** [atom/atom-shell#1292]
same as this issue: https://github.com/atom/atom-shell/issues/905

I use the `Developer ID Application: Company (XXXXXXXXXX)` to sign my app.

- like this:

```console
codesign --verbose --force --sign "Developer ID Application: Company (XXXXXXXXXX)" /Users/kamisama/work/fireball/dev/dist/Fireball.app/Contents/MacOS/Fireball 
```

terminal output log:

``` console

$codesign --verbose --deep --force --sign "Developer ID Application: Nan Wang (SM763GNPZ6)" /Users/kamisama/work/fireball/dev/dist/Fireball.app 
/Users/kamisama/work/fireball/dev/dist/Fireball.app: replacing existing signature
/Users/kamisama/work/fireball/dev/dist/Fireball.app: signed bundle with Mach-O thin (x86_64) [com.fireball-x.fireball]


```

then I used `autoUpdater.checkForUpdates();` to download the `Fireball.zip`.

but the console output this log:
![image](https://cloud.githubusercontent.com/assets/5819351/6820427/e849b50a-d309-11e4-889f-f3156bcec369.png)

I also found  something interesting。

When I do `checkForUpdates();`, 
the folder `Users/kamisama/Library/Application%20Support/com.github.atom.ShipIt/update.Im2trlv/` will download file > `Fireball.zip`

When a software error, the    `Users/kamisama/Library/Application%20Support/com.github.atom.ShipIt/update.Im2trlv/` will be delete.

**Comment by zcbenz** [comment]
According to the error there is something wrong with your signature, I have pushed a change to print more detailed errors, once it gets released we will have better knowledge of it.

**Comment by zcbenz** [comment]
@w88975 Can you try if the latest release of atom-shell gives meaningful error?

**Comment by zcbenz** [comment]
I'm closing this until there is more information provided.

**Comment by rishson** [comment]
Hi @zcbenz, I am also experiencing this behaviour. I'm on Atom-shell 0.22.3, but don't seem to be getting any 'extra' debug info for the failure reason.

My build seems OK, with the signing passing and being verified:

    dist/atom-shell/xxxxx.app: signed bundle with Mach-O thin (x86_64) [com.xxxxx.xxxxx]
    dist/atom-shell/xxxxx.app/Contents/MacOS/xxxxx: replacing existing signature
    dist/atom-shell/xxxxx.app/Contents/MacOS/xxxxx: signed bundle with Mach-O thin (x86_64) [com.xxxxx.xxxxx]
    dist/atom-shell/xxxxx.app/Contents/MacOS/xxxxx: valid on disk
    dist/atom-shell/xxxxx.app/Contents/MacOS/xxxxx: satisfies its Designated Requirement

When I run auto-update, the download works fine but then I get the following in autoupdater.on('error')

    Code signature at URL file:///var/root/Library/Application%20Support/com.xxxxx.xxxxx.ShipIt/update.UdQiF6a/xxxxx.app/ did not pass validation
 
Should there be more error info after your [fix](https://github.com/atom/atom-shell/commit/18044663341701f70528375a799881e087357e01)?

**Comment by zcbenz** [comment]
@rishson That error message is all we can get from Squirrel, it is possible that your way of code signing is not correct, I think you can do code sign by following the links in #1396.

**Comment by Krishnaraj-shankar** [comment]
Error: Code signature at URL file:///Users/krishna-pt5814/Library/Caches/com.Krishnaraj.autoupdater.ShipIt/update.Homm8pL/Autoupdater%20app.app/ did not pass validation: code has no resources but signature indicates they must be present

getting this error while the autoupdater downloads the updated version
