### ISSUE TITLE
URI behavior on Windows

### ISSUE THREAD

**Issue by akrieger** [atom/atom-shell#1298]
Hey atom-shell folks. I'm working with some library code that does intercepts on link clicks and has some behavior based on the a tag href. Unfortunately, parsing the href has some inconsistencies.

Specifically, for an <a href="/default"></a> tag, when handling the click event, <a>.href resolves to file:///C:/default. Passing this into the URI class results in protocol = file, and path = /C:/default.

On Mac/Linux, this behaves fine. uri.protocol = file, but path is = /default as expected, and the library works fine. On Windows, this breaks. I can probably special case the parser to strip /C: if it detects it, but that is... hacky. I feel like inserting the drive letter unnecessarily exposes the fact that the code is running on Windows, and until a click event is passed on the logic should expose the href as being just file:///default.

Is there a way to make the latter behavior the default? I didn't find any sort of configuration option for it. I tried looking in source but didn't find anything either. Or is my thinking just flawed and to be fully consistent with something the drive letter absolutely has to be inserted?

**Comment by thomasjo** [comment]
The current behavior is correct. In no way, shape or form is `file:///C:/default` equivalent to `file:///default`. On Windows, the drive alias (e.g. `C:`) is a crucial part of the path. It's akin to `/` (aka root). If the user has multiple drives, either physical or logical, you absolutely need the drive alias in the URI. How else would you know which drive the path belongs to?

In summary, yes your thinking is flawed. You usually need to handle Windows as a special case.

**Comment by paulcbetts** [comment]
Why are you including the extra slash? Don't you want `file://C:/Default`?

**Comment by akrieger** [comment]
@paulcbetts, on Windows, the full file protocol is file://hostname/drive:/path, but if it's localhost then hostname is omitted and and collapsed, resulting in a triple slash. According to wikipedia.

@thomasjo, alright. It's unfortunate because these aren't meant to be paths to a local resource. Again, in my (flawed) thinking, an href of /foo means 'document foo relative to the absolute root of the domain', but 'absolute root of the domain' is an implementation detail rather than something to be exposed, when in the client context. In the renderer/browser context, sure, I can understand it there.

**Comment by akrieger** [comment]
I've played around with it more and agree that your definition makes sense. It would make me happier if the drive letter wasn't automagically prepended such that querying for href returned consistent values across platforms, or that URI.getPath() would 'deal with it', but that would just move the special casing out of app code into atom code, where it suddenly becomes a magical behavior. Thanks for the explanation.

**Comment by akrieger** [comment]
In the interest of following up, we decided to add a file:// protocol handler which rewrites requests to load relative to our resources directory. Then we load our root document with no drive specification (eg. mainWindow.loadUrl('file:///index.html')). This causes any clicked links to be relative to '', which results in the .href property looking like file:///foo on Windows and OSX, as we wanted.

If we run into issues with this in the future, we will obviously revisit this. But for now this works the way we expect and may even solve some issues we're encountering with the library rewriting history and breaking future resource loads.

**Comment by bwin** [comment]
> Why are you including the extra slash? Don't you want file://C:/Default?

@paulcbetts When the hostname is omitted, there's 3 slashes after `file:`. See http://en.wikipedia.org/wiki/File_URI_scheme

**Comment by bwin** [comment]
@akrieger 

> I decided to add a file:// protocol handler which rewrites requests to load relative to our resources directory.

AFAIK file-URIs are always absolute (and platform specific). Wouldn't it be better to add a new protocol for your use-case, because the meaning of file-URIs is already defined?

**Comment by paulcbetts** [comment]
@akrieger Hm, that might be the spec but that doesn't line up with how people use them though, because on *nix that means you would have to write `file:////usr/bin/foo` (four slashes!) to get an absolute path, but people very often write three slashes for absolute paths

**Comment by bwin** [comment]
@paulcbetts good point about the 4 slashes. I couldn't find anything about that.
Maybe it's because `file:///etc/fstab` is short for `file://localhost/etc/fstab` and you don't use double slashes inside the `path`, just as a protocol-separator. Because otherwise it would be `file://localhost//etc/fstab` in long-form (with host).

**Comment by akrieger** [comment]
I tried adding a custom protocol. So our main.js looked like

```
...
protocol.registerProtocol('custom', function(request) {
  // Rewrite the request url to point to our assets.
});
...
app.on('ready', function() {
  mainWindow.loadUrl('custom:///index.html');
});
```

This worked at loading index.html. But, an inline <script src="/bundle.js"></script> tag we had would not load. Just, at all. There were no errors, for some reason the runtime just wasn't trying to fetch bundle.js in any way shape or form.

**Comment by akrieger** [comment]
```
akrieger$ cat src/index.html
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US">
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <div id="foo"></div>
    <script type="text/javascript" src="/bundle.js" charset="utf-8"></script>
  </body>
</html>
```

**Comment by bwin** [comment]
Could you try setting the custom protocol in the script-src?
`<script type="text/javascript" src="custom:///bundle.js" charset="utf-8"></script>`

**Comment by akrieger** [comment]
That does work. But then we would have to set the custom protocol on every single resource in our code. Every single image for example. It's... unsightly, I guess.

**Comment by akrieger** [comment]
Also using the custom scheme seems to mysteriously break the app even after it loads, whereas using the same behavior but for file:// seems to equally mysteriously just work.

**Comment by bwin** [comment]
Have you tried with `//`-prefixed URLs (I edited my previous comment)? Or do you dislike this, too? This is the protocol-relative way.
If you're still interested in this, could you describe how it breaks your app.

**Comment by akrieger** [comment]
If I try `//bundle.js` and scheme `custom`, then the script does not autoload.

If I try `//bundle.js` with scheme `file`, then I get a very mysterious request: url
`file request for file://bundle.js/`

This obviously fails to load.

**Comment by akrieger** [comment]
When I said 'breaks the app.'

What appears to be happening, using scheme `custom://`, loading `custom:///index.html` with `<script src="custom:///bundle.js" />`, is that when clicking a link, the href is completely, totally, garbage.

![screen shot 2015-03-25 at 9 50 52 pm](https://cloud.githubusercontent.com/assets/667719/6840617/489a4e5e-d339-11e4-80db-ec8af997da0a.png)

**Comment by bwin** [comment]
> This module [protocol] can only be used after the ready event was emitted.

In your example you have `registerProtocol` before `app.on('ready', ...`. Was this just in your example?

**Comment by akrieger** [comment]
Even if that weren't the case, some other code appears to be attempting history rewriting. This is okay with file:// but not with custom://.

I readily admit that a large part of my difficulties are stemming from my choice of libraries. I am eagerly researching alternatives.

**Comment by akrieger** [comment]
@bwin oops, yes, just in my example code. All of this is executing inside `app.on('ready', ...)`.

**Comment by bwin** [comment]
Ok, I'm experiencing some weird things... Tomorrow I'll look at it again. (It's late)(or early...)

**Comment by akrieger** [comment]
Thanks for looking into it! I really appreciate it.

**Comment by akrieger** [comment]
@bwin should I open a separate issue about what I linked above, where I click on a link with `href="/search"` but the property on the JS object returns `custom:///index.html`?

**Comment by bwin** [comment]
I couldn't look into it, because some bad things happened in my private life in the last days. I'm sorry. To me, some things (about the behaviour of custome protocols) didn't make sense. Yes, it's probably best to open a new issue and see what others think about it. Again, I'm sorry to not have answered in the last days, but I won't look into it soon. Best of luck anyway.

**Comment by akrieger** [comment]
That's cool! I grateful you even said you'll look into a closed issue's followup questions :)
