### ISSUE TITLE
Passing a string into new Tray() throws an exception

### ISSUE THREAD

**Issue by tommoor** [atom/atom-shell#1299]
Version 0.22.2, Mac OSX.

I have checked the string path passed is a full file:/ path that is correct. The image is a .png with Template appended to the filename.

![image](https://cloud.githubusercontent.com/assets/380914/6836269/d1f4d2aa-d2fd-11e4-831f-7466f90f486f.png)

I also tried using native-image and the createFromPath method to create a native image and pass this in. In this case it creates a blank tray icon with no image, however there is no exception thrown.

**Comment by zcbenz** [comment]
The API only accepts real filesystem path, so you should remove the `file://` prefix.

**Comment by tommoor** [comment]
Thanks! 

The path is produced from using path.normalize - I would expect to be able to pass the output of anything from the path module in...

**Comment by zcbenz** [comment]
Enabling `file://` prefix would imply the API can takes arbitrary urls, which is not true. I think we should have better error messages.

**Comment by tommoor** [comment]
Well, I could go for a better error message at the very least :smile:

**Comment by jstejada** [comment]
@zcbenz I'm trying to pass in a NativeImage instance created from a data url, but I'm getting that same error. Do you have any ideas what might be the cause?
