### ISSUE TITLE
max-width attribute is not obeyed if max-height is unset.

### ISSUE THREAD

**Issue by tommoor** [atom/atom-shell#1301]
When you want to create a window which has a restricted width but an unrestricted height, you might set BrowserWindow options as so:

```javascript
new BrowserWindow({
    'width': 280,
    'height': 500,
    'max-width': 280,
    'min-width': 260,
    'resizable': true
});
```

Unless max-height is set in the above hash you can still resize the window horizontally.

**Comment by bwin** [comment]
Confirmed on Windows 7, Atom-Shell 0.22.1.
