### ISSUE TITLE
`capturePage` can't work with atom-shell 2.22.1+ 

### ISSUE THREAD

**Issue by dygg** [atom/atom-shell#1305]
when i update atom-shell to the newer version , the old code couldn't to work correctly :

`
mainWindow.capturePage(function(imgBuf){
...
//imgBuf is not correct buffer, it's length is undefined
});
`

**Comment by zcbenz** [comment]
From v0.21.3 `capturePage` returns [NativeImage](https://github.com/atom/atom-shell/blob/master/docs/api/native-image.md#class-nativeimage) instance instead of Buffer.

**Comment by dygg** [comment]
er... the api docs haven't update...

**Comment by zcbenz** [comment]
@dygg Sorry I forgot to update the docs, it is updated now.
