### ISSUE TITLE
create-dist.py report error when libgcrypt.so does not exist

### ISSUE THREAD

**Issue by gliurn** [atom/atom-shell#1306]
I'm trying to create an RPM package for Centos 7 based on your spec file (https://build.opensuse.org/package/view_file/home:zcbenz:atom-shell/atom-shell/atom-shell.spec?expand=1)

after 
git clone --branch v0.21.3 https://github.com/atom/atom-shell.git 
cd atom-shell/
./script/bootstrap.py
./script/build.py 

everthing is fine, then :

./script/create-dist

report me this:

Downloading symbols for libchromiumcontent 103778aa0ec3772f88e915ca9efdb941afdc85cf...
http://gh-contractor-zcbenz.s3.amazonaws.com/libchromiumcontent/linux/64bit/103778aa0ec3772f88e915ca9efdb941afdc85cf/libchromiumcontent-symbols.zip
.............................................................................................................................................................................................................................................................................................................................................................................
Extracting...
Traceback (most recent call last):
  File "./script/create-dist.py", line 223, in <module>
    sys.exit(main())
  File "./script/create-dist.py", line 93, in main
    create_dist_zip()
  File "./script/create-dist.py", line 193, in create_dist_zip
    make_zip(zip_file, files, dirs)
  File "/root/test/atom-shell/script/lib/util.py", line 100, in make_zip
    zip_file.write(filename, filename)
  File "/usr/lib64/python2.7/zipfile.py", line 1114, in write
    st = os.stat(filename)
OSError: [Errno 2] No such file or directory: 'libgcrypt.so'

**Comment by zcbenz** [comment]
You can remove the line that contains `libgcrypt.so` in `create-dist.py` to work around this. This script copies some system libraries to the distribution but doesn't count the situation when the library doesn't exist.

**Comment by gliurn** [comment]
ok so this will work :
git clone --branch v0.21.3 https://github.com/atom/atom-shell.git 
cd atom-shell
./script/bootstrap.py
./script/build.py -c Release
sed '71d' /script/create-dist.py
./script/create-dist.py

but if i change version it won t of course.So can you think about it in your next commit?
my RPM is still building, it will inform you in case of fail

**Comment by gliurn** [comment]
RPM work but if i want to upgrade atom-shell's version, i will have to redo some of the work because of this, so could you resolve this problem quick please?

**Comment by gliurn** [comment]
Thanks a lot
