### ISSUE TITLE
Rename "Atom Helper" on Mac

### ISSUE THREAD

**Issue by jorangreef** [atom/atom-shell#1308]
I followed the instructions at https://github.com/atom/atom-shell/blob/master/docs/tutorial/application-distribution.md:

"You can rename Atom.app to whatever you want, and you also have to rename the CFBundleDisplayName, CFBundleIdentifier and CFBundleName fields in following manifest files if they have these keys:

Atom.app/Contents/Info.plist
Atom.app/Contents/Frameworks/Atom Helper.app/Contents/Info.plist"

I did exactly that and it mostly works:

When running the default_app, in Activity Monitor, the parent process is now renamed correctly, and one of the Helper's is also renamed correctly (the one with an icon), but the Helper with no icon is still called "Atom Helper" in Activity Monitor.

How can I get this last remaining "Atom Helper" (the Helper without the icon) to be renamed?

I would prefer to not have to rebuild Atom on all platforms.

Also, I noticed this commit in iojs: https://github.com/iojs/io.js/commit/3d46fefe0cb5abf45bb6a21e5d0a377c58f0f896 ("win,node-gyp: allow node.exe/iojs.exe to be renamed"). Will this allow the .exe to be renamed without breaking native node modules?

Finally, in the documentation regarding renaming the .exe, it's not clear whether native node modules refers to core modules shipped with Node (e.g. tls) or third party modules which have native bindings?

**Comment by zcbenz** [comment]
Currently `Atom Helper` is hard-coded, so the only way to change it is to rebuild with your own branding. I think we should probably search for `Helper` app instead of hard-coding the path when initializing.

I'm merging this to #686.

> Also, I noticed this commit in iojs: iojs/io.js@3d46fef ("win,node-gyp: allow node.exe/iojs.exe to be renamed"). Will this allow the .exe to be renamed without breaking native node modules?

Yeah.

> Finally, in the documentation regarding renaming the .exe, it's not clear whether native node modules refers to core modules shipped with Node (e.g. tls) or third party modules which have native bindings?

It refers the third party modules with native bindings.

**Comment by jorangreef** [comment]
Thanks, it would be great if Atom-Shell could search for a "... Helper" app in Frameworks.

**Comment by paulcbetts** [comment]
> I would prefer to not have to rebuild Atom on all platforms.

fwiw, this is exactly what we do at Slack. It's not that bad!

**Comment by jorangreef** [comment]
Do you do this using VMs? Could you give some tips as to how you automate it?

**Comment by paulcbetts** [comment]
@jorangreef https://github.com/paulcbetts/grunt-build-atom-shell will do everything for you, including fix up native modules
