### ISSUE TITLE
NPAPI Flash Plugin isn't searched and supported correctly in current atom-shell.

### ISSUE THREAD

**Issue by nyagi** [atom/atom-shell#1310]
Try this at ArchLinux:
```coffeescript
mainWindow = new BrowserWindow
  'width': 800
  'height': 600
  'dark-theme': true
  'web-preferences':
    'plugins': true
    'extra-plugin-dirs': [path.join(__dirname, 'plugins')]
```
navigator.plugins
PluginArray {length: 0, item: function, namedItem: function, refresh: function}

It seems no plugins searched.

And at Windows, plugins are collectly searched but flash video can't be shown either. Can it be fixed or PPAPI plugins support wanted?

**Comment by deepak1556** [comment]
NPAPI was removed from chromium version 35 on linux.  on windows its probably #936

**Comment by paulcbetts** [comment]
NPAPI Flash is working for us on Windows, haven't tested on Linux yet

**Comment by deepak1556** [comment]
@paulcbetts any clue on 936 then ? Also `41` seems to have a bug with redirect requests https://code.google.com/p/chromium/issues/detail?id=464629 .

**Comment by deepak1556** [comment]
Probably should alert users trying to load npapi plugins on unsupported platform using [this method](https://code.google.com/p/chromium/codesearch#chromium/src/content/browser/plugin_service_impl.cc&l=791&rcl=1427384622)

**Comment by paulcbetts** [comment]
@deepak1556   ¯\_(ツ)_/¯

**Comment by zcbenz** [comment]
In Chrome 41 NPAPI plugins are disabled unless you explicitly allow them on Windows and OS X, on Linux NPAPI support has been removed long long ago.

I think we should start supporting PPAPI plugins since Chrome is deprecating NPAPI plugins very soon, I'm merging this to #912.
