### ISSUE TITLE
Broken Link on Blog Posting

### ISSUE THREAD

**Issue by mattcollier** [atom/atom-shell#1312]
The link provided in the paragraph about spell checking is broken:
http://blog.atom.io/2015/01/21/new-in-atom-shell.html

I believe the link should point to:
https://github.com/atom/atom-shell/blob/master/docs/api/web-frame.md#webframesetspellcheckproviderlanguage-autocorrectword-provider

**Comment by kevinsawicki** [comment]
Thanks for pointing this out, should be fixed now.
