### ISSUE TITLE
Emit title-set event for webview

### ISSUE THREAD

**Issue by steelbrain** [atom/atom-shell#1316]
I've been using hacks like polling to see if title changed, emitting `title-set` would make it just too easy. and it will also be the first step towards an awesome custom webview API.

Thrust (also based on chromium) emits these events, You might want to have a look at [web_view_guest.cc](https://github.com/breach/thrust/blob/827ab964de36103543b6b0f53b5f4f2caf56f41a/src/browser/web_view/web_view_guest.cc#L766) and [web_view.js](https://github.com/breach/thrust/blob/298f53ca970624f3a680e8e4467014f55fe5bc3d/src/renderer/extensions/resources/web_view.js#L52).

@mark-hahn, won't it be cool for your web-browser package too :wink:

**Comment by mark-hahn** [comment]
> @mark-hahn <https://github.com/mark-hahn>, won't it to be cool for your
web-browser package too

Yes it would.

**Comment by tommoor** [comment]
Would this work the same as 'page-title-updated' but for webview? If so you'd probably want to mirror that event name... https://github.com/atom/atom-shell/blob/master/docs/api/browser-window.md#event-page-title-updated

**Comment by steelbrain** [comment]
Not sure, It'll have provide two arguments to the callback function `title, explicit_set` (explicit_set means that the title was set explicitly in js I guess)
