### ISSUE TITLE
How to use ipc (renderer) without callbacks?

### ISSUE THREAD

**Issue by jofan** [atom/atom-shell#1320]
I'm having an issue with the following scenario:

From renderer I create and open a new BrowserWindow
```
var remote = require('remote');
var BrowserWindow = remote.require('BrowserWindow');
var preview = new BrowserWindow({...});
```
Then I would like to communicate between Renderer and this new BrowserWindow and try to set up IPC to do so.
```
// same file
var ipc = remote.require('ipc');
ipc.on('enterSlide', enterSlideCallBack);
```
The events are coming through nicely but the ```enterSlideCallBack``` function creates a memory leak as explained [here](https://github.com/atom/atom-shell/blob/master/docs/api/remote.md#passing-callbacks-to-browser).

What I don't understand is how IPC can be used in Renderer (as documented [here](https://github.com/atom/atom-shell/blob/master/docs/api/ipc-renderer.md)) without callbacks. I'm sure I'm missing something obvious :). Anybody that can help me?

**Comment by steelbrain** [comment]
I think it's already fixed in the master by https://github.com/atom/atom-shell/commit/d46c64f64b0168cf74e5fb9f1140ca5869a5e75c

**Comment by jofan** [comment]
Ah, excellent. That's it, thanks!
