### ISSUE TITLE
After app.quit() atom process keeps running

### ISSUE THREAD

**Issue by luicaps** [atom/atom-shell#1322]
Hey guys,

New to atom-shell, idk if it's meant to be, but after closing the browser, the atom process on my prompt keeps running, demanding me to force kill (crlt + c).

My concern is if I missed any configuration or if the final client application will be keeping the process running even after the user closed it.

Thanks!

**Comment by zcbenz** [comment]
Can you give a minimal example?

**Comment by luicaps** [comment]
Sorry if I wasn't clear. Here in my pc, when I run atom (just running the application without any parameters), the process is bound to my shell. After closing atom, the process is still bound, like it didn't finish completely.

![shell](https://cloud.githubusercontent.com/assets/5818668/6932901/771bc750-d7f6-11e4-948e-3fbc6070f21f.png)

I was wondering if closing atom really quits all the processes involved.

**Comment by zcbenz** [comment]
atom-shell uses some tricks to print output to console, the process actually quits, and you can verify it in process explorer or task manager.

**Comment by haoxins** [comment]
![wechat_1441091984](https://cloud.githubusercontent.com/assets/8917336/9598334/f62d66ae-50bc-11e5-844d-8c98d67503d0.jpeg)

After `app.quit() or app.exit()`, the electron processes keep increasing

**Comment by waeldief** [comment]
This issue solved by @ryhanson in https://github.com/atom/electron/issues/2312#issuecomment-153966902
