### ISSUE TITLE
What is the foreground mode?

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom-shell#1325]
This is probably a stupid question.  The atom editor has a foreground option `-f`.  What does it mean to run a browser process in the foreground?  I don't see how a browser could run in a background process.

**Comment by zcbenz** [comment]
The `atom` command will exit immediately after opening the file, and `atom -f` will wait until the editor quits and print Chromium debug information in the meanwhile. There is no concept of foreground mode in atom-shell.
