### ISSUE TITLE
How to pass iojs arguments

### ISSUE THREAD

**Issue by steelbrain** [atom/atom-shell#1328]
I couldn't find it in the docs, I want to pass `--es_staging` to atom-shell in able to use classes in my app.

**Comment by zcbenz** [comment]
You can enable it in web pages by using following code:

```js
app.commandLine.appendSwitch('js-flags', '--es_staging');
```

There is no way to use it in main process for now.

**Comment by steelbrain** [comment]
Would something like [this][this] work in the main process? (just curious)

[this]:https://www.npmjs.com/package/setflags

**Comment by steelbrain** [comment]
For future visitors, You can set v8 opts at runtime with `v8::setFlagsFromString`
https://iojs.org/api/v8.html#v8_setflagsfromstring

**Comment by steelbrain** [comment]
Just have something like this in the main file and include your main app in that file, for example
```js
  var v8 = require('v8');
  v8.setFlagsFromString('--harmony_classes');
  v8.setFlagsFromString('--harmony_object_literals');
  v8.setFlagsFromString('--harmony_tostring');
  require('./Main');
```

**Comment by CxRes** [comment]
@steelbrain Could you please clarify how you have loaded v8 flags. I put the above code in the main file as specified in manifest. And then required the file which contains the `app` instance. However the flag did not work. I am trying to use the `--harmony_modules` flag.

**Comment by steelbrain** [comment]
@CxRes it works for me, but please note that the flags are process-bound, so flags set in one process will not be available in another

**Comment by flying-sheep** [comment]
seems to be broken right now :(

see nodejs/node#1000
