### ISSUE TITLE
background-image doesn't work with ASAR archives

### ISSUE THREAD

**Issue by paulcbetts** [atom/atom-shell#1330]
To repro:

1. Create a `div`, set its `background-image` to `./someImg.svg`
1. It doesn't work
1. In that div, create an `img` with a `src` tag. 
1. It does work
1. Manually set the `background-image` to a full path that includes `app.asar`
1. It does work

```
GET file:///path/to/my/app/Contents/Resources/app/static/maximize-normal.svg net::ERR_FILE_NOT_FOUND
```

Maybe the missing app.asar is the problem?

**Comment by zcbenz** [comment]
I think it might be related to the path of your css or html file, a simple html page with inline css works for me:

```html
    <style type="text/css" media="screen">
      #test {
        display: block;
        width: 520px;
        height: 300px;
        background-image: url('./atom.png');
      }
    </style>
```

![screen shot 2015-03-30 at 11 35 40 am](https://cloud.githubusercontent.com/assets/639601/6889810/ee59b04c-d6d0-11e4-9287-96c25d6a5b92.png)

**Comment by paulcbetts** [comment]
@zcbenz After debugging it more, I think that the LESS compiler is changing './foo' to 'foo' and that fails. Sorry about that.
