### ISSUE TITLE
window.opener.postMessage issue

### ISSUE THREAD

**Issue by smebberson** [atom/atom-shell#1341]
I can't seem to get the `window.opener.postMessage` to work correctly. The scenario is that I've opened a window using BrowserWindow, and I'm trying to communicate between my main window and my opened window.

When the code executes the `window.opener.postMessage` function, I get the following error which appears in a JavaScript alert dialog:

```
Uncaught Exception:
TypeError: Cannot read property 'send' of undefined
    at EventEmitter.<anonymous> (/Library/WebServer/focusbooster-desktop-atom-shell/atom-shell/binaries/darwin/Atom.app/Contents/Resources/atom.asar/browser/lib/guest-window-manager.js:90:22)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.<anonymous> (/Library/WebServer/focusbooster-desktop-atom-shell/atom-shell/binaries/darwin/Atom.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:86:23)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:169:7)
```

I wrote some isolated code as a test case for this. You can take a look at it here https://github.com/smebberson/atom-shell-postmessage-demo. You'll need to run it within the context of atom-shell of course.

I'm running Mac OS X 10.10.2 and I'm using atom-shell v1.5.1.

**Comment by deepak1556** [comment]
In your test case use `window.open` to create guest browser window as it keeps track of the window for `window.opener` https://github.com/atom/atom-shell/blob/master/docs/api/window-open.md .

**Comment by zcbenz** [comment]
Only window opened by `window.open` will have `window.opener` set, thanks @deepak1556.

**Comment by smebberson** [comment]
Thanks for looking into this. The documentation doesn't actually state this, should I submit a PR to fix that. I think it could be clearer.

Also, that page, which I had read previously talks about using `BrowserWindow` rather than `BrowserWindowProxy` as there are limited features implemented with `BrowserWindowProxy`.

If I'm waiting to access the full features of `BrowserWindow`, how would I go about achieving this in a context in which `window.opener` exists?

**Comment by zcbenz** [comment]
> Thanks for looking into this. The documentation doesn't actually state this, should I submit a PR to fix that. I think it could be clearer.

It sounds a good idea to me.

> If I'm waiting to access the full features of BrowserWindow, how would I go about achieving this in a context in which window.opener exists?

You should not use `window.open` and `window.opener` if you want full features, they only exist to be compatible with some web pages.

**Comment by smebberson** [comment]
If I wasn't to use `window.open` and `window.opener` but wanted to achieve communication between my primary window and my opened window (while having the full control that BrowserWindow offers), is it best to just use the [IPC module](https://github.com/atom/atom-shell/blob/master/docs/api/ipc-main-process.md) and then route communication between the two windows using a custom function to proxy the messaging?

**Comment by zcbenz** [comment]
Yeah you have to use `ipc` to route messages between your windows in the main process.

**Comment by bkeepers** [comment]
I just ran into this using [remark](https://github.com/gnab/remark), a browser-based slideshow tool. It [tries to detect the presence of `window.opener`](https://github.com/gnab/remark/blob/e034c9f0d541124cc54152f34d036e4c25ffc124/src/remark/models/slideshow/navigation.js#L94-L96) before calling it.

It seems like the current behavior of raising an error is not ideal. I would expect `window.opener` to either be null, or to silently noop, or even to be an alternate way of calling `ipc.send`.
