### ISSUE TITLE
What's the status of asar and atom-shell releases/compatibilities at this point?

### ISSUE THREAD

**Issue by shrewdlogarithm** [atom/atom-shell#1346]
Since I made my middleware 'asar packager' I note there's been a LOT of work done on the asar project - and a few new releases of atom-shell

Is there a dependency map between the 2 projects - does the current 'release' of atom-shell require asars made with a specific release of the asar project - is there anywhere which documents this stuff or is it backwards compatible?

In particular I noticed that asar had it's dependency on chromium-pickle removed (it's a pain to compile and hard to deploy on a PaaS as it has very specific dependencies) and then reverted??

Is there a plan to redo that or...

**Comment by paulcbetts** [comment]
The only ASAR compatibility change that has happened recently is if you use the "Unpacked ASAR" feature (https://github.com/atom/asar/pull/25), otherwise they should be compatible

**Comment by zcbenz** [comment]
If you didn't use the "unpacked" feature then everything is compatible.
