### ISSUE TITLE
Can I communicate with a webview through IPC?

### ISSUE THREAD

**Issue by pcomans** [atom/atom-shell#1349]
Hi there,

I am embedding an external web app in my atom shell application. It lives in a webview for security reasons.
Is there any way to add the capability to receive IPC messages to the web app by using webview.executeJavaScript?
Am I going about this the wrong way?

**Comment by zcbenz** [comment]
You can find examples in webview's docs:
https://github.com/atom/atom-shell/blob/master/docs/api/web-view-tag.md#ipc-message

People usually setup IPC in `preload` scripts.

**Comment by jamesschauer** [comment]
I don't think the documentation is at all clear with respect to answering this question.

The documentation is focused on interaction between the main and render proc.

It's not clear how the javascript inside the webview sends or receives messages.

**Comment by MarshallOfSound** [comment]
@jamesschauer The key thing to understand here, is the the WebView is it's own renderer process.  Anywhere in the docs that the "renderer" process is mentioned, it can mean either a BrowserWindow's webContents or a WebView's webContents.

In terms of the IPC API they both act the same way.

**Comment by paulcbetts** [comment]
IPC will by-default, go between the webview and the main process, even though in the HTML it's this hierarchical main => window => webview, from Chrome's perspective, it's just main => [all renderers]. WebView has a "sendToHost" method that lets you talk with your parent BrowserWindow

**Comment by perlun** [comment]
For reference, here is the documentation for the `sendToHost` method: https://github.com/electron/electron/blob/master/docs/api/ipc-renderer.md#ipcrenderersendtohostchannel-arg1-arg2-

**Comment by Aarbel** [comment]
@perlun do you have a code example to show how main process can communicate with a <webview> ?

My <webview> needs to send informations to main process, how can i access ipcRenderer inside it ? Thru `window` global object ? `process` global object ?  

Thanks a lot for your help !

**Comment by trusktr** [comment]
I'm trying to communicate from a host window to a webview, and not having any luck. Just silence.

Can you please add example of specifically communicating from a BrowserWindow to the `<webview>`?

**Comment by trusktr** [comment]
Okay, I figured it out, and it is not what the docs seem to suggest (_god @#$%! Please update the docs with examples!_):

```js
// inside the `<webview>`:

// this part is normal, just like inferred from the docs, using ipcRenderer:
import {ipcRenderer} from 'electron'
ipcRenderer.sendToHost('channelName', ...args)
```

```js
// in the host BrowserWindow

// this is what is not clear in the example-lacking docs:

// do NOT do this:
    webview.getWebContents().on('ipc-message', onIpcMessage)

// instead, do this:
    webview.addEventListener('ipc-message', onIpcMessage)

// here's how the handler should be:
  function onIpcMessage(event) {
    const {args, channel} = event
    console.log(channel, args)

    // and here's how to send a message to the webview:

    // do NOT do this:
    webview.getWebContents().send('channelName', ...args)

    // instead, do this:
    webview.send('channelName', ...args)
  }
```

So, basically, I'm _**not**_ using WebContents IPC in the host window, and it works great. Trying to use the webview's webContents IPC in the host BrowserWindow doesn't work no matter what I try.

As @pcomans mentioned

> I don't think the documentation is at all clear with respect to answering this question.
> The documentation is focused on interaction between the main and render proc.
> It's not clear how the javascript inside the webview sends or receives messages.

@zcbenz @MarshallOfSound Can you or other Electron team members please spend some time on the docs?

**Comment by MarshallOfSound** [comment]
Hey @trusktr just a quick thing, I would remind you that interacting with maintains on this issue tracker requires you follow the [Code Of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) and comments such as "god @#$%" towards maintainers or other community members are inappropriate even when self-censored.  I would ask that you remove that particular part of your comment and in the future ensure your comments are non-combative and respectful to the maintainers and community who invest time in this project.

All this said we do acknowledge that certain parts of our docs do need some work and we have an entire Working Group --> [Docs & Tools](https://github.com/electron/governance/tree/master/wg-docs-tools) to deal with this problem.

However in this specific case the documentation for `ipc-message` on the webview element (what you are trying to use here) has a simple, minimal example explaining exactly how to use `sendToHost` and `ipc-message`.

https://electronjs.org/docs/api/webview-tag#event-ipc-message

**Comment by trusktr** [comment]
Sorry about that, it's not personal, just frustration. I hope it may make maintainers want to improve docs.

That example is nice, but WebContents IPC seems to be the obvious API to use, as we know from BrowserWindows. So if you read that example, you will wonder why it isn't using webContents like we do with BrowserWindows. My intuition is that it would work the same as with BrowserWindows (most people will have that intuition).

**Comment by trusktr** [comment]
Does it work with WebContents IPC? Is there an example of that?

**Comment by Nashorn** [comment]
@trusktr - thank you for the solution on communications between preload script and webview/renderer. The docs on webview <--> main process works, but sendToHost from a preload<-->webview/renderer never worked unless you fired a sendToHost from preload and intercepted using an addEventListnener in renderer/webview.

Thanks

**Comment by Nashorn** [comment]
BTW -- The communications strategy and approach (if you want to call it a 'design') in electron between main, renderer and guest/preload is all over the place, there are so many confusing and ambiguous ways to send, sendTo, sendToHost, sendSync....then using ipc, ipcRenderer, ipcMain, a combination of sendToHost + addEventListener, channels....what the hell!

Take that dog out to the back, shave its as and shoot. So horrible, the electron team needs to resolve this with an improved, centralized and secure event bus with 1 unified api. Because what i described above is ridiculous, i've spent a day, hours lost figuring out how to send a message from 1 process to another...AND, that was in just 1 direction.

**Comment by papuruth** [comment]
> Okay, I figured it out:
> 
> ```js
> // inside the `<webview>`:
> 
> // this part is normal, just like inferred from the docs, using ipcRenderer:
> import {ipcRenderer} from 'electron'
> ipcRenderer.sendToHost('channelName', ...args)
> ```
> 
> ```js
> // in the host BrowserWindow
> 
> // this is what is not clear in the example-lacking docs:
> 
> // do NOT do this:
>     webview.getWebContents().on('ipc-message', onIpcMessage)
> 
> // instead, do this:
>     webview.addEventListener('ipc-message', onIpcMessage)
> 
> // here's how the handler should be:
>   function onIpcMessage(event) {
>     const {args, channel} = event
>     console.log(channel, args)
> 
>     // and here's how to send a message to the webview:
> 
>     // do NOT do this:
>     webview.getWebContents().send('channelName', ...args)
> 
>     // instead, do this:
>     webview.send('channelName', ...args)
>   }
> ```
> 
> So, basically, I'm _**not**_ using webview's WebContents IPC in the host window, and it works great. Trying to use the webview's WebContents IPC in the host BrowserWindow doesn't work no matter what I try.
> 
> As @pcomans mentioned
> 
> > I don't think the documentation is at all clear with respect to answering this question.
> > The documentation is focused on interaction between the main and render proc.
> > It's not clear how the javascript inside the webview sends or receives messages.
> 
> @zcbenz @MarshallOfSound Can you or other team members spend some TLC on the docs?

Thanks man this helped me to solve my problem.
Basically I was trying to accomplish to call a function in renderer process that's in react via electron menu item. But react is being served inside webview.
So, I used 
`currentWindow.webContents.send('any_channel', args);`  in menu click function
and in `electron-index.html` I did following, 
```js
ipcRenderer.on('any-channel', (event, args) {
webview.send('channel_name_in_react_component', args);
})
```
and in react component  I accessed it using
```js
ipcRenderer.on('channelNamel', (event, args) {
// do whatever
});
```
