### ISSUE TITLE
'window-all-closed' event on darwin

### ISSUE THREAD

**Issue by mattcollier** [atom/atom-shell#1357]
The quick-start code provided for main.js in the docs makes an exception for darwin related to the 'window-all-closed' event triggering app.quit():

https://github.com/atom/atom-shell/blob/fdc07dea177f52ae0943db320358ee1ea8da5107/docs/tutorial/quick-start.md

Is this exception still necessary?  I've got some code triggered by the 'before-quit' event that is not getting run on OSX due to this exception.

**Comment by deepak1556** [comment]
just need to update the docs, you can remove the exception.

**Comment by zcbenz** [comment]
On OS X it is a convention that most apps do not quit when all windows are closed, that code is to follow this convention.

You can create a separate issue if you observed a bug.

**Comment by deepak1556** [comment]
Ahh, Forgot abt tat, thanks!

**Comment by damianobarbati** [comment]
@zcbenz does this event `window-all-closed` still exists? It doesn't fire on MacOS, no matter if:

- there's an app window and I `window.close()`
- there's an app window and user press `cmd+W`
- there's an app window and user press `cmd+Q`
