### ISSUE TITLE
Reduce distribution size

### ISSUE THREAD

**Issue by lavelle** [atom/atom-shell#1365]
I've got a relatively simple Atom Shell app that I'm looking to distribute. I'm packaging it by copying my `app` directory into `Atom.app/Contents/Resources`, then renaming `Atom.app` to `MyName.app` and zipping it up.

My app directory is 2.3 mb but the resulting ZIP is 108 mb. Since the whole of the Atom editor for OS X is  75mb, I figure I must be adding some unecessary stuff to the archive. Is there anyway to reduce the file size? I'm storing on S3 so I'm keen to keep bandwidth down.

**Comment by kevinsawicki** [comment]
Are you running the zip command with the `--symlinks` option?

**Comment by lavelle** [comment]
That took it down to 106mb haha. It hardly seems to be getting compressed at all. Atom itself is 216mb and goes down to 79mb zip, whereas mine stays around 100mb before and after. I'm using a build from `grunt-download-atom-shell`, downloading version 0.20.3. Would I be able to make it smaller (or more compressible) building myself?

**Comment by zcbenz** [comment]
I'm closing this since it is a question not an issue, https://discuss.atom.io/c/atom-shell is a better place for this.

**Comment by zcbenz** [comment]
The zip distribution on Mac is created via `zip -r -y`.
