### ISSUE TITLE
Can't reset labels of menu items in osx

### ISSUE THREAD

**Issue by awsmsrc** [atom/atom-shell#1375]
You can however set the enabled attribute.
We want it to work like the wifi menu in osx where the first item is disabled but you see app state
I would like to not have to create an entirely new menu

Not tested on any other OS

**Comment by zcbenz** [comment]
I'm merging this to #528.

**Comment by awsmsrc** [comment]
@zcbenz so this is fixed in the current released version of electron?

**Comment by zcbenz** [comment]
No, but it will be fixed once we have #528 implemented, so you can track that issue for progress.
