### ISSUE TITLE
Resizing a transparent window results in a white background flash

### ISSUE THREAD

**Issue by willbarrett** [atom/atom-shell#1391]
Observed on Ubuntu Linux 14.04 (unity) and Windows 8.1.

Steps to reproduce:
1) Create a transparent window
2) Resize the window from a smaller size to a larger size on a trigger, such as a mouse event.
3) Trigger the resize. About 1/4 of the time, the newly-added space in the window will render as a white block for one frame before being filled with transparency.

Theoretically, the window should be transparent on initial resize, and then be filled with content, if they can't happen simultaneously.

**Comment by willbarrett** [comment]
Doesn't seem to affect OSX.

**Comment by zcbenz** [comment]
Resizing a transparent window is not supported in atom-shell, though it is not explicitly prohibited, there is nothing we can do with the bugs of it.

So I'm closing this as won't fix.

**Comment by willbarrett** [comment]
Hey @zcbenz - we understand, but that's really unfortunate. Where do the bugs lie? In Chromium itself, or in another dependency of atom-shell?

**Comment by zcbenz** [comment]
@willbarrett This is a bug of Chromium, we share the same code with Chrome extension's [alpha enabled window](https://code.google.com/p/chromium/issues/detail?id=436596), but that feature is still experiment and in heavy development.

**Comment by willbarrett** [comment]
Thanks @zcbenz - that's really helpful.

**Comment by TemaSM** [comment]
@zcbenz , what about nw.js - it doesn't has the same bug :pensive:
