### ISSUE TITLE
setTimeout after rendererWindow.close() fails to fire

### ISSUE THREAD

**Issue by teleclimber** [atom/atom-shell#1400]
It seems that if I call setTimeout after closing a renderer window, the setTimeout never fires.

To reproduce: grab hello-atom from https://github.com/dougnukem/hello-atom and add a few lines at the end of the `app.on('ready', function() {` callback in `main.js` so it looks like this:

```
 app.on('ready', function() {
  // Create the browser window.
  mainWindow = new BrowserWindow({width: 800, height: 600});

  // and load the index.html of the app.
  mainWindow.loadUrl('file://' + __dirname + '/index.html');

  // Emitted when the window is closed.
  mainWindow.on('closed', function() {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null;
  });
  
/////add these lines:
  setTimeout( function() {
        console.log( 'about to close window' );
	
        mainWindow.close();
	
        setTimeout( function() {
              console.log( 'after window close' );
        }, 3000 );
  }, 3000 );
////end added lines

});
```

The first `setTimeout` is just there to trigger the problematic code (on my project it's triggered by a menu).

On atom-shell 0.22.3 in windows 7 the "after window close" never gets logged (and in my experience with my project nothing in the setTimeout callback ever gets executed).

If you comment out `mainWindow.close();` then "after window close" appears as expected in the console.

**Comment by bengotow** [comment]
Hi teleclimber,

I think the problem you're running into is that the `window-all-closed` event handler (here: https://github.com/dougnukem/hello-atom/blob/master/hello-app/main.js#L12) is firing and quitting the application immediately after the last window is closed. You should be able to keep your application running on Windows/Linux by disabling that event handler.

**Comment by teleclimber** [comment]
Ooohh. Of course. I guess I never realized it quit because atom.exe keeps running after the application quits.

Thanks!
