### ISSUE TITLE
exit the app

### ISSUE THREAD

**Issue by majomuchi123** [atom/atom-shell#1401]
I know how to exit the app in main.js, but i want to stop it when for example i click a button.
I just want to do that seriously, just that i didnt found any information about it.

Thanks.

**Comment by saschagehlich** [comment]
```js
var app = require('app');
app.quit();
```

**Comment by majomuchi123** [comment]
Thanks a lot man.
It may be a silly question but im starting at prgramming, and i got 13 years so really thanks

**Comment by bahmandamia6982** [comment]
@majomuchi123 

**First** 
> $ npm install jquery --save

**Next edit app.js like this**
`const remote = require('electron').remote`
`const $ = require('jquery')`    
`$('#exit').click( e => {`
    `    remote.getCurrentWindow().close()`
`}); `

**Finally add app.js to your html file**
`<script src="./app.js"></script>`

**Comment by majomuchi123** [comment]
Thank you very much, @bahmandamia6982
