### ISSUE TITLE
Release folder has changed to `out/R` on Win32

### ISSUE THREAD

**Issue by paulcbetts** [atom/atom-shell#1413]
Building with `python script/build.py -c Release` now builds to a folder called "R" not to "Release" anymore, seems like an oops

**Comment by Tribex** [comment]
@paulcbetts This is intentional, see https://github.com/atom/atom-shell/blob/master/docs/development/build-system-overview.md#target-names. :)

**Comment by paulcbetts** [comment]
Aha, closing - :tophat: @Tribex
