### ISSUE TITLE
modules required in a webview shares variables

### ISSUE THREAD

**Issue by mafintosh** [atom/atom-shell#1414]
It seems variables are shared across modules when using a webview. Consider the following example

`app.js`:
``` js
#!/usr/bin/env atom-shell

var app = require('app')
var BrowserWindow = require('browser-window')
var win

app.on('ready', function () {
  win = new BrowserWindow({show: true})
  win.loadUrl('file://index.html')
})
```

`index.html`:
``` html
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
  <script src="index.js"></script>
</body>
</html>
```

`index.js`:
``` js
var foo = 'bar'
var dep = require('./dep.js')
```

`dep.js`:
``` js
console.log(foo) // notice that foo isn't declared
```

Normally when using node or iojs running `index.js` would result in `dep.js` throwing a ReferenceError since foo is not declared . However when running `app.js` with atom-shell `dep.js` ends up printing `bar` since it apparently shares variables declared in `index.js`.

This is a pretty big issue and it will break modules that declare variables in the module scope called the same as variables declared in `index.js`.

**Comment by zcbenz** [comment]
Scripts loaded by `<script>` will be loaded by the browser, and the code in it will run under global context, so setting `foo` in it is equivalent to set `global.foo`.

You should use `require` if you want to constrain the code in module scope.
