### ISSUE TITLE
Completely remove the Menu from the top of the screen on Mac?

### ISSUE THREAD

**Issue by bradparks** [atom/atom-shell#1415]
Hey! Is there anyway to completely remove the top level menu from the app? I've tried all the following and none seem to work. My app needs to show a transparent overlay on top of each monitor screen, that takes up the entire screen. Thanks!

```
  var size = d.workArea;
  var w = new BrowserWindow({
    frame:false,
    toolbar: false,
    'accept-first-mouse': true,
    transparent: true,
    left:d.workArea.x,
    top:d.workArea.y,
    'skip-taskbar': true,
    'auto-hide-menu-bar': true,
    'enable-larger-than-screen': true,
    width:size.width,
    height:size.height
  });
  w.setMenuBarVisibility(false);
  w.setAutoHideMenuBar(true);
```

**Comment by paulcbetts** [comment]
Probably needs to be marked as `LSUIElement` (https://developer.apple.com/library/mac/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html)

**Comment by bradparks** [comment]
ok... good to know... thanks....

**Comment by paulcbetts** [comment]
> My app needs to show a transparent overlay on top of each monitor screen, that takes up the entire screen.

Also, this will make it so the user can't click anything on-screen, this is probably not what you want...

**Comment by bradparks** [comment]
ahh.... my app is intended to be keyboard driven, but will still require mouse interaction. You think it's at this level that I need to do this possibly though? Something to do with plists and custom mac builds?

**Comment by zcbenz** [comment]
Having an application menu is an requirement for normal desktop applications on OS X, so I'm closing this since it is basically impossible. Specifying `LSUIElement` in `Info.plist` should be able to give the thing you want with some side effects.

> ahh.... my app is intended to be keyboard driven, but will still require mouse interaction. You think it's at this level that I need to do this possibly though? Something to do with plists and custom mac builds?

Currently it is impossible.

**Comment by alexandrubau** [comment]
You can use w.setMenu(null); [setMenu](http://electron.atom.io/docs/v0.34.0/api/browser-window/#win-setmenu-menu-linux-windows)

**Comment by piavgh** [comment]
set frame: false will also remove  Close/Maximize/Minimize buttons

**Comment by jayarjo** [comment]
So it impossible to remove default menu or what?

**Comment by MattIPv4** [comment]
I have an application that is full screen that I wish to overlay on top of everything, including the menubar at the top of the screen on a mac, is this at all possible, couldn't really get an answer from what has been said here already. `frame:false` removes the titlebar of the application, but not the macos menu bar.

**Comment by jjeff** [comment]
FWIW, there is a Mac System Preferences setting (under "General") to hide the menu bar (similar to the way the menu works when a window is in fullscreen). I'm not sure if/how Electron can read/write that setting and it requires an extra step from your users… but it's there.
<img width="780" alt="Screen Shot 2020-10-27 at 5 00 45 PM" src="https://user-images.githubusercontent.com/321284/97361630-30457d00-1876-11eb-9066-f64150687c88.png">

**Comment by justinseibert** [comment]
An alternative to `LSUIElement` is setting `LSUIPresentationMode` to `3` which is described as:

> All hidden mode. In this mode, all UI elements are hidden, including the menu bar. Elements do not automatically show themselves in response to mouse movements or user activity.

https://developer.apple.com/documentation/bundleresources/information_property_list/lsuipresentationmode

**Comment by nianyi778** [comment]
> I have an application that is full screen that I wish to overlay on top of everything, including the menubar at the top of the screen on a mac, is this at all possible, couldn't really get an answer from what has been said here already. `frame:false` removes the titlebar of the application, but not the macos menu bar.我有一个全屏应用程序，我希望将其覆盖在所有内容之上，包括 mac 屏幕顶部的菜单栏，这是否可能，无法从这里已经说过的内容中真正得到答案。`frame：false` 会删除应用程序的标题栏，但不会删除 macOS 菜单栏。

 Is there a suitable solution? I had a similar problem
