### ISSUE TITLE
npm install error - cert not trusted

### ISSUE THREAD

**Issue by boxertech** [atom/atom-shell#1419]
Getting an error when trying to install on a new Windows 7 machine. Anyone else seeing this? Error shown:

$ npm install atom-shell -g
C:\Users\xxxxxxx\AppData\Roaming\npm\atom-shell -> C:\Users\xxxxxxx\AppData\Roaming\npm\node_modules\atom-shell\run.bat

> atom-shell@0.23.0 install C:\Users\xxxxxxx\AppData\Roaming\npm\node_modules\atom-shell
> node install.js

Downloading atom-shell-v0.23.0-win32-x64.zip
Error: certificate not trusted

C:\Users\xxxxxxx\AppData\Roaming\npm\node_modules\atom-shell\install.js:16
  throw err
        ^
Error: certificate not trusted
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Development\\nodejs\\node.exe" "c:\\Development\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "atom-shell" "-g"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! atom-shell@0.23.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the atom-shell@0.23.0 install script 'node install.js'.
npm ERR! This is most likely a problem with the atom-shell package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls atom-shell
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\development\npm-debug.log

**Comment by steelbrain** [comment]
If you could just format that error output in proper markdown :)

**Comment by zcbenz** [comment]
Please move this issue to https://github.com/mafintosh/atom-shell since the atom-shell npm registry is managed there. And pasting the content of `c:\development\npm-debug.log` would help a lot.
