### ISSUE TITLE
Update to Chrome 42?

### ISSUE THREAD

**Issue by saschagehlich** [atom/atom-shell#1424]
Is there any estimate on when atom-shell will include the latest version of Chrome? They added an important feature to the WebAudio API:

https://www.chromestatus.com/feature/5411681005993984

The page says Chrome 43, but I just updated my Chrome to 42.0.2311.9 and AudioContext.prototype.close is already available.

**Comment by zcbenz** [comment]
We will do the upgrade next week.

**Comment by saschagehlich** [comment]
Cool, thank you!
