### ISSUE TITLE
What is to become of process.versions['atom-shell']

### ISSUE THREAD

**Issue by mattcollier** [atom/atom-shell#1433]
I suspect there's a fair amount of existing code that uses process.versions['atom-shell'] to identify the atom-shell environment.  What is to become of this property when the name change occurs?  Is there a better way to identify then atom-shell environment?

**Comment by frankhale** [comment]
I'd suspect that a new identifier called electron will be added which
provides the same info and the atom-shell will still exist and then be
deprecated after a while. That is just an opinion of course.

**Comment by zcbenz** [comment]
`process.versions['atom-shell']` will be kept for backward compatibility, existing code will not be affected by the rename.
