### ISSUE TITLE
Increase the max stack depth on the dev tools profiler?

### ISSUE THREAD

**Issue by nathansobo** [atom/atom-shell#222]
I'm running into [this issue][chromium-issue] when trying to use the flame graph to profile editor typing performance, which is making it really difficult to reason about. How hard would it be to change the stack limit on their profiler or make it adjustable?

[chromium-issue]: https://code.google.com/p/chromium/issues/detail?id=233145

**Comment by deepak1556** [comment]
@nathansobo is this still an issue after the frame count increase https://code.google.com/p/v8/source/detail?r=21986 ?

**Comment by nathansobo** [comment]
I haven't encountered a problem with it for some time, so I'll go ahead and close.
