### ISSUE TITLE
Support for window transparency

### ISSUE THREAD

**Issue by garand** [atom/atom-shell#381]
Is it possible to set the window background to transparent and then allow the transparency level to be controlled with CSS? Similar to TextMate?

![screen shot 2014-06-05 at 9 46 46 am](https://cloud.githubusercontent.com/assets/82437/3188124/db02aca0-ecb7-11e3-97ae-aa5f3cf6eaec.png)

/cc @zcbenz

**Comment by v3ss0n** [comment]
So thats means Atom have support for it too ? or atom haven't swtich to that version>?

**Comment by agileago** [comment]
＋1,it is great

**Comment by v3ss0n** [comment]
thats sooo awesome @zcbenz  , so awesome that it give me tears! Soon we can have transulant atoms running :D .

**Comment by MastroPino** [comment]
+1 great on OS X 10.11

**Comment by fritx** [comment]
Any progress on blurred background? +1 for that

**Comment by sgarbesi** [comment]
+1

**Comment by htmlguy** [comment]
+1

**Comment by imcoddy** [comment]
+1

**Comment by luigiplr** [comment]
+1

**Comment by hirokiky** [comment]
+1

**Comment by AshCoolman** [comment]
Untested by from [here](http://lurk.org/groups/tidal/messages/topic/18D8UrgeQxqsReDL3Kv0Wx):


> Thought I would share this in case it's useful. I figured out how to make the
> Atom editor transparent, mostly gleaned from various forums around the web,
> gathered here for future reference.
> 
> Can't attach this gif from some reason, but my set-up now looks like this:
> https://dl.dropboxusercontent.com/u/2177570/transparentAtom.gif
> 
> (I have only tested this on a Mac running El Capitan).
> 
> 1. Download the Atom repository from github (https://github.com/atom/atom)
> 
> 2. Open up this file: ~/atom/src/browser/atom-window.coffee
> 
> 3. At line 26, change this:
> 
>     options =
>       show: false
>       title: 'Atom'
>       'web-preferences':
>         'direct-write': true
> 
> to this:
> 
>     options =
>       frame: true
>       transparent: true
>       title: 'Atom'
>       'web-preferences':
>         'direct-write': true
>         'subpixel-font-scaling': true
> 
> 
> (it could be that you literally just need the 'transparent:true' command here
> and that those other extras are superfluous, but I haven't recompiled Atom to
> find out).
> 
> 4. Compile this version of Atom (this is always a bit trial and error for me. I
> suspect most people here know how to do it in their sleep. I navigated to the
> atom directory in terminal and ran this: script/build --install-dir ~/<path to
> wherever>/Atom.app
> 
> 
> 5. In Atom, go to Packages > Package Generator > Generate Atom Syntax Theme and
> name a new theme
> 
> 6. Go to Preferences > Themes. Find your theme, select it, and then choose
> 'view code'
> 
> 7. This should open a branch of all the files for the new syntax you've
> created. Find your base.less style sheet and tailor it to suit your needs. More
> info on theme customisation here (https://atom.io/docs/v1.2.0/)
> 
> I kept it super simple just using these lines which just turn the alpha channel
> of the background right now.
> 
> html, body, atom-workspace, atom-pane-container atom-pane {
>   background: rgba(0, 0, 0, 0) !important;
>   }
> 
> 
> atom-text-editor, :host {
>   background-color: rgba(0, 0, 0, 0.1);
>   color: @syntax-text-color;
> 
> 
> You can quickly check changes (on a mac anyways) by saving the file and hitting
> ctrl-alt-cmd-l to reload Atom.
> 
> If this works for you, it's also worth having a 2nd version of Atom handy which
> doesn't have transparency enabled, cos it can get annoying if you're not in
> performance mode and just wanna do some coding.
> 
> For the record, this was the original post that got me started
> (https://www.reddit.com/r/Atom/comments/33u7ec/transparent_window_test/)
> 
> It's working pretty well for me. Means I can run an OSC-receiving app I've made
> in Unity behind the code. Hopefully in the future will contribute a unity
> package. Right now it's a bit too scrappy/customised to very specific needs.
> Ought to make it a bit more open-ended/flexible before it's worth sharing.>

**Comment by afang** [comment]
Is this a feature already implemented in Electron?

**Comment by LukasBombach** [comment]
@afang I was just looking for this too. If I am not mistaken, by now transparent window-backgrounds are possible, but blurred translucent backgrounds (as in OS X Yosemite) aren't.

**Comment by afang** [comment]
@LukasBombach dang, is there another Javascript desktop framework that can implement transparent bodies?

**Comment by LukasBombach** [comment]
@afang It seems like it is also [an open issue in nw.js](https://github.com/nwjs/nw.js/issues/2817).

Also [I found this video](https://www.youtube.com/watch?v=YvMaVSSI2v4), apparently a demo to a bug report for electron *using a blurred background*, but I cannot find the original issue.

**Comment by LukasBombach** [comment]
One last comment before I spam this issue too much: I talked to the guy of the video I linked to in my previous post: What he did was to blur and reposition an image to fake a blurred translucent background, so no fix there.

**Comment by afang** [comment]
How does he listen to window move events?

**Comment by LukasBombach** [comment]
@afang I believe this is not the place to discuss these questions.

**Comment by fritx** [comment]
@LukasBombach is it implemented with electron in that video?

**Comment by LukasBombach** [comment]
Yes, that is electon, but apparently it's a big hack that does not really work, you can find the guy on twitter for questions: [@FirePanther](https://twitter.com/FirePanther)

**Comment by jiyinyiyong** [comment]
Buggy to me too... strange shadows and blinking rects.

**Comment by maxvoltar** [comment]
+1 here. Really helps bridge the "is this a real Mac app?" feeling.

**Comment by williambout** [comment]
I agree with @maxvoltar . Big :+1:

**Comment by fyodorvi** [comment]
Does anybody have strange shadow bugs?

**Comment by T-Specht** [comment]
I also have strange shadow bugs too and animations are really laggy. Everything seems fine when I oven the DevTools, though.

**Comment by sgarbesi** [comment]
@T-Specht same issue here.

**Comment by sgarbesi** [comment]
https://github.com/atom/electron/issues/4157

**Comment by sgarbesi** [comment]
@T-Specht @fyodorvi Launching Atom with these parameters fixing the shadow bugs for me.

```
--enable-transparent-visuals --disable-gpu
```

I think it's the fact that Atom's using `translate3d` in the CSS, and it's causing the shadow  issues. Finally I can switch to Atom at this point with the transparency working.

**Comment by sgarbesi** [comment]
@T-Specht @fyodorvi @jiyinyiyong @LukasBombach Here's a working port for OS X https://github.com/sgarbesi/atom

**Comment by MentalGear** [comment]
👍  Great !
However, did you notice sluggish performance by deactivating gpu - and can it still be activated on single elements within the UI ?

Eventually, this issue should be addressed by @atom-build .

**Comment by sgarbesi** [comment]
@mentalgear I didn't, but I'm on a quad core laptop with 16gb of memory.

**Comment by fritx** [comment]
Is it able to detect if `transparent` would work on this machine?
In Windows, it seems that if the user didn't turn on `visual styles`, transparent would not work.
In nwjs, I do it by checking `win.isTransparent`.

**Comment by AdamStarkIO** [comment]
Very much interested in this as well!

**Comment by prubini87** [comment]
Guys, what if Chromium has dropped transparency? Isn't it open source? Can't we make a patch or something? ;P

**Comment by Rishab-Honeywell** [comment]
We are using electron on linux CentOS. i need to show a dialog window with a transparent overlay in the background. Currently we are rendering the overlay and dialog into an electron browser window but the window itself is not transparent and hence it is not loking good. Is there any way to fix this on linux centOS.

**Comment by rokejulianlockhart** [comment]
@Rishab-Honeywell, don't ask questions here.
