### ISSUE TITLE
App Before-Quit Event

### ISSUE THREAD

**Issue by rpmadden08** [atom/atom-shell#444]
It would be useful to add another event to the app module that gets triggered before the windows are closed when a user tries to quit. As it is, the "will-quit" event seems to be the only useful quit-related event, but by the time it gets called, all the data related to the windows is gone. This makes it difficult to preserve the state of the application when quitting.

You could save data in the "close" or "closed" event for the BrowserWindow, but you might only want the data to persist when the whole application quits and not just when an individual window is closed.

Alternatively, you could override the app.quit function and do what you need there before calling the original app.quit function, but "app.quit" doesn't seem to get called when a user quits the application from the dock menu. It also seems a bit hacky to have to override a function from a module like that. It would be easier if there was a "before-quit" event that could save all the window states before closing them and terminating the application.

**Comment by CharlieHess** [comment]
+1 on @vsaar's comment.
This kind of behavior is very common for apps that run from the tray, (e.g., nearly all persistent apps). There's not a good way to accomplish it right now.

**Comment by CharlieHess** [comment]
Testing this [branch](https://github.com/atom/atom-shell/pull/1176) with some example code, run-from-tray behavior is pretty trivial to implement:
``` javascript
hostWindow.on('close', (e) => {
  if (hostWindow.forceClose) return;
  e.preventDefault();
  hostWindow.hide();
});

app.on('before-quit', () => {
  hostWindow.forceClose = true;
});

app.on('activate-with-no-open-windows', () => {
  hostWindow.show();
});
```
Thoughts @zcbenz?

**Comment by zcbenz** [comment]
Fixed by #1176.

**Comment by vsaar** [comment]
@CharlieHess, thanks a lot for implementing this. Much appreciated!

**Comment by McPo** [comment]
@CharlieHess It appears that e.preventDefault() is no longer preventing the closing of the browser window and as such the "run-from-tray behaviour" isn't working.

**Comment by mickychen0524** [comment]
@CharlieHess I followed your code but app doesn't get closed when click 'quit' from docker from production build generated by electron builder. any thought?
