### ISSUE TITLE
Add RequestBufferJob for protocol module interceptors

### ISSUE THREAD

**Issue by YuriSolovyov** [atom/atom-shell#566]
Sometimes it is useful to have the ability to send buffer as response when intercepting requests.
Options object can be similar to RequestStringJob.

**Comment by deepak1556** [comment]
added with https://github.com/atom/atom-shell/pull/1208 :)

**Comment by YuriSolovyov** [comment]
Thanks!

**Comment by YuriSolovyov** [comment]
@deepak1556 what if I want to send and image with using this interceptor?
docs say: `Create a request job which accepts a buffer and sends a string as response.` but image is not a string, and it does not have encoding, should I use `binary` encoding for this case?

**Comment by deepak1556** [comment]
it wont work with the current setup as the response wouldnt be encoded to that type, i have started to fix it here https://github.com/deepak1556/atom-shell/commit/a4a9fb544a48c982011894bebdbcfbd371cb20f1 does that test case cover your purpose ? 

/cc @zcbenz

**Comment by YuriSolovyov** [comment]
@deepak1556 my purpose is to be able to send any file of any type as response.
What is the point of `mimeType` then ?
Thanks for your work.

**Comment by zcbenz** [comment]
@YuriSolovyov @deepak1556 RequestBufferJob can send binary data as response since it is taking a `Buffer`, we only need to fix the document.

**Comment by deepak1556** [comment]
But somehow the image data is corrupted when trying to write to a file from the response. Will inspect further

**Comment by YuriSolovyov** [comment]
@deepak1556 it is becasue it is trying to incode is as text when `encoding` is provided ?
Maybe it is better to not assume `urf8` encoding by default and require it explicitly?
And if there is no encoding, just send plain buffer with mime-type...

**Comment by zcbenz** [comment]
@deepak1556 Are you using `$.ajax` to test image data? [It is quite tricky to handle binary data correctly in Web](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Sending_and_Receiving_Binary_Data).

@YuriSolovyov The `encoding` doesn't have any effect if the `mimeType` is a binary type (and it is by default).

**Comment by deepak1556** [comment]
thanks for the link, so i tried with blob type just to see what kind of error it throws

```
    it 'returns RequestBufferJob should send encoded image data', (done) ->
      p = path.join __dirname, 'fixtures', 'asar', 'logo.asar', 'logo.png'
      data = require('native-image').createFromPath(p).toPng()
      job = new protocol.RequestBufferJob(mimeType: 'image/png', data: data)
      handler = remote.createFunctionWithReturnValue job
      protocol.registerProtocol 'atom-buffer-job', handler

      $.ajax
        url: 'atom-buffer-job://fake-host'
        dataType: 'arraybuffer'
        processData: false
        success: (response) ->
          assert.equal response.length, data.length
          require('fs').writeFile 'l.png', response
          protocol.unregisterProtocol 'atom-buffer-job'
          done()
        error: (xhr, errorType, error) ->
          assert false, 'Got error: ' + errorType + ' ' + error
          protocol.unregisterProtocol 'atom-buffer-job'
```

it throws 
```
not ok 58 protocol module registered protocol callback returns RequestBufferJob should send encoded image data
  Error: the string "Uncaught AssertionError: Got error: parsererror No conversion from text to arraybuffer" was thrown, throw an Error :)
```

looks like the response isnt a binary type even thought the mimetype is, any thoughts ?

**Comment by zcbenz** [comment]
I guess jQuery is not working well with binary data, using XMLHttpRequest works well:

```html
<script type="text/javascript" charset="utf-8">
var oReq = new XMLHttpRequest();
oReq.open("GET", "my-protocol://myfile.png", true);
oReq.responseType = "arraybuffer";

oReq.onload = function(oEvent) {
  var blob = new Blob([oReq.response], {type: "image/png"});
  console.log(blob);
};

oReq.send();
</script>
```

**Comment by deepak1556** [comment]
Sweet, works !! :)

```html
  <script>
    var oReq = new XMLHttpRequest();
    oReq.open("GET", "my-protocol://myfile.png", true);
    oReq.responseType = "blob";

    oReq.onload = function(oEvent) {
      var blob = this.response;
      var img = document.createElement('img');
      img.src = window.URL.createObjectURL(blob);
      document.body.appendChild(img)
    }

    oReq.send();
  </script>
```
![screen shot 2015-03-24 at 3 25 46 pm](https://cloud.githubusercontent.com/assets/964386/6799248/2e0d9b72-d23a-11e4-9e6d-93344fb2a16b.png)
