### ISSUE TITLE
set the user data directory

### ISSUE THREAD

**Issue by dounai** [atom/atom-shell#647]
i want save data under my app, not at the default path, does support the chrome command line: '–user-data-dir'.i use the method 'app.commandLine.appendSwitch', but that not work.
and app has only getDataPath method, no setDataPath.
I found the path can be setted in package.json of node-webkit.

**Comment by charliewolf** [comment]
+1. We would like to switch to Atom Shell for an application but it is simply not doable unless it has a unique path--right now ALL atom shell applications share one dir.

**Comment by paulcbetts** [comment]
> right now ALL atom shell applications share one dir.

If you build it from source and change the name, it will use that name instead, that might help work around this issue for now
