### ISSUE TITLE
Any way to extract GPU info using atom-shell?

### ISSUE THREAD

**Issue by caracare521** [atom/atom-shell#663]
Node.js has an OS module and it provides some basic CPU and memory info.
Wondering if we have some similar way to get data about GPU?

For what I know now:
You can type chrome://gpu in google chrome to check all the gpu information you want.
But how to fill the gap between this "chrome://gpu" and atom-shell?

**Comment by caracare521** [comment]
Hi, @zcbenz 
mind telling me how to get this gpu info, I mean which module which method?
I did a search on release page, but didn't manage to find it out.

**Comment by zcbenz** [comment]
It can be got by loading `chrome://gpu` url in browser window, it hasn't been released yet.

**Comment by caracare521** [comment]
@zcbenz  Thank you for the info~

**Comment by caracare521** [comment]
Hi, @zcbenz 
after updated to 22.3, I can load chrome://gpu with a browser window, but I wonder if we can read meaningful data from it into atom-shell? 

Looks like it's not that fancy to grab data using dom operations. 
Just wonder if we have some method like what nw did?
Here is a link of it, https://github.com/nwjs/nw.js/wiki/Extract-info-about-gpu.

Any suggestions?
