### ISSUE TITLE
Metro or "Windows 8" style apps

### ISSUE THREAD

**Issue by salzhrani** [atom/atom-shell#730]
I know it is not a priority, but are there any major hurdles preventing the creation of metro style apps and submitting to the windows store ?

**Comment by zcbenz** [comment]
I'm closing this because we will not work on this, but if someone is interested in this and sends a pull request, we will appreciate it.

**Comment by max-pub** [comment]
Would be really great to see this! Microsoft should step in here to get more apps for its dire store.

**Comment by sapioit** [comment]
One way Microsoft could solve this would be allowing non-Metro apps...

**Comment by sapioit** [comment]
So yeah, they are not interested in getting more apps to their `dire store`...
