### ISSUE TITLE
-webkit-app-region drag disables parts of UI and doesn't act like normal HTML

### ISSUE THREAD

**Issue by iamdriz** [atom/atom-shell#741]
If I have a div with the style of `-webkit-app-region:drag;` and then position any elements on top of it (even using a higher z-index) the elements are no longer usable. Even if the elements are not nested inside the div with the drag applied to it.

Second if I hover over an element (outside of the above div) and then hover the element that has the style of `-webkit-app-region:drag;` then the hover effect is still applied to the previous element. It's as though the app region doesn't act like a normal piece of the webContent and so it doesn't register the unhover... **also noticed this happen when clicking the button to make the window minimized.**

![image](https://cloud.githubusercontent.com/assets/801252/4767199/3f6826ea-5b5b-11e4-9e7c-e87f658234b3.png)

So here I have moved the mouse from the button to the grey area (which has the style of -webkit-app-region:drag;) and it's still showing the button as hovered.

And a third issue is that if I have the following:

~~~
div.title
{
	position: absolute;
	top:0;
	left:0;
	right:76px;
	height:32px;
	background: #eeeeee;
	z-index:500;
	-webkit-app-region:drag;
}

div.title:hover
{
	background: #cccccc;
}
~~~

The hover effect will not work.

**Comment by zcbenz** [comment]
I'm closing this as won't fix, you can find the reason in https://github.com/atom/atom-shell/issues/1354#issuecomment-90315551.
