### ISSUE TITLE
Crash when cleaning up weak handles

### ISSUE THREAD

**Issue by Subash** [atom/atom-shell#767]
![subash_subash____dropbox_prepros_ ___opbox_prepros_ _zsh_ _solarized_dark_ansi_ _147x39](https://cloud.githubusercontent.com/assets/3478693/4871944/4a13f12a-61d0-11e4-9f94-5faa38fcdf20.png)

**Comment by zcbenz** [comment]
It should have been fixed after the upgrade to Chrome 40.
