### ISSUE TITLE
Add support for choosing in which screen (if more than 1) to show the app

### ISSUE THREAD

**Issue by alexandernst** [atom/atom-shell#780]
It's more and more common to find desktops with two or even three screens. Make Atom Shell be able to detect such cases and allow the developer to show the app in a certain screen.

**Comment by iamdriz** [comment]
What's happening with this? I think it's really important to be able to choose which screen windows appear on.

**Comment by iamdriz** [comment]
@zcbenz @paulcbetts Has there been any progress on this feature? I really need to be able to detect multiple screens for an app I am developing. We were using Adobe AIR before which has excellent support for this feature. Perhaps take ideas from there?

**Comment by iamdriz** [comment]
@paulcbetts In Adobe AIR you could target a screen with:

~~~
var largestScreen = null;

if(air.Screen.screens.length > 1) {

    for( index = 0; index < air.Screen.screens.length; ++index) {
        var currentScreen = air.Screen.screens[index];
        if( largestScreen == null ){
            largestScreen = currentScreen;  
        }
        else{
            //Defining largest screen as biggest total area.
            var currentArea = currentScreen.bounds.width * currentScreen.bounds.height;
            var largestArea = largestScreen.bounds.width * largestScreen.bounds.height;
            if(currentArea > largestArea) {
                largestScreen = currentScreen;
            }
        }
    }

} else {

    // Show error that you need a projector screen
    alert('You need more than one screen to run this application.');

}
~~~

And then you could do something like:

`mainWindow = new BrowserWindow({ screen: largestWindow });`

Or

`mainWindow.screen('largestWindow');`

**Comment by iamdriz** [comment]
@zcbenz @paulcbetts What about something like this:

~~~
var Screen = require('screen');
var BrowserWindow = require('browser-window');

var largestScreen = null;

if(Screen.screens.length > 1) {

    for( index = 0; index < Screen.screens.length; ++index) {
        var currentScreen = Screen.screens[index];
        if( largestScreen == null ){
            largestScreen = currentScreen;  
        }
        else {
            var currentScreenSize = currentScreen.workAreaSize;
            var largestScreenSize = largestScreen.workAreaSize;
            var currentArea = currentScreenSize.width * currentScreenSize.height;
            var largestArea = largestScreenSize.width * largestScreenSize.height;
            if(currentArea > largestArea) {
                largestScreen = currentScreen;
            }
        }
    }

} else {

    alert('You need more than one screen to run this application.');

}

// Set screen on initial load
mainWindow = new BrowserWindow({ screen: largestScreen });

// Set screen using method
mainWindow.setScreen(largestScreen);
~~~

**Comment by iamdriz** [comment]
@paulcbetts @zcbenz 

Is this being looked into? It's something we **really really** need for a project we are developing, so would be awesome if we could get some idea of when or even if this is being developed.

Hopefully the code snippet above can be used for a starting point of how it might work in the API.

**Comment by iamdriz** [comment]
@zcbenz @paulcbetts  In fact Node WebKit has this: https://github.com/rogerwang/node-webkit/wiki/Screen

How feasible is it for you to port this code over?

**Comment by paulcbetts** [comment]
The code probably isn't useful to port over, but it'd be great to have the same API too for this and other new things going forward, if what they've got is reasonable

**Comment by iamdriz** [comment]
Is this something that we could see being implemented anytime soon?
