### ISSUE TITLE
 Can't read or write .asar files using fs apis

### ISSUE THREAD

**Issue by joshuawarner32** [atom/atom-shell#782]
I'm working on a client using atom-shell that dynamically downloads and verifies .asar files, using the node APIs, e.g. `fs.createWriteStream` and `fs.createReadStream`.

Whenever I try to operate on .asar files using this method, atom instead tries to read/write a file with a blank name at the root of the archive.  Right now, I'm working around this by downloading the .asar files to a .asar.downloading file and then renaming it to the final name.  Similarly for when I'm verifying a signature on the file, I have to rename it (.asar.verifying), then use `fs.createReadStream`, and pipe it to a crypto hash.

I suggest the `fs.*` functions, when given a path to a .asar file (e.g. `~/foo.asar`), should operate on the file itself, rather than any files in the archive.  The behavior when given a path to a file in the asar (e.g. `~/foo.asar/main.js`) should be unchanged.

**Comment by joshuawarner32** [comment]
@zcbenz, sorry for taking so long to test this in my app, and thanks for the fix... but it doesn't completely work :(.

(Also, sorry for posting on a closed issue; I can open a new issue if you want)

The problem is this: the low-level fs functions that asar.coffee replaces work fine in original-fs (i.e. I actually get access to the original behavior); however, all the higher-level fs functions call through the fs module object (the exports object), so when the low-level functions are swapped out, the high-level functions change to the new behavior.  This is convenient for the .asar functionality, since you only have to swap out those low-level functions to get the uniform asar-handling behavior, but it also means that you can't simply keep references to the high-level functions in original-fs and expect them not to change.

The obvious way to do this in my mind is to have original-fs bypass the normal `require` machinery and obtain a unique version of the exports of the file.  I looked into how to do this a little but I don't see a way, short of modifying nodejs itself.

Any ideas?

**Comment by bwin** [comment]
What about handling an asar archive differently if it ends with a `/`?
`path/to/archive.asar` = as file
`path/to/archive.asar/` = as directory

I don't like the code that checks if a path is an asar archive anyway, but I'll come back to this. Just my 2 cents because this came up.

**Comment by zcbenz** [comment]
@joshuawarner32 I didn't realize some high level `fs` functions depend on exported functions, I'm reopening this issue to track the problem.

> What about handling an asar archive differently if it ends with a /?

If all code you use are written by yourself then it would be fine, but I have to guarantee that no third party code would fail because of the `asar` support, event it is very very rare.

As an example, a script running `walkdir(__dirname)` under the root of `asar` archive will fail if we treat `path/to/archive.asar` as file.

**Comment by benji** [comment]
Using var fs = require("original-fs") works but that's certainly goes against the principle of least surprise, it's very intuitive. spent an hour scratching my head on this.

**Comment by jstlroot** [comment]
I totally agree with @benji.

I cannot understand how assuming this

> Furthermore, it doesn't make any sense for that to ever treat an .asar file as a file.

would be right.

I also wasted a lot of time on this and ended up using 'original-fs'.

**Comment by aprilandjan** [comment]
Like @joshuawarner32 said, Even with the `original-fs`,  extra works need to be done when dealing with some third-party modules which use `fs` internally, That's quite a pain :<
