### ISSUE TITLE
Feature request: Add httpreferrer attribute to iframe

### ISSUE THREAD

**Issue by frankhale** [atom/atom-shell#837]
Since the addition of httpreferrer to webview I now have a use case that requires adding that functionality to the iframe. I've started to look into this but realized that the iframe specific Atom-Shell code was removed via https://github.com/atom/atom-shell/commit/81170d81b3847f01e88d0afa96a06d4d70f651c4 and probably some other commits that I haven't found yet. Would some of that code need to be added back to support extra parameters being added to iframe? I don't currently see any coffeescript API supporting this like there is for webview.

**Comment by frankhale** [comment]
My use case was using the YouTube API which needs an iframe. I think the correct solution is to load a page into a webview to set the httpreferrer and then inject code into webview to do whatever I need to do with the iframe to bootstrap the YouTube API. I'm going to close this as I think this is a perfectly reasonable way to accomplish what I need.

**Comment by frankhale** [comment]
I'm providing this information here so that anyone coming across it can easily reference the solution. I eventually want to get this put into libchromiumcontent upstream if there is a larger need by the community.

I've created a patch to libchromiumcontent / Chromium to add a new switch to allow overriding the HTTP referrer for all requests. So this allows you to spoof the referrer for iframes as well as everything else. I needed this to get around VEVO videos on YouTube being blocked from embedding using the YouTube iframe API.

The following issue has the reference information for those that want to get this feature for themselves today: https://github.com/frankhale/toby/issues/45

**Comment by citkane** [comment]
I have also been struggling with the issue of using the YouTube iframe API in a webview and setting httpReferrer for playback of restricted videos in my Electron App. @frankhale 's various insights I found have been helpful, but I do not want to use a patched version of Electron or override the referrer for all requests

For posterity, I am posting my alternative workaround on this closed topic in case anybody else faces the problem.

Basically, I have abandoned using the Youtube API altogether and have used webview wrappers to access the html5 video object directly. The code logic looks something like this:

HTML:
```html
<div id='youtube-wrap'>
	<webview style="width:100%; height:100%;" id="youtube" httpReferrer="http://youtube.com" src="https://www.youtube.com/embed/ru0K8uYEZWw?autoplay=1&controls=0&color=white&disablekb=1&modestbranding=1&rel=0&showinfo=0" nodeintegration preload="./youtube.js"></webview>
</div>
<div onclick="play()">play</div>
<div onclick="pause()">pause</div>
<div onclick="fullscreen()">fullscreen</div>
```
CSS:
The reason for wrapping the webview will be clear when you consider fullscreen functionality.
```css
#youtube-wrap{
    width:400px;
   height:300px;
}
```

JS logic for the main window:
```javascript
const {ipcRenderer} = require('electron');
var webView;
var ready = false;
window.addEventListener("load",function(){	
	webView = document.getElementById('youtube');								
	webView.addEventListener('dom-ready', function(e) {
        //optionally open a dev console for the webview
		webView.openDevTools();
	})
	webView.addEventListener('ipc-message',function(event){
		if(event.channel === 'media'){
			if(event.args[0]==='vidready'){
				ready=true;
			}
		};
	});
})
function play(){
    if(ready){
        webView.send('media','play');
    }
}
function pause(){
    if(ready){
        webView.send('media','pause');
    }
}
function fullscreen(){
    //this allows the webview to escape the confines of it's wrapper to go fullscreen, while the youtube logic inside the webview is set to 100% width and 100% height - voila! a fullscreen implementation.
    document.getElementById("youtube").webkitRequestFullscreen();
}
```
JS logic for the rendered (webview) window:
This is injected into the webview in html, ie. youtube.js
```javascript
const {ipcRenderer} = require('electron');
var video;
window.addEventListener("load",function(){	
	window.$ = window.jQuery = require('jquery');
	ipcRenderer.sendToHost('media','vidready');	
	video = $('video')[0];
        //we set autoplay to true to force loading of video - now pause.
        video.pause();
	ipcRenderer.on('media',function(send,mess){
		if(mess === 'pause'){
			video.pause();
		}
		if(mess === 'play'){			
			video.play();
		}
	});
});
```
You now have a two way dialogue between the main window and the embedded video, which makes it relatively easy to write video control functions to suite the purpose of your app using HTML5 specifications. You can also view restricted content because the httpReferrer in the HTML webview declaration holds true.

**Comment by frankhale** [comment]
I was messing around with this the other day and came up with this. This will allow you to set the HTTP Referrer for each request.

```
const { session } = require('electron');
```

```javascript
session.defaultSession.webRequest.onBeforeSendHeaders(['https://*.youtube.com/*'], (details, callback) => {
    details.requestHeaders["Referer"] = "https://youtube.com";
    callback({cancel: false, requestHeaders: details.requestHeaders});
  });
```

**Comment by frankhale** [comment]
My previous talk about patching Electron is no longer necessary, see my latest comment with example of overriding the headers to set the referrer for requests.

**Comment by dbuezas** [comment]
@frankhale  the Referer attribute is now read only, this works:
```
webContents.session.webRequest.onBeforeSendHeaders(['*'], (details, callback) => {
        callback({ requestHeaders: {
          ...details.requestHeaders,
          Referer: this.props.httpreferrer,
        } });
      });
```
