### ISSUE TITLE
webview links not working

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom-shell#852]
I'm working on switching my iframe to a webview in the atom `web-browser` package.  It was an easy change.  However my links in the page aren't working.  Nothing happens when I click on them.

For what it's worth here is my code and the inspector display ...

      @content: ->
        @div class:'browser-page', tabindex:-1, =>
          @tag 'webview'

![fvsdv](https://cloud.githubusercontent.com/assets/811455/5149701/4e0fd87e-7180-11e4-9087-46ff344b62f8.gif)

Versions
* **Atom:**       0.150.0
* **Atom-Shell:** 0.19.2
* **OS:**         Microsoft Windows 8.1 Pro with Media Center
* **Misc**
  * apm  0.111.0
  * npm  1.4.4
  * node 0.10.33
  * python 2.7.8
  * git 1.7.11.msysgit.1
  * visual studio 2013

**Comment by zcbenz** [comment]
It seems to have been fixed after the upgrade to Chrome 40.
