### ISSUE TITLE
Windows: BrowserWindow icon should not overwrite native icon

### ISSUE THREAD

**Issue by bpasero** [atom/atom-shell#863]
When the executable already has a nice icon set (high resolution ico file), the browser window icon should not overwrite this icon. 

In fact, I would not expect that I have to set an icon on the browser window if the executable already has an icon set.

The issue is that browser window does not support high resolution ICO (only PNG), where the executable does support it. As soon as I use an icon in the browser window constructor, it replaces my nice high resolution one and the app looks blurry in the task bar.

**Comment by simurai** [comment]
I tried https://github.com/atom/atom/pull/5047 adding multiple resolutions by using different `@` ratios described in the [docs](https://github.com/atom/atom-shell/blob/master/docs/api/image.md#high-resolution-image). But didn't seem to work.

So I think there are these options:

1. Not set a `BrowserWindow` icon, but then it uses some [default icon](https://cloud.githubusercontent.com/assets/430293/5693807/429fe9ee-98fd-11e4-9921-820fed123c3f.png) that doesn't look that great.
2. Use a high res icon, but then it looks pixelated in the window
3. Use a `16px` icon, but then the taskbar icon looks pixelated
4. Use a `32px` icon. Looks not perfect but okay-ish in both, window and taskbar.

Doing 4. is probably the best compromise for now.

ps. Something interesting is that once you right-click and "pin" an icon in the taskbar, it switches to the `ico` which looks perfect.

**Comment by zcbenz** [comment]
I'll look into this.

**Comment by simurai** [comment]
Thanks. If it's possible to use the `ico` (already has all sizes backed in), that would be the simplest. But I don't know enough to judge. :innocent:

**Comment by zcbenz** [comment]
After next release of atom-shell the `exe`'s icon would be used as window icon when `icon` option is not set, which shows in hi res in both task bar and window title bar.

**Comment by simurai** [comment]
Awesome. Thank you!

**Comment by bpasero** [comment]
Cool thanks!!
Am 16.01.2015 04:39 schrieb "simurai" <notifications@github.com>:
