### ISSUE TITLE
<webview>.reload() & <webview>.reloadIgnoringCache() load about:blank instead of page

### ISSUE THREAD

**Issue by christoth** [atom/atom-shell#882]
<webview>.reload() & <webview>.reloadIgnoringCache() load about:blank instead of page with the following error in the WebView DevTools console
Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME

Using v.0.19.5, on Win7, with both file:// and custom schema based URLs.

Alternatively, I can ipc the webview to reload itself using document.location.reload(true), however this is cumbersome if the webview methods already exist.

Thanks in advance.

**Comment by deepak1556** [comment]
this should be fixed with https://github.com/atom/atom-shell/commit/29471ff8b506c5c7ee5fa92d66b7c6c1547f9247 .

**Comment by zcbenz** [comment]
Yeah it has been fixed by #1209, thanks @deepak1556.
