### ISSUE TITLE
capturePage quality

### ISSUE THREAD

**Issue by PassioEtDesiderium** [atom/atom-shell#889]
It would be cool if the quality of the screenshots were adjustable. At the moment, some screenshots have 0.5 - 1 MB, in some cases this is not that handy e.g. if you only want to provide previews or something like that.

**Comment by zcbenz** [comment]
In v0.21.3 there is a new API to do it:
https://github.com/atom/atom-shell/blob/master/docs/api/native-image.md#nativeimagetojpegquality
