### ISSUE TITLE
disable chrome BrowserWindow caching

### ISSUE THREAD

**Issue by maxogden** [atom/atom-shell#891]
opening issue at the request of @zcbenz

my issue is that when using `win.loadUrl` chrome aggressively caches page contents, and I cant get it to load newer versions without reloading with devtools open and the 'disable cache while devtools is open' checked

to reproduce, clone this repo: https://github.com/maxogden/atom-shell-cache-bug

and then run:

```
npm install
npm start
```

you should see `HELLOOOO` in the app

now, quit the atom shell app, edit `client/index.html` in that repo to say something other than `HELLOOOO` and then run `npm start` again

it should still show  `HELLOOOO`

also, @zcbenz and I looked briefly through http://peter.sh/experiments/chromium-command-line-switches/ but did not find one that seemed to do the trick. i also tried this but it doesn't fix the issue:

```js
    win.loadUrl("http://localhost:8765")
    win.webContents.on('did-finish-load', function() {
      console.log('reloading')
      win.reloadIgnoringCache()
    })
```

**Comment by elbriga** [comment]
Hi zcbenz!

What is the location (on windows) that atom-shell uses for caching?

I need to solve the cache problem badly! Is there plans to support the chromium command line switches for disaling cache completely?

Thanks!

**Comment by zcbenz** [comment]
The cache is stored at `require('remote').require('app').getDataPath()`, and unfortunately there is no command line switch in Chromium to disable cache.

**Comment by zcbenz** [comment]
From next release you can use `--disable-http-cache switch` command line switch to disable disk cache.

**Comment by Rameshv** [comment]
hi @zcbenz, it still caches the `webview` content. I have added the `--disable-http-cache ` switch in app, but still it caches the webview..
