### ISSUE TITLE
Can't flash send requests in atom-shell?

### ISSUE THREAD

**Issue by leplay** [atom/atom-shell#936]
I'm trying to embed some Youku videos in atom-shell. Its flash player loaded successful, but I didn't see any  requests sent by the flash player in console. It throw an error after a while. Here is a [screenshot](http://cl.ly/Z1cz).

My codes are following.
main.js: 
```
var app = require('app');
var BrowserWindow = require('browser-window');
require('crash-reporter').start();
var mainWindow = null;

app.on('ready', function() {
  mainWindow = new BrowserWindow({width: 1200, height: 800, 'web-preferences': {'web-security': false, 'plugins': true, 'node-integration': false}});
  mainWindow.loadUrl('file://' + __dirname + '/index.html');
});
```

index.html:
```
<!DOCTYPE html>
<html>
<head>
    <title>Test</title>
</head>
<body>
    <embed src="http://player.youku.com/player.php/sid/XMzQ4NDg0OTUy/v.swf" width="600" height="480" quality="high" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true">
</body>
</html>
```

Thank you!

**Comment by deepak1556** [comment]
@zcbenz looks like we need to append this flag to the render process [`switches::kDisableDirectNPAPIRequests`](https://code.google.com/p/chromium/codesearch#chromium/src/content/renderer/npapi/webplugin_impl.cc&sq=package:chromium&rcl=1427384622&l=1224)

**Comment by zcbenz** [comment]
Chrome will remove support for NPAPI plugins soon, so I'm merging this to #912.
