### ISSUE TITLE
illegal access in child process

### ISSUE THREAD

**Issue by stefanbuck** [atom/atom-shell#961]
Hi,

I use [node-glob](https://github.com/isaacs/node-glob) to find some files on the disk. If I use `require` to 'load' fork.js everything works fine. But in my use case I want to run fork.js as a child process and this produce an **illegal access** error. The `node_modules` folder has CHMOD: drwxr-xr-x. Is this a bug or the expected behaviour of the sandbox?

fork.js
```js
var glob = require('glob');
glob.sync('/usr/local/lib/node_modules/*');
```

browser.js
```js
// Works as expected
// require('./fork.js');

// Doesn't work (see stracktrace below)
require('child_process').fork(__dirname + '/fork.js');
```

Stacktrace:
```
/Users/stefanbuck/projects/sample-atom-shell/node_modules/glob/sync.js:282
      if (this.strict) throw er
                             ^
illegal access
```

And finally the source from node-glob :wink: 
https://github.com/isaacs/node-glob/blob/941d53c8ab6216f43a6f5e8e01245364ba90cfe9/sync.js#L282

**Comment by stefanbuck** [comment]
@zcbenz I found out that `localCompare` is not working in a ChildProcess and glob use this for sorting the paths https://github.com/isaacs/node-glob/blob/941d53c8ab6216f43a6f5e8e01245364ba90cfe9/sync.js#L238

fork.js
````js
console.log('------ Test localeCompare ------');

//  The following messages are not printed in the console
console.log('a'.localeCompare('c')); // -2, or -1, or some other negative value
console.log('c'.localeCompare('a')); // 2, or 1, or some other positive value
console.log('a'.localeCompare('a')); // 0
```

**Comment by stefanbuck** [comment]
On mac I get the **illegal access** message, again. I've created an example repository. https://github.com/stefanbuck/atom-shell-child-process-issue

**Comment by stefanbuck** [comment]
@zcbenz any chance to get a fix soon?

**Comment by zcbenz** [comment]
Not very soon because I'm not sure about the root cause.

**Comment by stefanbuck** [comment]
Hi @zcbenz 
I want to implement a terminate button which stops e.g. a programatic npm install execution or any other node script. I guess a child process would be perfect for that. Any hints how I could do that from your side?

**Comment by zcbenz** [comment]
You can ship the official Node binary with your app and use it to execute npm.

**Comment by stefanbuck** [comment]
:+1: Thank you
