### ISSUE TITLE
showing shadow dom in chrome inspector?

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom-shell#965]
I don't know of this is a chromium bug or problem in atom-shell, but the inspector option `Show Shadow DOM` isn't working.  My checkbox inputs in atom are getting a shadow-root from somewhere and I don't know how to debug this with the inspector option broken.

Im on windows 8.1 with atom 165

**Comment by zcbenz** [comment]
It is strange that there is no `Show Shadow DOM` option on my machine, and the shadow dom seems to show correctly:

![screen shot 2015-01-02 at 12 07 01 pm](https://cloud.githubusercontent.com/assets/639601/5599241/3e6c830e-9278-11e4-8cf2-406d59d1caf8.png)

**Comment by mark-hahn** [comment]
It must be a windows thing.  I'll search for a chrome bug.

**Comment by zcbenz** [comment]
It also works for me on Windows:

![screen shot 2015-01-02 at 2 57 46 pm](https://cloud.githubusercontent.com/assets/639601/5600495/d200db08-928f-11e4-9c67-e39b5b5994ae.png)

**Comment by mark-hahn** [comment]
Thanks.  I wish it worked for me.

**Comment by mark-hahn** [comment]
I found the "problem".  The shadow-root attached is apparently empty.  I didn't even know this was possible.  So the inspector was telling me the right thing.

Sorry for the trouble.  Now I just have to find what is doing this.
