### ISSUE TITLE
Access DOM of another BrowserWindow?

### ISSUE THREAD

**Issue by saschagehlich** [atom/atom-shell#967]
Is it possible to access the DOM of other BrowserWindow instances? I'd like to create two windows, one "controlling" window and one frameless "canvas" window. The "controlling" window should be able to draw stuff to the "canvas" window.

**Comment by zcbenz** [comment]
There is no way to directly control the DOM of another window, you have to make use of `ipc` module to send messages to achieve that.

It works like this:
1. The "control" window sends a "draw xxx" message to browser process
2. The browser process redirects the "draw xxx" message to the "canvas" window
3. The "canvas" window does the drawing when received "draw xxx" message

**Comment by saschagehlich** [comment]
Thank you!
