### ISSUE TITLE
loadHtml instead of loadUrl in atom-shell? (trying to use jade)

### ISSUE THREAD

**Issue by laggingreflex** [atom/atom-shell#968]
Instead of loading HTML from a URL

    window.loadUrl('file://...')

I want to use Jade

    var html = jade.renderFile('file://...');

Is there a way to load this compiled HTML instead of from the URL? Something like `loadHtml(html)`?

**Comment by saschagehlich** [comment]
Have you tried DataURLs? You could use https://github.com/heldr/datauri to generate a DataURL from your String.

**Comment by laggingreflex** [comment]
It worked, thanks!

    var html = jade.renderFile('file://...');
    html = 'data:text/html,' + encodeURIComponent(html);
    window.loadUrl(html);
