### ISSUE TITLE
Protocol URLs throw mixed content warnings

### ISSUE THREAD

**Issue by paulcbetts** [atom/atom-shell#971]
When I try to load fonts in a `WebView` via a protocol URL, I get mixed content warnings:

> Mixed Content: The page at 'https://TEAM.slack.com/messages/general/' was loaded over HTTPS, but requested an insecure font 'slack-resources:fonts/TTF/Lato-Hairline.ttf'. This content should also be served over HTTPS.

This prevents the font from being loaded unless `disablewebsecurity` is passed to the WebView; is there a way in Chromium to indicate that a particular protocol is "trusted"?

**Comment by zcbenz** [comment]
There are also `allow_displaying_insecure_content` and `allow_running_insecure_content` options in Chromium, I guess that's what you want?

**Comment by paulcbetts** [comment]
@zcbenz That might work, but I don't want to disable this warning entirely since it seems like a Generally Good Idea™, only to mark my protocol handler as secure. If that involves a huge amount of work, I could also live with `allow_displaying_insecure_content`

**Comment by paulcbetts** [comment]
Yesssssssssss :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles:

**Comment by pcomans** [comment]
Is there a way to do the same for webview? I con only get this to work for the webframe my application is running in. I am embedding an web app that uses HTTPS and can not display images that are served via HTTP. Is there a way to fix that?

**Comment by bitomule** [comment]
@pcomans any update on it? did you find the way to load http urls? I show external images and can't make it work :(

**Comment by paulcbetts** [comment]
Accessing webFrame works in Webviews too, run it in your WebView preload script

**Comment by bitomule** [comment]
Do you have any example of it? Where's the webview preload script? Thanks ;)

**Comment by etiktin** [comment]
@bitomule you can instruct the webview to use a preload script by using the [preload attribute](https://github.com/atom/electron/blob/master/docs/api/web-view-tag.md#preload).
In your preload script you should be able to use [`webFrame.registerURLSchemeAsSecure('yourscheme')`](https://github.com/atom/electron/blob/master/docs/api/web-frame.md#webframeregisterurlschemeassecurescheme).

**Comment by bitomule** [comment]
@etiktin but I'm not using webview. I just load my url in the window. Is it possible to allow http content if web is loaded that way?

**Comment by etiktin** [comment]
@bitomule I'm not sure I understand you. If you're using a custom protocol and you want to register it as secure, you can use a preload script also with BrowserWindow and not just webviews and call `webFrame.registerURLSchemeAsSecure('yourscheme')` from there (see [BrowserWindow options](https://github.com/atom/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions)).
If that's not what you were asking, I suggest you ask the [community](https://github.com/atom/electron#community).

**Comment by bitomule** [comment]
@etiktin I'm using BrowserWindow and just loading a remote https url. The issue is that site loads non https sites entered by users. I tried BrowserWindow options to disable security but it doesn't work. If you have any idea it would be great, if not I'll try community.

**Comment by etiktin** [comment]
@bitomule it does for me. What version are using? The docs in the master branch of github use the new options syntax introduced in v0.35 (e.g. `web-preferences` is now `webPreferences`), so if you are using an older version you should use the old option names or upgrade to the latest and use the new ones.

**Comment by bitomule** [comment]
@etiktin thanks! Updated electron version and now it works. Thanks thanks thanks!!

**Comment by etiktin** [comment]
@bitomule you're welcome.
