### ISSUE TITLE
Feature request for OSX: Ability to disable AppNap

### ISSUE THREAD

**Issue by hachre** [atom/atom-shell#973]
Hi everyone and a happy new year :)

my App is doing background stuff but keeps getting set into AppNap mode by OS X whenever the memory situation on my machine is becoming bad.

OSX doesn't seem to ever wake it up again, though, unless I look at the app's window, which for a background app is of course undesirable.

There is support for disabling AppNap on a per-app basis in OSX by setting:
```
defaults write com.Your.App NSAppSleepDisabled -bool YES
```

This creates a file in ~/Library/Preferences/com.Your.App.plist and adds the given value to it.

I have noticed that Chrome also seems to store the position and dimensions of the devtools window in there.

Would it be possible for atom-shell to hook into that mechanism, which already seems to exist in Chrome, and to expose an API like require("app").setAppNapEnabled(false) ?

That would be great...
Thanks!

**Comment by zcbenz** [comment]
OS X doesn't provide an API to disable AppNap, and from the documents I think they don't encourage developers to do that, so I'm closing this as won't fix.

**Comment by crucialfelix** [comment]
There is an API for it. For applications with real time continual processes (audio, timers, responding to external messages like MIDI / OSC) it is needed.

See: https://github.com/supercollider/supercollider/blob/2744239f2252eebb2d952b7aa56134d53ce243ea/common/SC_Apple.mm

I think its this:
```
unint64_t options = (NSActivityUserInitiated | NSActivityIdleSystemSleepDisabled) | NSActivityLatencyCritical;

id activity = [[NSProcessInfo processInfo] beginActivityWithOptions: options reason:@"avoiding audio hiccups and reducing latency"];
```

http://stackoverflow.com/questions/19847293/disable-app-nap-in-macos-10-9-mavericks-application

**Comment by unboundmusic** [comment]
This was added to the core electron API http://electron.atom.io/docs/api/power-save-blocker/#powersaveblockerstarttype
