### ISSUE TITLE
"Module did not self-register" after successful "apm install ."

### ISSUE THREAD

**Issue by Larivact** [atom/atom-shell#976]
I would like to use the native module [node-sass](https://github.com/sass/node-sass) in my atom-shell project. I carefully followed your [instructions](https://github.com/atom/atom-shell/blob/master/docs/tutorial/using-native-node-modules.md) ```apm install .``` works but when I am starting my application I get the uncaught exception "Module did not self-register".

I am using atom-shell v0.20.3.
```apm -v``` output:
```
apm  0.114.0
npm  1.4.4
node 0.10.33
python 2.7.8
git
visual studio 2013
```

**Comment by zcbenz** [comment]
You have to use apm v0.112.0 to build modules for atom-shell v0.20.x, but it is recommended to set the `ATOM_NODE_VERSION` environment variable so you don't need to care about the version of `apm`.

```bash
$ env ATOM_NODE_VERSION=0.20.3 apm install .
```

**Comment by Larivact** [comment]
@zcbenz still getting the exception
```
set ATOM_NODE_VERSION=0.20.3
apm install .
```
(windows cmd)

**Comment by Larivact** [comment]
@zcbenz  still doesn't work.
```
set ATOM_NODE_VERSION=0.20.3
apm install .
```
(windows cmd)

**Comment by paulcbetts** [comment]
To be honest, you'll save yourself a ton of personal suffering if you use [grunt-build-atom-shell](github.com/paulcbetts/grunt-build-atom-shell), rebuilding native Node modules is one of the trickiest parts of Atom Shell atm

**Comment by Larivact** [comment]
@paulcbetts 404

**Comment by Larivact** [comment]
@zcbenz still doesn't work

**package.json**
```json
{
  "name"    : "atom-cito",
  "version" : "0.1.0",
  "main"    : "main.js",
  "dependencies": {
  	"node-sass": "2.0.0-beta"
  }

}
```
**main.js**
```js
var sass = require('node-sass');
```

**Comment by Larivact** [comment]
1. How do I install a specific version of apm? The apm readme says nothing about that. Do I have to manually build it?
2. I would like to see an actual example of how to build a native node.js module with grunt-build-atom-shell for atom-shell.
3. Why is this issue closed?

**Comment by paulcbetts** [comment]
> I would like to see an actual example of how to build a native node.js module with grunt-build-atom-shell for atom-shell.

When you use `grunt-build-atom-shell`, modules are rebuilt for you automatically, there is no explicit step. You just `npm install` as always, then make sure `build-atom-shell` is at the front of your build process

**Comment by Larivact** [comment]
@paulcbetts how do I make sure that build-atom-shell is at the front of my build process?
I just don't understand the hole Gruntfile.js stuff.

**Comment by paulcbetts** [comment]
> Your documentation is all about how to build atom-shell from Git, nothing about how to actually rebuild native modules.

You don't _have_ to think about rebuilding native modules, that's the whole point - it all happens automatically.
