### ISSUE TITLE
String.localeCompare crashes in Node mode

### ISSUE THREAD

**Issue by zcbenz** [atom/atom-shell#979]
When running in Node mode, `String.localeCompare` will crash the process, see also https://github.com/atom/atom/issues/4725.

**Comment by park9140** [comment]
@zcbenz, any movement on this?  I can't release the next version of `atom-typescript-tools` without it.

**Comment by park9140** [comment]
@zcbenz,  ha you beat me too it I got it in my head to try and fix this getting as far as discovering it was the ICU that was not quite set up correctly.  Thanks for so much for fixing this.  Perhaps I will win the race next time, now that I went to all the trouble to learn how to compile and debug the project :)
