### ISSUE TITLE
Add --disable-web-security switch to atom

### ISSUE THREAD

**Issue by stumitchell** [atom/atom-shell#986]
hi similar to https://github.com/atom/atom-shell/issues/498 do we have to request support for each switch we want to use or is there some so other way to get to them?

I not that http://peter.sh/experiments/chromium-command-line-switches/ contains alo of possible switches

Stu

**Comment by zcbenz** [comment]
There is a `web-security` option in `BrowserWindow`:
https://github.com/atom/atom-shell/blob/master/docs/api/browser-window.md#new-browserwindowoptions

**Comment by stumitchell** [comment]
Thanks that worked
