### ISSUE TITLE
Communicate between two windows

### ISSUE THREAD

**Issue by iamdriz** [atom/atom-shell#991]
How can I communicate between two BrowserWindows in atom-shell?

I have been using Intercom.js https://github.com/diy/intercom.js/ for a project which works fine in the browser world, but doesn't work in the atom-shell world... Any ideas for how to get Intercom.js working? Or an alternative?

**Comment by iamdriz** [comment]
I need to be able to do complex communications like this in Window 1:

`intercom.emit('notice', { func: 'buildGame', params: [boxes, winner] });`

And in Window 2:

~~~
intercom.on('notice', function(data) {
	if(data.func){
		var callback = data.func;
		if(data.params) {
			var params = [];
			for(var i=0;i<data.params.length;i++)
			{
				params.push(data.params[i]);
			}
			window[callback].apply(window, params);
		} else {
			window[callback]();
		}
	}
});
~~~

So this might call `buildGame(6, 4);` in Window 2

I've seen this: https://github.com/atom/atom-shell/blob/master/docs/api/ipc-browser.md

But how would I do the same thing?

**Comment by bwin** [comment]
In your browser-code (what you call "server-side") you hold references to your BrowserWindows.
From the renderer-code ("frontend"; inside BrowserWindow) you send msgs through IPC to the browser-code, which can send it to the BrowserWindow.
AFAIK

**Comment by iamdriz** [comment]
Okay so from my understanding, this is how I would do it:

**index1.html**
~~~
ipc.send('asynchronous-message', { func: 'buildGame', params: [boxes, winner] });
~~~

**index2.html**
~~~
ipc.on('asynchronous-message', function(event, data) {
  if(data.func){
        var callback = data.func;
        if(data.params) {
            var params = [];
            for(var i=0;i<data.params.length;i++)
            {
                params.push(data.params[i]);
            }
            window[callback].apply(window, params);
        } else {
            window[callback]();
        }
    }
});
~~~

But the code is inside the BrowserWindow HTML pages... and I haven't got anything in the server-side bit (e.g. the main.js) regarding the ipc...

Is that correct?

**Comment by bwin** [comment]
No, you send your `asynchronous-message` from `index1.html` to your `main.js`. There you need to receive it and send it to `index2.html`.
Sorry, haven't got time to write example code.

**Comment by bwin** [comment]
Sorry, forgot to mention that you send from Browser to Renderer with `yourBrowserWindow.webContents.send(args...)`.
see https://github.com/atom/atom-shell/blob/master/docs/api/browser-window.md#webcontentssendchannel-args

**Comment by iamdriz** [comment]
So I need a combination of both to do what I want?

**Comment by bwin** [comment]
yes.

Very simple example:

**main.js**
```
win1 = new BrowserWindow ... // index1.html
win2 = new BrowserWindow ... // index2.html
ipc.on('my-msg', function(event, arg) {
  win2.webContents.send(event, arg);
  // if you need communication in both ways, you have to check event.sender
  // then you know where it's coming from and therefore know where to send it
});
```

**index1.html**
```
ipc.send('my-msg', 'hi');
```

**index2.html**
```
ipc.on('my-msg', function(arg) {
  console.log('this was sent from win1', arg);
});
```

**Comment by iamdriz** [comment]
@bwin How do I use IPC in the webpage?

As when I do:

~~~
window.$ = window.jQuery = require('./js/jquery.min.js');

var remote = require('remote');

var ipc = remote.require('ipc');

$(document).ready(function(){

	ipc.on('talk', function(data) {
		if(data.func){
			var callback = data.func;
			if(data.params) {
				var params = [];
				for(var i=0;i<data.params.length;i++)
				{
					params.push(data.params[i]);
				}
				window[callback].apply(window, params);
			} else {
				window[callback]();
			}
		} else {
			var element = document.getElementById('message');
			element.innerHTML = data.message;
		}
	});

});
~~~

I get an error that ipc is not defined... even though I'm calling it using remote?

**Comment by bwin** [comment]
Don't use `remote` for ipc. There are actually 2 different ipc modules in atom-shell. `require('ipc')` uses the right one in respect to where you're calling it from.
Have a look at
https://github.com/atom/atom-shell/blob/master/docs/api/ipc-browser.md
and
https://github.com/atom/atom-shell/blob/master/docs/api/ipc-renderer.md

**Comment by bwin** [comment]
I created a Gist for you at https://gist.github.com/bwin/5ed15cc0620a6a63f081
In the devtools-console of win1 call `sendIpcMsg()` and you send a simple msg to win2.

**Comment by iamdriz** [comment]
@bwin I've got it working :) Your typo threw me but it's all working now. Thanks.

**Comment by bwin** [comment]
:+1:

**Comment by Altiano** [comment]
Why there is no direct communication ?

**Comment by iamdriz** [comment]
@Altiano There is. You just need to make sure that it comes from where the process was spawned.

**Comment by Altiano** [comment]
I mean from renderer process to another one.. How.?

**Comment by paulcbetts** [comment]
```
let myWindows = require('remote').getAllWindows();
myWindows[1].webContents.send('an-event-from-window-zero');
```

**Comment by Altiano** [comment]
this probably work, but how can you be sure that `myWindows[1]` would return the first window ?

**Comment by Altiano** [comment]
After some test, this is what I do:

```
let myWindow = require('remote').BrowserWindow.fromId(id);
myWindow].webContents.send('an-event-from-window-zero');
```

**Comment by greggman** [comment]
Just FYI, I pushed a major change to [other-window-ipc](https://github.com/greggman/other-window-ipc). The new one uses channels which makes certain uses much easier.  A channel listens for connections. Each channel can have multiple streams.

**Comment by dtaburetkin** [comment]
What wrong with:

main
`const EventEmitter = require('events')
class MyEmitter extends EventEmitter {}
global.events = new MyEmitter()`

any js in project
`var events = require('electron').remote.getGlobal('events')
events.emit('event')`

?
