### ISSUE TITLE
BrowserWindow creates blank window

### ISSUE THREAD

**Issue by iamdriz** [atom/atom-shell#992]
In the latest releases of atom-shell when I add code for a BrowserWindow. It loads the window my code has requested but then also loads an additional blank one.

So for example I have this code:

~~~
mainWindow = new BrowserWindow({
	   "width": 800,
	   "height": 600,
	   "fullscreen":false,
	   "kiosk": false,
	   "resizable":false,
	   "frame":true,
	   "web-preferences":{
		  "web-security":false
	   },
	   "show":true
	});
~~~

But I get an empty white window (that is resizeable, and note that my code has this set to false) in addition to my own window that I have requested.

What's really interesting is that if I set frame to false, this doesn't happen! And if I delete the code above then it doesn't happen either. So it's like calling a browserwindow with a frame in the latest versions causes a duplicate window to be created.

I can confirm this bug happens in 0.19.5 and 0.20.3 but DOES NOT in 0.18.1, so it seems a recent fix in the later versions causes this issue. I'm testing on Windows 7.

**Comment by bwin** [comment]
I can't reproduce this on 0.19.5 or 0.20.5 on Windows 7 HP 64bit.
I get exactly one empty window.

```
var app = require('app');
var BrowserWindow = require('browser-window');

app.on('ready', function() {
  mainWindow = new BrowserWindow({
    "width": 800,
    "height": 600,
    "fullscreen":false,
    "kiosk": false,
    "resizable":false,
    "frame":true,
    "web-preferences":{
      "web-security":false
    },
    "show":true
  });
});
```

Why do you specify default values like `fullscreen: false`?

**Comment by iamdriz** [comment]
Okay so I'm an idiot and had this line in my webpage:

~~~
// create a popup
var popup = window.open('projector.html');
~~~

Which **obviously** caused the problem. However it doesn't happen in the older versions of atom-shell... weird :S
