### ISSUE TITLE
Webview: no access to contentWindow

### ISSUE THREAD

**Issue by bpasero** [atom/atom-shell#997]
Not sure if this can be supported given how webview is implemented, but when you try to access webview.contentWindow as misleading error message is printed:

 <webview>: contentWindow is not available at this time. It will become available when the page has finished loading.

This is when trying to access it from the webviews did-stop-loading handler.

Code:

```
<!DOCTYPE html>
<html>
  <head>
    <title>Hello World!</title>
  </head>
  <script>
	onload = function() {
	    var webview = document.getElementById("foo");
	   
	    webview.addEventListener("did-stop-loading", function() {
	    	console.log("did finish: " + webview.contentWindow);
	    });
	  }
  </script>
  <body>
    <h1>Hello World!</h1>
    We are using node.js <script>document.write(process.version)</script>
    and atom-shell <script>document.write(process.versions['atom-shell'])</script>.

    <webview id="foo" src="about:blank" style="width:640px; height:480px"></webview>
  </body>
</html>
```

**Comment by cldwalker** [comment]
I'm also seeing the same issue on osx 10.9 with atom-shell 0.20.4. For me, it's more than a misleading error message because it prevents access to the contentWindow

**Comment by bpasero** [comment]
+1 for DOM access to the window in webview but I guess thats not possible because the webview runs another process.

**Comment by zcbenz** [comment]
The `contentWindow` in Chrome only has a [ContentWindow.postMessage](https://developer.chrome.com/apps/tags/webview#type-ContentWindow) method, which you can use [`<webview>.send`](https://github.com/atom/atom-shell/blob/master/docs/api/web-view-tag.md#webviewsendchannel-args) to replace. There is no way to access the DOM of `<webview>` directly.

I'll remove this property to avoid confusions.

**Comment by KidkArolis** [comment]
Is there any way to use `ContentWindow.postMessage` on a webview now that the `contentWindow` reference has been removed? The `webview.send` can be used as a replacement in general, but I have some existing code that relies on postMessage and it would be super handy to just use that to communicate with webviews.

**Comment by paulcbetts** [comment]
@KidkArolis I'd just shim it back in

**Comment by KidkArolis** [comment]
If anyone else runs into this issue, I have a little shim for postMessage available over here: https://github.com/KidkArolis/electronic-post-message
